### ISSUE TITLE
fix numerical inversion of characteristic function to determine probability density

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#106]
https://math.stackexchange.com/questions/29299/characteristic-function-of-the-normal-distribution

**Comment by crowlogic** [comment]
junit.framework.AssertionFailedError: expected:<0.5697828247309229> but was:<0.0>
	at junit@4.13.2/junit.framework.Assert.fail(Assert.java:57)
	at junit@4.13.2/junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:120)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:129)
	at junit@4.13.2/junit.framework.TestCase.assertEquals(TestCase.java:277)
	at arb4j/arb.operators.integraltransforms.FourierTransformTest.testDuality(FourierTransformTest.java:68)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by crowlogic** [comment]
Caused by: java.lang.AssertionError: TODO: implement 'error' function erf
	at arb4j/arb.stochastic.StandardGaussianDistribution.evaluate(StandardGaussianDistribution.java:36)
