### ISSUE TITLE
expression parser crashes when the argument of a function is a binary operation

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#215]
```
ExpressionTest
arb.expressions.ExpressionTest
testFunctionOfInputPlusAConstant(arb.expressions.ExpressionTest)
java.lang.NullPointerException: Cannot invoke "arb.expressions.nodes.Node.generate(org.objectweb.asm.MethodVisitor)" because "this.left" is null
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:53)
	at arb4j/arb.expressions.nodes.FunctionCall.generationFunctionCall(FunctionCall.java:138)
	at arb4j/arb.expressions.nodes.FunctionCall.lambda$0(FunctionCall.java:116)
	at arb4j/arb.expressions.nodes.FunctionCall.generate(FunctionCall.java:109)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:276)
	at arb4j/arb.expressions.Expression.generateClass(Expression.java:169)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:45)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:635)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:623)
	at arb4j/arb.expressions.ExpressionTest.testFunctionOfInputPlusAConstant(ExpressionTest.java:61)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

testFunctionOfVariablePlusAVariable(arb.expressions.ExpressionTest)
java.lang.NullPointerException: Cannot invoke "arb.expressions.nodes.Node.generate(org.objectweb.asm.MethodVisitor)" because "this.left" is null
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:53)
	at arb4j/arb.expressions.nodes.FunctionCall.generationFunctionCall(FunctionCall.java:138)
	at arb4j/arb.expressions.nodes.FunctionCall.lambda$0(FunctionCall.java:116)
	at arb4j/arb.expressions.nodes.FunctionCall.generate(FunctionCall.java:109)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:276)
	at arb4j/arb.expressions.Expression.generateClass(Expression.java:169)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:45)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:635)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:623)
	at arb4j/arb.expressions.ExpressionTest.testFunctionOfVariablePlusAVariable(ExpressionTest.java:80)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

testFunctionOfVariablePlusAConstant(arb.expressions.ExpressionTest)
java.lang.NullPointerException: Cannot invoke "arb.expressions.nodes.Node.generate(org.objectweb.asm.MethodVisitor)" because "this.left" is null
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:53)
	at arb4j/arb.expressions.nodes.FunctionCall.generationFunctionCall(FunctionCall.java:138)
	at arb4j/arb.expressions.nodes.FunctionCall.lambda$0(FunctionCall.java:116)
	at arb4j/arb.expressions.nodes.FunctionCall.generate(FunctionCall.java:109)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:276)
	at arb4j/arb.expressions.Expression.generateClass(Expression.java:169)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:45)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:635)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:623)
	at arb4j/arb.expressions.ExpressionTest.testFunctionOfVariablePlusAConstant(ExpressionTest.java:95)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
Here is the output of testFunctionOfInputPlusAConstant with Expression.debugParser set to true

```
Generating arb/expressions/TanhOpenParenOnePlusInputCloseParen108136571614933 from expression 'tanh(t+1)'
// class version 64.65535 (-65472)
// access flags 0x1
public class arb/expressions/TanhOpenParenOnePlusInputCloseParen108136571614933 implements arb/functions/real/RealFunction {


Generating evaluate with methodDesc='(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object;' signature='(Larb/Real;IILarb/Real;)Larb/Real;'

  // access flags 0x1
  // signature (Larb/Real;IILarb/Real;)Larb/Real;
  // declaration: arb.Real evaluate(arb.Real, int, int, arb.Real)
  public evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object;

   L0

parseFirst: ch=t position=0
parseSecond: ch=t position=0
parseLast: ch=t position=0
parse: ch=t position=0
parseName: startPos=0, position=4, identifier='tanh' ch='('
Ate expected '(' and advanced to char 't' at pos 5
parseFunctionOrVariable: startPos=0, position=5, identifier='tanh', isFunction=true, node=null
parseFirst: ch=t position=5
parseSecond: ch=t position=5
parseLast: ch=t position=5
parse: ch=t position=5
parseName: startPos=5, position=6, identifier='t' ch='+'
parseFunctionOrVariable: startPos=5, position=6, identifier='t', isFunction=false, node=null
Ate expected '+' and advanced to char '1' at pos 7
parseSecond: ch=1 position=7
parseLast: ch=1 position=7
parse: ch=1 position=7
Adding constant c0 to Expression[expression=tanh(t+1), shortClassName=TanhOpenParenOnePlusInputCloseParen108136571614933] with value 1
newFunctionCall name=tanh arg=Add[
  left=
   Literal[value=1],
  right=
 null
]
}
```

**Comment by crowlogic** [comment]
if you update you will find libarblib.so in the root directory, just add 

```
-Djava.library.path=. ` -ea`  --enable-preview --enable-native-access=arb4j 
```
to the commandline params 

```
crow@hotspot:~/a$ ldd libarblib.so 
	linux-vdso.so.1 (0x00007ffd84085000)
	libflint-arb.so.2 => /lib/x86_64-linux-gnu/libflint-arb.so.2 (0x00007fc356a00000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc356600000)
	libflint.so.17 => /lib/x86_64-linux-gnu/libflint.so.17 (0x00007fc355e00000)
	libmpfr.so.6 => /lib/x86_64-linux-gnu/libmpfr.so.6 (0x00007fc356db6000)
	libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fc356d33000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc356917000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc356ec7000)
	libntl.so.44 => /lib/x86_64-linux-gnu/libntl.so.44 (0x00007fc355a00000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc355600000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc356d0d000)
	libgf2x.so.3 => /lib/x86_64-linux-gnu/libgf2x.so.3 (0x00007fc356cfe000)
crow@hotspot:~/a$ file libarblib.so 
libarblib.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=fc74c2e79b53c76198c1af6678ced167007c0b67, with debug_info, not stripped
```
