### ISSUE TITLE
Optimize Handling of Integer-Valued Literal Constants in Expression Compiler

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#222]
#### Description:
Currently, the expression compiler processes all numerical literals uniformly, typically requiring the construction of `arb.Real` objects. This issue proposes to optimize the handling of integer-valued literal constants by directly calling the integer-version of the relevant arithmetic or mathematical function, bypassing the need to create `arb.Real` objects.

#### Motivation:
Using integer-specific versions of functions should provide performance improvements by avoiding the overhead associated with constructing `arb.Real` objects.

#### Proposed Implementation:
- During the parsing phase, identify integer-valued literal constants.
- For such constants, map them directly to the integer-specific versions of the arithmetic or mathematical functions within the Arbitrary Precision Library.

#### Criteria for Success:
- Integer-valued literals are correctly identified and mapped to integer-specific function calls.
- Confirm performance gains through benchmarks.
- New behavior is verified through tests and is well-documented.

By more efficiently handling integer-valued literals, this change aims to improve the overall performance of the expression compiler.

**Comment by crowlogic** [comment]
This will require emitting the appropriate instructions to cause the integers to be pushed onto the stack rather than references to arb.Real instances constructed from their String representations

**Comment by crowlogic** [comment]
top-of-the-stack

**Comment by crowlogic** [comment]
```java
  // Method descriptor #8 (Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object;
  // Signature: (Larb/Integer;IILarb/Real;)Larb/Real;
  // Stack: 6, Locals: 5
  public java.lang.Object evaluate(java.lang.Object in, int order, int bits, java.lang.Object result);
     0  aload_0 [this]
     1  getfield nCnMinusOneTimesCn.C : TwoTimesnPlusαPlusβ [13]
     4  aload_1 [in]
     5  checkcast arb.Integer [15]
     8  aload_0 [this]
     9  getfield nCnMinusOneTimesCn.c0 : arb.Integer [19]
    12  iload_3 [bits]
    13  aload 4 [result]
    15  checkcast arb.Real [21]
    18  invokevirtual arb.Integer.sub(arb.Real, int, arb.Real) : arb.Real [25]
```

line 18

```java
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    nCnMinusOneTimesCn.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @18: invokevirtual
  Reason:
    Type 'arb/Integer' (current frame, stack[2]) is not assignable to 'arb/Real'
  Current Frame:
    bci: @18
    flags: { }
    locals: { 'nCnMinusOneTimesCn', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'TwoTimesnPlusαPlusβ', 'arb/Integer', 'arb/Integer', integer, 'arb/Real' }
  Bytecode:
    0000000: 2ab4 000d 2bc0 000f 2ab4 0013 1d19 04c0
    0000010: 0015 b600 191c 1d2a b400 1db6 0021 c000
    0000020: 1559 2ab4 0024 b600 282b c000 0f1c 1d2a
    0000030: b400 2bb6 0021 c000 151d 1904 c000 15b6
    0000040: 002e b0                                

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:219)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1256)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:80)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testC(JacobiPolynomialTest.java:84)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
will have to handle this case... not that high of a priority presently

```java
[crow@c15 20240306-10:43:02PM]~/a$ decompile 1Plus2Plus3.class 
INFO:  JVM info: Oracle Corporation - 21.0.1 - 21.0.1+12-LTS-29
INFO:  Scanning classes from file 1Plus2Plus3.class
INFO:  Loading Class: 1Plus2Plus3 from file 1Plus2Plus3.class
INFO:  Preprocessing class 1Plus2Plus3
INFO:  ... done
INFO:  Decompiling class 1Plus2Plus3
INFO:  ... done
import arb.Real;
import arb.functions.real.RealFunction;

public class 1Plus2Plus3 implements RealFunction {
   public Real a;
   public Real α;
   public Real b;
   public Real r;
   public Real v;
   public Real x;
   public Real y;
   public Real z;
   public Real λ;
   public Real n;
   public int i1 = (int)(new int());

   public Real evaluate(Real in, int order, int bits, Real result) {
      return 1.add(2, bits, i1).add(3, bits, result);
   }

   public void close() {
      i1.close();
   }
}
```

**Comment by crowlogic** [comment]
Not a big priority can revisit later if it becomes necessary
