### ISSUE TITLE
Expression compiler , indexing 

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#240]
### New Indexing Features in the Expression Compiler

In this update, the expression compiler for the Arbitrary Precision Library gains two indexing methods for variable references:

1. **Square Bracket Indexing**: Use `X[3]` to access the third element of vector `X`.
  
2. **Unicode Subscript Indexing**: `X₃` does the same as `X[3]`, giving you another way to access vector elements.

Both methods map to the same internal operation and default to Java's 0-based indexing. This feature allows for more expressive and flexible code without sacrificing performance.

**Comment by crowlogic** [comment]
```java
java.lang.IllegalArgumentException: Invalid class name (must be an internal class name): arb/expressions/v[Three]82351844382065
	at org.objectweb.asm.util@9.5/org.objectweb.asm.util.CheckMethodAdapter.checkInternalClassName(CheckMethodAdapter.java:1337)
	at org.objectweb.asm.util@9.5/org.objectweb.asm.util.CheckMethodAdapter.checkInternalName(CheckMethodAdapter.java:1315)
	at org.objectweb.asm.util@9.5/org.objectweb.asm.util.CheckClassAdapter.visit(CheckClassAdapter.java:233)
	at arb4j/arb.expressions.Compiler.generateFunctionInterface(Compiler.java:240)
	at arb4j/arb.expressions.Expression.generate(Expression.java:236)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:83)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:425)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:950)
	at arb4j/arb.expressions.Expression.express(Expression.java:909)
	at arb4j/arb.expressions.ExpressionTest.testIndexedVariable(ExpressionTest.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalArgumentException: Invalid null (must not contain . ; [ or /): arb/expressions/v[Three]82351844382065
	at org.objectweb.asm.util@9.5/org.objectweb.asm.util.CheckMethodAdapter.checkIdentifier(CheckMethodAdapter.java:1252)
	at org.objectweb.asm.util@9.5/org.objectweb.asm.util.CheckMethodAdapter.checkInternalClassName(CheckMethodAdapter.java:1335)
	... 26 more

```

**Comment by crowlogic** [comment]
todo: handle indexing a variable by another variable

idea: add a Variables<Integer> variable called indexVariables to Expression

function: sum or add for example could be implemented in expression parser by registering an index variable with a sub-expression (whatever the expression for the summand is ).

```java
java.lang.AssertionError: TODO: handle variable index references
	at arb4j/arb.expressions.nodes.Variable.generate(Variable.java:125)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:399)
	at arb4j/arb.expressions.Expression.generate(Expression.java:238)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:83)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:437)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:983)
	at arb4j/arb.expressions.Expression.express(Expression.java:953)
	at arb4j/arb.expressions.ExpressionTest.testVariableIndexedByAVariable(ExpressionTest.java:73)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.NoSuchFieldError: k
	at v_k_.evaluate(Unknown Source)
	at arb4j/arb.expressions.ExpressionTest.testVariableIndexedByAVariable(ExpressionTest.java:75)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```
