### ISSUE TITLE
pi constant in expression compiler broke

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#243]
```java
junit.framework.AssertionFailedError: expected:<3.14159265358979323846264338327950288419716939937510582097494459230781640628620 +/- 1.93e-77> but was:<0>
	at junit@4.13.2/junit.framework.Assert.fail(Assert.java:57)
	at junit@4.13.2/junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:78)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:86)
	at junit@4.13.2/junit.framework.TestCase.assertEquals(TestCase.java:246)
	at arb4j/arb.expressions.ExpressionTest.testPi(ExpressionTest.java:354)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
glitch: its`` erroneously declaring π to be the input variable

```Generating arb/expressions/π from expression 'π'
// class version 64.65535 (-65472)
// access flags 0x1
public class arb/expressions/π implements arb/functions/real/RealFunction {


Generating evaluate with methodDesc='(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object;' signature='(Larb/Real;IILarb/Real;)Larb/Real;'

  // access flags 0x1
  // signature (Larb/Real;IILarb/Real;)Larb/Real;
  // declaration: arb.Real evaluate(arb.Real, int, int, arb.Real)
  public evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object;

   L0

eatFirst(depth=0): ch=π position=0
eatSecond(depth=0): ch=π position=0
eatLast(depth=0): ch=π position=0
eat(depth=0): ch=π position=0
eatName(depth=0): startPos=0, position=1, identifier='π' index='null' ch='?'
eatFunctionInvocationOrVariableReference(depth=0): startPos=0, position=1, identifier='Reference[name=π, index=null]', isFunction=false
Independent Variable declared to be: Variable[name=INPUT(Reference[name=π, index=null])]
eat() returning Variable[name=INPUT(Reference[name=π, index=null])]
Variable[name=INPUT(Reference[name=π, index=null])]
    ALOAD 1
```

**Comment by crowlogic** [comment]
test

```java
shell> plot(-10,30,128,express("π*J0(t)"));
|  Exception java.lang.RuntimeException: Undefined reference to variable 'Reference[name=t, index=null]' in Expression[expression=π*J0(t), shortClassName=πTimesJZerot], independent variable is Variable[name=INPUT(Reference[name=π, index=null])]
|        at Variable.<init> (Variable.java:69)
|        at Expression.eatFunctionInvocationOrVariableReference (Expression.java:619)
|        at Expression.eat (Expression.java:509)
|        at Expression.eatLast (Expression.java:641)
|        at Expression.eatSecond (Expression.java:834)
|        at Expression.eatFirst (Expression.java:536)
|        at Expression.eatFunctionInvocationOrVariableReference (Expression.java:596)
|        at Expression.eat (Expression.java:509)
|        at Expression.eatLast (Expression.java:641)
|        at Expression.eatSecond (Expression.java:842)
|        at Expression.eatFirst (Expression.java:536)
|        at Expression.eatRootNode (Expression.java:424)
|        at Expression.generateEvaluationMethod (Expression.java:399)
|        at Expression.generate (Expression.java:238)
|        at Compiler.compile (Compiler.java:83)
|        at Compiler.compile (Compiler.java:437)
|        at Expression.instantiate (Expression.java:983)
|        at Expression.express (Expression.java:942)
|        at Expression.express (Expression.java:931)
|        at (#3:1)
|  Caused by: java.lang.NoSuchFieldException: Reference[name=t, index=null]
|        at Variable.<init> (Variable.java:73)
|        ...

```
