### ISSUE TITLE
finish ChebyshevyPolynomials implementation

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#248]
```java
package arb.functions.polynomials.orthogonal;

import java.util.Iterator;

import arb.OrthogonalBasis;
import arb.Real;
import arb.domains.Domain;
import arb.functions.real.RealFunction;

public class ChebyshevyPolynomials extends
                                   JacobiPolynomials<ChebyshevPolynomialOfTheFirstKind>

{

  @Override
  public Iterator<ChebyshevPolynomialOfTheFirstKind> iterator()
  {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public RealFunction getOrthogonalMeasure()
  {
    assert false : "TODO: return 1/sqrt(1-t^2)";
    return null;
  }

  @Override
  public Domain<Real> getDomain()
  {
    assert false : "TODO: return [-1,1]";
    return null;
  }

}
```

**Comment by crowlogic** [comment]
comes automatically with https://github.com/crowlogic/arb4j/issues/254 since a ChebyshevPolynomial is a special case of a Jacobi polynomial

**Comment by crowlogic** [comment]
```java
java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    F.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @148: aload_0
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @148
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/Real' }
  Stackmap Frame:
    bci: @148
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { }
  Bytecode:
    0000000: 2ab4 000e 9a00 072a b600 122a b400 162b
    0000010: c000 18b5 001d 2ab4 0021 b600 2757 2ab4
    0000020: 002a 2ab4 002d b600 3157 2ab4 0034 2ab4
    0000030: 0037 b600 3157 2ab4 0021 2ab4 0016 2ab4
    0000040: 002a 1d2a b400 3ab9 003d 0400 c000 231d
    0000050: b600 4157 2ab4 002a b600 452a b400 34b6
    0000060: 0049 9eff d42a b400 212a b400 4d2b c000
    0000070: 18b5 004f 2ab4 0052 b600 2757 2ab4 002a
    0000080: 2ab4 002d b600 3157 2ab4 0055 2ab4 0058
    0000090: b600 3157 2ab4 0052 2ab4 004d 2ab4 002a
    00000a0: 1d2a b400 5bb9 003d 0400 c000 231d b600
    00000b0: 4157 2ab4 002a b600 452a b400 55b6 0049
    00000c0: 9eff d42a b400 521d 1904 c000 23b6 005f
    00000d0: b0                                     
  Stackmap Table:
    same_frame(@11)
    same_frame(@54)
    same_frame_extended(@148)

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j@0.85/arb.expressions.Expression.constructNewInstance(Expression.java:1163)
	at arb4j@0.85/arb.expressions.Expression.instantiate(Expression.java:1151)
	at arb4j@0.85/arb.expressions.Expression.instantiate(Expression.java:126)
	at arb4j@0.85/arb.functions.Function.express(Function.java:154)
	at arb4j@0.85/arb.expressions.nodes.nary.ProductTest.testRatioOfProducts(ProductTest.java:83)

```
