### ISSUE TITLE
implement Jacobi polynomials

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#254]
#### Description:
The `arb4j` library currently lacks implementations for Jacobi polynomial recursions. This feature will be developed using the Java API as there are no analogs in ArbLib. The aim is to extend the library's functionality to include Jacobi polynomial recursions.

For the Jacobi polynomials:

Initial conditions:
```math
P_0(x) = 1
```
```math
P_1(x) = \frac{1}{2}(\alpha + \beta + 2) + (\alpha - \beta) x
```

Recurrence relation:
```math
P_n(x) = a_n x P_{n-1}(x) + b_n P_{n-2}(x)
```

Common factor:
```math
c_n = \frac{2n + \alpha + \beta - 1}{(2n + \alpha + \beta)(2n - 2 + \alpha + \beta)}
```

Simplified coefficients:
```math
a_n = c_n (\alpha^2 - \beta^2)
```
```math
b_n = c_n (2n + \alpha + \beta)
```

**Comment by crowlogic** [comment]
can proceed now that the RealFunction registration via the [[Context]] is supported

**Comment by crowlogic** [comment]
next up


```c
void arb_poly_shift_left(arb_poly_t res, const arb_poly_t poly, slong n);

void arb_poly_shift_right(arb_poly_t res, const arb_poly_t poly, slong n);
```

which maps to

```java
  public static void arb_poly_shift_left(RealPolynomial res, RealPolynomial poly, int n)
  {
    arblibJNI.arb_poly_shift_left(RealPolynomial.getCPtr(res), res, RealPolynomial.getCPtr(poly), poly, n);
  }

  public static void arb_poly_shift_right(RealPolynomial res, RealPolynomial poly, int n)
  {
    arblibJNI.arb_poly_shift_right(RealPolynomial.getCPtr(res), res, RealPolynomial.getCPtr(poly), poly, n);
  }
```

**Comment by crowlogic** [comment]
2nd

**Comment by crowlogic** [comment]
depends on 

[Expression Compiler: Relax Requirement That Operands implement the Field interface #274 ](https://github.com/crowlogic/arb4j/issues/274)

**Comment by crowlogic** [comment]
# The Jacobi Polynomial Recursions

\

```math
A (n) = \frac{{(2 n + \alpha + \beta - 1)  (\alpha^2 - \beta^2 + (2 n + \alpha + \beta - 2) (2 n + \alpha + \beta) x)}}{{2 n (n + \alpha + \beta)  (2 n + \alpha + \beta - 2)}}
```

```math
B (n) = - \frac{{(- 1 + \alpha + n)  (- 1 + n + \beta)  (2 n + \alpha + \beta)}}{{n (n + \alpha + \beta)  (2 n + \alpha + \beta - 2)}}
```

```math
P (n) = \begin{cases}
    1 & \text{if } n = 0 \\
    \frac{1}{2}  (2 + \alpha + \beta) x - \frac{1}{2} \beta + \frac{1}{2} \alpha & \text{if } n = 1 \\
    A (n) P (n - 1) + B (n) P (n - 2) & \text{otherwise}
\end{cases}
```

**Comment by crowlogic** [comment]
```java
java.lang.NoSuchMethodError: 'arb.RealPolynomial arb.Integer.P(int, arb.RealPolynomial)'
	at nAnTimeszTimesPnMinusOneMinusBnTimesPnMinusTwoDividedByTwo.evaluate(Unknown Source)
	at arb4j@0.81/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP(JacobiPolynomialTest.java:150)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
this is what the decompiled generated code for the Jacobi polynomial recursion function (P)

```java
package arb.functions;

import arb.Integer;
import arb.Real;
import arb.RealPolynomial;

public class A
{
  public Integer                           c0  = new Integer("1");
  public Integer                           c1  = new Integer("2");
  public RealPolynomial                    l0  = new RealPolynomial();
  public Integer                           l1  = new Integer();
  public RealPolynomial                    l2  = new RealPolynomial();
  public RealPolynomial                    l3  = new RealPolynomial();
  public Real                              l4  = new Real();
  public Real                              l5  = new Real();
  public Integer                           l6  = new Integer();
  public RealPolynomial                    l7  = new RealPolynomial();
  public RealPolynomial                    l8  = new RealPolynomial();
  public RealPolynomial                    l9  = new RealPolynomial();
  public Real                              l10 = new Real();
  public Real                              l11 = new Real();
  public Function<Integer, RealPolynomial> P   = null;
  public Function<Integer, RealPolynomial> A   = null;
  public Function<Real, Real>              B   = null;
  public Function<Real, Real>              E   = null;

  public RealPolynomial evaluate(Integer in, int order, int bits, RealPolynomial result)
  {
    return A.evaluate(in, order, bits, l0)
            .mul(P.evaluate(in.sub(c0, bits, l1), order, bits, l2), bits, l3)
            .sub(B.evaluate(l4.set(in), order, bits, l5)
                  .mul(P.evaluate(in.sub(c1, bits, l6), order, bits, l7), bits, l8),
                 bits,
                 l9)
            .div(E.evaluate(l10.set(in), order, bits, l11), bits, result);
  }

  public void close()
  {
    c0.close();
    c1.close();
    l0.close();
    l1.close();
    l2.close();
    l3.close();
    l4.close();
    l5.close();
    l6.close();
    l7.close();
    l8.close();
    l9.close();
    l10.close();
    l11.close();
  }
}```

**Comment by crowlogic** [comment]
TODO: inject reference to self into self.P reference so in after its constructed it would be this.P=P or outside newP.P=newP

**Comment by crowlogic** [comment]
woo

```java
p(0)=RealPolynomial[length=1, coeffs=1, remainder=null]
p(2,x)=RealPolynomial[length=3, coeffs=[-0.375, 0, 0.75], remainder=null]
P(2.1)=0.375
P(2,2=2.625)
A(3,1.5)=RealPolynomial[length=2, coeffs=[0, 30], remainder=null]
B(1)=0.34375
C(1)=2.75
E(3)=18
F(1)=0.5625
p(1,x)=RealPolynomial[length=2, coeffs=[0, 0.5], remainder=null]
```

**Comment by crowlogic** [comment]
```java
P(0)=RealPolynomial[length=1, coeffs=1]
P(1)=RealPolynomial[length=2, coeffs=[0, 0.5]]
P(2)=RealPolynomial[length=3, coeffs=[-0.375, 0, 0.75]]
P(3)=RealPolynomial[length=4, coeffs=[0, -0.9375, 0, 1.25]]
P(4)=RealPolynomial[length=5, coeffs=[0.2734375, 0, -2.1875, 0, 2.1875]]
P(5)=RealPolynomial[length=6, coeffs=[0, 1.23046875, 0, -4.921875, 0, 3.9375]]
P(6)=RealPolynomial[length=7, coeffs=[-0.2255859375, 0, 4.060546875, 0, -10.828125, 0, 7.21875]]
P(7)=RealPolynomial[length=8, coeffs=[0, -1.46630859375, 0, 11.73046875, 0, -23.4609375, 0, 13.40625]]
P(8)=RealPolynomial[length=9, coeffs=[0.196380615234375, 0, -6.2841796875, 0, 31.4208984375, 0, -50.2734375, 0, 25.13671875]]
```

**Comment by crowlogic** [comment]
![Screenshot from 2024-01-17 16-47-55](https://github.com/crowlogic/arb4j/assets/41244135/63bd3c33-6b48-4599-bb7f-86824c4afbdd)

**Comment by crowlogic** [comment]
```java
Exception in thread "main" java.lang.AssertionError: TODO: instantiate a new instance, we cant use the existing one because for the same reason its not thread-safe, is that intermediate variables are delcared as fields of the compiled expression
	at arb4j/arb.expressions.Expression.injectContextualFunctionReferences(Expression.java:539)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:594)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:100)
	at arb4j/arb.functions.Function.express(Function.java:147)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:103)
	at arb4j/arb.functions.JacobiPolynomialPrototype.main(JacobiPolynomialPrototype.java:72)
```

**Comment by crowlogic** [comment]
instantiate the self-referencing class on-demand not at constructor
time.. instances cant be shared due to the intermediate variables
clashing in the case of recursion and concurrent access

```java
java.lang.NullPointerException: Cannot invoke "arb.functions.Function.evaluate(Object, int, int, Object)" because "this.P" is null
	at P.evaluate(Unknown Source)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP2(JacobiPolynomialTest.java:170)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
a buncha poppycock does not make cause some old fart fails to get the point

```java
java.lang.AssertionError: generate the instructions to get call getClass(), construct a new instance using the copy-constructor so that the field values are assigned properly,  this=FunctionCall[name=P,  function=Mapping[name=P, func=null, domain=arb.Integer, range=arb.RealPolynomial, functionInterface=null], arg=n - 1, targetResultType=arb.RealPolynomial]
	at arb4j/arb.expressions.nodes.unary.FunctionCall.generateContextualFunctionCall(FunctionCall.java:191)
	at arb4j/arb.expressions.nodes.unary.FunctionCall.generate(FunctionCall.java:115)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:98)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:97)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:97)
	at arb4j/arb.expressions.nodes.unary.UnaryOperation.generate(UnaryOperation.java:73)
	at arb4j/arb.expressions.nodes.unary.When.generate(When.java:78)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:473)
	at arb4j/arb.expressions.Expression.generate(Expression.java:369)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:101)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:75)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:117)
	at arb4j/arb.functions.Function.express(Function.java:147)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:103)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP0(JacobiPolynomialTest.java:139)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
sleep

```java
java.lang.AssertionError: addend is null
	at arb4j/arb.Real.add(Real.java:1313)
	at arb4j/arb.functions.C.evaluate(C.java:18)
	at arb4j/arb.functions.C.evaluate(C.java:1)
	at arb4j/arb.functions.F.evaluate(F.java:19)
	at arb4j/arb.functions.F.evaluate(F.java:1)
	at arb4j/arb.functions.A.evaluate(A.java:25)
	at arb4j/arb.functions.A.evaluate(A.java:1)
	at arb4j/arb.functions.P.evaluate(P.java:56)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP3(JacobiPolynomialTest.jav
```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: operand is null
	at arb4j/arb.Real.add(Real.java:1313)
	at arb4j/arb.functions.C.evaluate(C.java:18)
	at arb4j/arb.functions.C.evaluate(C.java:1)
	at arb4j/arb.functions.F.evaluate(F.java:19)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testF(JacobiPolynomialTest.java:97)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
excellent

```java
crow@c17:~/a$ cat P.java
import arb.Integer;
import arb.Real;
import arb.RealPolynomial;
import arb.functions.Function;

public class P implements Function<Integer, RealPolynomial> {
   public Integer const1 = new Integer("0");
   public Integer const2 = new Integer("1");
   public Integer const3 = new Integer("2");
   public Real α;
   public Real β;
   public Real r1 = new Real();
   public Real r2 = new Real();
   public RealPolynomial rp1 = new RealPolynomial();
   public RealPolynomial rp2 = new RealPolynomial();
   public RealPolynomial rp3 = new RealPolynomial();
   public RealPolynomial rp4 = new RealPolynomial();
   public Integer i1 = new Integer();
   public RealPolynomial rp5 = new RealPolynomial();
   public RealPolynomial rp6 = new RealPolynomial();
   public Real r3 = new Real();
   public Real r4 = new Real();
   public Integer i2 = new Integer();
   public RealPolynomial rp7 = new RealPolynomial();
   public RealPolynomial rp8 = new RealPolynomial();
   public RealPolynomial rp9 = new RealPolynomial();
   public Real r5 = new Real();
   public Real r6 = new Real();
   public Function<Integer, RealPolynomial> P;
   public Function<Integer, RealPolynomial> A;
   public Function<Real, Real> B;
   public Function<Real, Real> C;
   public Function<Real, Real> E;

   public RealPolynomial evaluate(Integer in, int order, int bits, RealPolynomial result) {
      if (this.α == null) {
         throw new AssertionError("α is null");
      } else if (this.β == null) {
         throw new AssertionError("β is null");
      } else if (this.A == null) {
         throw new AssertionError("A is null");
      } else if (this.B == null) {
         throw new AssertionError("B is null");
      } else if (this.C == null) {
         throw new AssertionError("C is null");
      } else if (this.E == null) {
         throw new AssertionError("E is null");
      } else {
         return switch(in.getSignedValue()) {
            case 0 -> result.set(this.const2);
            case 1 -> ((Real)this.C.evaluate(this.r1.set(this.const2), order, bits, this.r2))
            .mul(result.identity(), bits, this.rp1)
            .sub(this.β, bits, this.rp2)
            .add(this.α, bits, this.rp3)
            .div(this.const3, bits, result);
            default -> {
               RealPolynomial var5 = (RealPolynomial)this.A.evaluate(in, order, bits, this.rp4);
               if (this.P == null) {
                  this.P = new P(this);
               }

               var5 = var5.mul((RealPolynomial)this.P.evaluate(in.sub(this.const2, bits, this.i1), order, bits, this.rp5), bits, this.rp6);
               Real var10001 = (Real)this.B.evaluate(this.r3.set(in), order, bits, this.r4);
               if (this.P == null) {
                  this.P = new P(this);
               }

               yield var5.sub(
                     var10001.mul((RealPolynomial)this.P.evaluate(in.sub(this.const3, bits, this.i2), order, bits, this.rp7), bits, this.rp8), bits, this.rp9
                  )
                  .div((Real)this.E.evaluate(this.r5.set(in), order, bits, this.r6), bits, result);
            }
         };
      }
   }

   public P() {
      this.initializeContextualFunctions();
   }

   public void initializeContextualFunctions() {
      this.A = new A();
      this.B = new B();
      this.C = new C();
      this.E = new E();
   }

   public P(P var1) {
      this();
      this.α = var1.α;
      this.β = var1.β;
   }

   public void close() {
      this.const1.close();
      this.const2.close();
      this.const3.close();
      this.r1.close();
      this.r2.close();
      this.rp1.close();
      this.rp2.close();
      this.rp3.close();
      this.rp4.close();
      this.i1.close();
      this.rp5.close();
      this.rp6.close();
      this.r3.close();
      this.r4.close();
      this.i2.close();
      this.rp7.close();
      this.rp8.close();
      this.rp9.close();
      this.r5.close();
      this.r6.close();
      this.P.close();
   }
}
```

**Comment by crowlogic** [comment]
its done like this

```java
  public static void instantiateAndInitialize(MethodVisitor mv,
                                              String ownerClass,
                                              String fieldType,
                                              String fieldName,
                                              FieldAssignment[] fieldAssignments)
  {
    String typeDesc = "L" + fieldType + ";";
    Label  label    = new Label();
    mv.visitLabel(label);

    // Instantiate new object and assign to field
    mv.visitVarInsn(Opcodes.ALOAD, 0);
    mv.visitTypeInsn(Opcodes.NEW, fieldType);
    mv.visitInsn(Opcodes.DUP);
    mv.visitMethodInsn(Opcodes.INVOKESPECIAL, fieldType, "<init>", "()V", false);
    mv.visitFieldInsn(Opcodes.PUTFIELD, ownerClass, fieldName, typeDesc);

    // Set fields in the new object
    for (FieldAssignment assignment : fieldAssignments)
    {
      mv.visitVarInsn(Opcodes.ALOAD, 0);
      mv.visitFieldInsn(Opcodes.GETFIELD, ownerClass, fieldName, typeDesc);
      mv.visitVarInsn(Opcodes.ALOAD, 0);
      mv.visitFieldInsn(Opcodes.GETFIELD, ownerClass, assignment.fieldName, assignment.fieldDescriptor);
      mv.visitFieldInsn(Opcodes.PUTFIELD, fieldType, assignment.fieldName, assignment.fieldDescriptor);
    }

    // Call initializeContextualFunctions
    mv.visitVarInsn(Opcodes.ALOAD, 0);
    mv.visitFieldInsn(Opcodes.GETFIELD, ownerClass, fieldName, typeDesc);
    mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, fieldType, "initializeContextualFunctions", "()V", false);
  }
```

**Comment by crowlogic** [comment]
```java
package arb.functions;

import arb.Integer;
import arb.Real;
import arb.RealPolynomial;

public class P implements
               Function<Integer, RealPolynomial>
{
  public Integer        const1;
  public Integer        const2;
  public Integer        const3;
  public Real           α;
  public Real           β;
  public Real           G;
  public Real           r1;
  public Real           r2;
  public RealPolynomial rp1;
  public RealPolynomial rp2;
  public RealPolynomial rp3;
  public RealPolynomial rp4;
  public Integer        i1;
  public RealPolynomial rp5;
  public RealPolynomial rp6;
  public Real           r3;
  public Real           r4;
  public Integer        i2;
  public RealPolynomial rp7;
  public RealPolynomial rp8;
  public RealPolynomial rp9;
  public Real           r5;
  public Real           r6;
  public P              P;
  public A              A;
  public B              B;
  public C              C;
  public E              E;
  public F              F;

  public RealPolynomial evaluate(Integer in, int order, int bits, RealPolynomial result)
  {
    if (this.α == null)
    {
      throw new AssertionError("α is null");
    }
    else if (this.β == null)
    {
      throw new AssertionError("β is null");
    }
    else if (this.A == null)
    {
      throw new AssertionError("A is null");
    }
    else if (this.B == null)
    {
      throw new AssertionError("B is null");
    }
    else if (this.C == null)
    {
      throw new AssertionError("C is null");
    }
    else if (this.E == null)
    {
      throw new AssertionError("E is null");
    }
    else
    {
      RealPolynomial var10000;
      switch (((Integer) in).getSignedValue())
      {
      case 0:
        var10000 = ((RealPolynomial) result).set(this.const2);
        break;
      case 1:
        var10000 = ((Real) this.C.evaluate(this.r1.set(this.const2),
                                           order,
                                           bits,
                                           this.r2)).mul(((RealPolynomial) result).identity(), bits, this.rp1)
                                                    .sub(this.β, bits, this.rp2)
                                                    .add(this.α, bits, this.rp3)
                                                    .div(this.const3, bits, (RealPolynomial) result);
        break;
      default:
        var10000 = (RealPolynomial) this.A.evaluate((Integer) in, order, bits, this.rp4);
        if (this.P == null)
        {
          this.P = new P(this);
        }

        var10000 = var10000.mul((RealPolynomial) this.P.evaluate(((Integer) in).sub(this.const2, bits, this.i1),
                                                                 order,
                                                                 bits,
                                                                 this.rp5),
                                bits,
                                this.rp6);
        Real var10001 = (Real) this.B.evaluate(this.r3.set((Integer) in), order, bits, this.r4);
        if (this.P == null)
        {
          this.P = new P(this);
        }

        var10000 = var10000.sub(var10001.mul((RealPolynomial) this.P.evaluate(((Integer) in).sub(this.const3,
                                                                                                 bits,
                                                                                                 this.i2),
                                                                              order,
                                                                              bits,
                                                                              this.rp7),
                                             bits,
                                             this.rp8),
                                bits,
                                this.rp9)
                           .div((Real) this.E.evaluate(this.r5.set((Integer) in), order, bits, this.r6),
                                bits,
                                (RealPolynomial) result);
      }

      return var10000;
    }
  }

  public P()
  {
    this.const1 = new Integer("0");
    this.const2 = new Integer("1");
    this.const3 = new Integer("2");
    this.r1     = new Real();
    this.r2     = new Real();
    this.rp1    = new RealPolynomial();
    this.rp2    = new RealPolynomial();
    this.rp3    = new RealPolynomial();
    this.rp4    = new RealPolynomial();
    this.i1     = new Integer();
    this.rp5    = new RealPolynomial();
    this.rp6    = new RealPolynomial();
    this.r3     = new Real();
    this.r4     = new Real();
    this.i2     = new Integer();
    this.rp7    = new RealPolynomial();
    this.rp8    = new RealPolynomial();
    this.rp9    = new RealPolynomial();
    this.r5     = new Real();
    this.r6     = new Real();
    this.initializeContext();
  }

  public void initializeContext()
  {
    A var10001 = this.A = new A();
    this.A.α = this.α;
    this.A.β = this.β;
    this.A.G = this.G;
    this.A.initializeContext();
    this.A = var10001;
    B var1 = this.B = new B();
    this.B.α = this.α;
    this.B.β = this.β;
    this.B.G = this.G;
    this.B.initializeContext();
    this.B = var1;
    C var2 = this.C = new C();
    this.C.α = this.α;
    this.C.β = this.β;
    this.C.G = this.G;
    this.C.initializeContext();
    this.C = var2;
    E var3 = this.E = new E();
    this.E.α = this.α;
    this.E.β = this.β;
    this.E.G = this.G;
    this.E.initializeContext();
    this.E = var3;
  }

  public P(P var1)
  {
    this();
    this.α = var1.α;
    this.β = var1.β;
  }

  public void close()
  {
    this.const1.close();
    this.const2.close();
    this.const3.close();
    this.r1.close();
    this.r2.close();
    this.rp1.close();
    this.rp2.close();
    this.rp3.close();
    this.rp4.close();
    this.i1.close();
    this.rp5.close();
    this.rp6.close();
    this.r3.close();
    this.r4.close();
    this.i2.close();
    this.rp7.close();
    this.rp8.close();
    this.rp9.close();
    this.r5.close();
    this.r6.close();
    this.P.close();
  }

}
```

gawDAMN this is a lot of work

**Comment by crowlogic** [comment]
woop

```
P(0,x)=1
P(1,x)=0.5*x
P(2,x)=0.75*x² - 0.375
P(3,x)=1.25*x³ - 0.9375*x
P(4,x)=2.1875*x⁴ - 2.1875*x² + 0.2734375
P(5,x)=3.9375*x⁵ - 4.921875*x³ + 1.23046875*x
P(6,x)=7.21875*x⁶ - 10.828125*x⁴ + 4.060546875*x² - 0.2255859375
P(7,x)=13.40625*x⁷ - 23.4609375*x⁵ + 11.73046875*x³ - 1.46630859375*x
P(8,x)=25.13671875*x⁸ - 50.2734375*x⁶ + 31.4208984375*x⁴ - 6.2841796875*x² + 0.196380615234375
P(9,x)=47.48046875*x⁹ - 106.8310546875*x⁷ + 80.123291015625*x⁵ - 22.2564697265625*x³ + 1.6692352294921875*x
```

**Comment by crowlogic** [comment]
TODO: make the function references final and initalized in the field
declaration and only propagate the variable references in the
intiializeContext call

**Comment by crowlogic** [comment]
mastered
