### ISSUE TITLE
epression compiler not trimming whitespace properly

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#262]
```java
java.lang.RuntimeException: Undefined reference to variable 'Reference[name= x, index=null]' in Expression[expression=½*(α + β + 2) + x*(α - β), shortClassName=½TimesαPlusβPlusTwoPlusxTimesαMinusβ], independent variable is Variable[name=INPUT(Reference[name= β, index=null])]
	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:73)
	at arb4j/arb.expressions.Expression.eatFunctionInvocationOrVariableReference(Expression.java:615)
	at arb4j/arb.expressions.Expression.eat(Expression.java:505)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:637)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:811)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:541)
	at arb4j/arb.expressions.Expression.eatRootNode(Expression.java:420)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:395)
	at arb4j/arb.expressions.Expression.generate(Expression.java:234)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:82)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:471)
	at arb4j/arb.expressions.Compiler.instantiate(Compiler.java:588)
	at arb4j/arb.expressions.Compiler.express(Compiler.java:626)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomial.<init>(JacobiPolynomial.java:55)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:15)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NoSuchFieldException: Reference[name= x, index=null]
	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:77)
	... 31 more

```

**Comment by crowlogic** [comment]
need to locate the parsing logic, particularly where eatName and eatFunctionInvocationOrVariableReference are implemented, and ensure that variable names are trimmed of any leading or trailing whitespace before they are processed further.
