### ISSUE TITLE
add graphical output features to InteractiveREPLShell 

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#268]
The [InteractiveREPLShell](https://github.com/crowlogic/arb4j/wiki/InteractiveREPLShell) provides a graphical interface for the arb4j project intended to serve as a versatile and enhanced replacement for the standard [JShell](https://github.com/crowlogic/arb4j/wiki/JShell) with additional graphical capabilities. This class offers an interactive Read-Eval-Print Loop (REPL) environment that provides the execute of Java code and displaying results in various formats, including text, graphs, and other visual representations.

This REPL shell is particularly tailored for the arb4j project, a robust Java API for high-performance mathematical computations and representations. It leverages the JShell API for executing Java code snippets and extends its functionality with capabilities to display complex outputs such as LaTeX formatted formulas, 2D/3D graphs, and more, catering to the needs of scientific and computational tasks in arb4j.

**Comment by crowlogic** [comment]
need to handle latex format errors

```java
isLatex $\frac{a}{B}$
isLatex $\frac{a}{\frac{c}{d}}}$
isLatex Error: Found a closing '}' without an opening '{'!
Stack Trace:
org.scilab.forge.jlatexmath.ParseException: Found a closing '}' without an opening '{'!
	at jlatexmath@1.0.7/org.scilab.forge.jlatexmath.TeXParser.parse(TeXParser.java:725)
	at jlatexmath@1.0.7/org.scilab.forge.jlatexmath.TeXFormula.<init>(TeXFormula.java:261)
	at jlatexmath@1.0.7/org.scilab.forge.jlatexmath.TeXFormula.<init>(TeXFormula.java:245)
	at arb4j/arb.viz.VisualShell.displayResult(VisualShell.java:149)
	at arb4j/arb.viz.VisualShell.displayResult(VisualShell.java:132)
	at arb4j/arb.viz.VisualShell.displayResults(VisualShell.java:102)
	at arb4j/arb.viz.VisualShell.evaluateInput(VisualShell.java:80)
	at arb4j/arb.viz.VisualShell.lambda$2(VisualShell.java:184)
	at javafx.base@20.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@20.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@20.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@20.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@20.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@20.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@20.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@20.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@20.0.2/javafx.scene.Node.fireEvent(Node.java:8944)
	at javafx.controls@20.0.2/com.sun.javafx.scene.control.behavior.TextFieldBehavior.fire(TextFieldBehavior.java:161)
	at javafx.controls@20.0.2/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(TextInputControlBehavior.java:344)
	at javafx.controls@20.0.2/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@20.0.2/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@20.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@20.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@20.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@20.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@20.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@20.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@20.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@20.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@20.0.2/javafx.scene.Scene.processKeyEvent(Scene.java:2190)
	at javafx.graphics@20.0.2/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2711)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)
	at javafx.graphics@20.0.2/com.sun.glass.ui.View.handleKeyEvent(View.java:542)
	at javafx.graphics@20.0.2/com.sun.glass.ui.View.notifyKey(View.java:966)
	at javafx.graphics@20.0.2/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@20.0.2/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```
