### ISSUE TITLE
expression compiler: add ability to view expression tree graphically

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#275]
using https://github.com/crowlogic/fxbinarytree is a good start

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: Auto-generated method stub
	at arb4j/arb.expressions.nodes.unary.FunctionReference.getBranches(FunctionReference.java:309)
	at arb4j/arb.expressions.AbstractSyntaxTreeModel.indexBranches(AbstractSyntaxTreeModel.java:40)
	at arb4j/arb.expressions.AbstractSyntaxTreeModel.<init>(AbstractSyntaxTreeModel.java:25)
	at arb4j/arb.expressions.Expression.newSyntaxTree(Expression.java:1654)
	at arb4j/arb.utensils.treetext.TextTreeTest.testPrintAbstractSyntaxTree(TextTreeTest.java:30)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```
