### ISSUE TITLE
expression compiler: suport tuple operands in the domain and range for multivariate expressions, polynomials, etc

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#283]
```java
java.lang.NoSuchFieldError: Undefined reference to variable 'z' in Expression[expression=n➔(A(n) * z * P[n-1,z] - B(n) * P[n-2,z]) / 2, shortClassName=nAnTimeszTimesP_nMinusOne,z_MinusBnTimesP_nMinusTwo,z_DividedByTwo], independent variable is Variable[name=INPUT(n)]
	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:77)
	at arb4j/arb.expressions.Expression.eatFunctionInvocationOrVariableReference(Expression.java:793)
	at arb4j/arb.expressions.Expression.eat(Expression.java:669)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:817)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:1008)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:703)
	at arb4j/arb.expressions.Expression.eat(Expression.java:650)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:817)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:1000)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:703)
	at arb4j/arb.expressions.Expression.eatRootNode(Expression.java:538)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:501)
	at arb4j/arb.expressions.Expression.generate(Expression.java:308)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:284)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:234)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1196)
	at arb4j/arb.functions.IntegerToRealPolynomialFunction.express(IntegerToRealPolynomialFunction.java:21)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:110)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testA(JacobiPolynomialTest.java:26)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
this in Expression.java


```java
  public void parseOptionalIndependentVariableSpecification()
  {
    int rightArrowIndex = expression.indexOf('➔');
    if (rightArrowIndex != -1)
    {
      independentVariableNode = new Variable<D, R, F>(this,
                                                      new Reference(expression.substring(0, rightArrowIndex)),
                                                      0);
      if (verbose)
      {
        out.println("independentVariableNode=" + independentVariableNode);
        out.flush();
      }
      position = rightArrowIndex;
      // assert independentVariable == null : "TODO: specify independent variable " +
      // independentVariable;
    }
  }
```

**Comment by crowlogic** [comment]
```java
arb.expressions.UndefinedReferenceException: Undefined reference to variable 'x' in Expression[expression=(n,x)➔(F(n)*x + G)*(C(n)/2 - 1/2), shortClassName=nxFnTimesxPlusGTimesCnDividedByTwoMinusOneDividedByTwo], independent variable is Variable[name=INPUT((n,x))]
	at arb4j/arb.expressions.nodes.Variable.resolveReference(Variable.java:199)
	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:80)
	at arb4j/arb.expressions.Expression.eatFunctionInvocationOrVariableReference(Expression.java:790)
	at arb4j/arb.expressions.Expression.eat(Expression.java:666)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:814)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:1005)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:700)
	at arb4j/arb.expressions.Expression.eat(Expression.java:647)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:814)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:997)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:700)
	at arb4j/arb.expressions.Expression.eatRootNode(Expression.java:536)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:499)
	at arb4j/arb.expressions.Expression.generate(Expression.java:306)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:291)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:241)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1193)
	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:633)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:88)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:118)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```
