### ISSUE TITLE
expression compiler: multivariate function support via Tuple class

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#284]

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: handle tuples: (n,z)
	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:67)
	at arb4j/arb.expressions.Expression.parseOptionalIndependentVariableSpecification(Expression.java:551)
	at arb4j/arb.expressions.Expression.eatRootNode(Expression.java:536)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:501)
	at arb4j/arb.expressions.Expression.generate(Expression.java:308)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:286)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:236)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1195)
	at arb4j/arb.functions.IntegerToRealPolynomialFunction.express(IntegerToRealPolynomialFunction.java:21)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testA(JacobiPolynomialTest.java:26)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
arb.expressions.UndefinedReferenceException: Undefined reference to variable 'x' in Expression[expression=(n,x)➔(F(n)*x + G)*(C(n)/2 - ½), shortClassName=nxFnTimesxPlusGTimesCnDividedByTwoMinushalf], independent variable is Variable[name=INPUT((n,x))]
	at arb4j/arb.expressions.nodes.Variable.resolveReference(Variable.java:200)
	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:81)
	at arb4j/arb.expressions.Expression.eatFunctionInvocationOrVariableReference(Expression.java:790)
	at arb4j/arb.expressions.Expression.eat(Expression.java:666)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:814)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:1005)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:700)
	at arb4j/arb.expressions.Expression.eat(Expression.java:647)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:814)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:997)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:700)
	at arb4j/arb.expressions.Expression.eatRootNode(Expression.java:536)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:499)
	at arb4j/arb.expressions.Expression.generate(Expression.java:306)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:291)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:241)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1193)
	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:633)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:88)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:118)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: resolve Variable[name=n] via input tuple Variable[name=INPUT((n,x))]
	at arb4j/arb.expressions.nodes.Variable.resolveReference(Variable.java:201)
	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:81)
	at arb4j/arb.expressions.Expression.eatFunctionInvocationOrVariableReference(Expression.java:791)
	at arb4j/arb.expressions.Expression.eat(Expression.java:667)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:815)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:998)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:701)
	at arb4j/arb.expressions.Expression.eatFunctionInvocationOrVariableReference(Expression.java:764)
	at arb4j/arb.expressions.Expression.eat(Expression.java:667)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:815)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:998)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:701)
	at arb4j/arb.expressions.Expression.eat(Expression.java:648)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:815)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:998)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:701)
	at arb4j/arb.expressions.Expression.eatRootNode(Expression.java:537)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:500)
	at arb4j/arb.expressions.Expression.generate(Expression.java:307)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:291)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:241)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1194)
	at arb4j/arb.functions.MultivariateFunction.express(MultivariateFunction.java:75)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:75)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
this is more correct

```java
java.lang.AssertionError: TODO: resolve Variable[name=n] via input tuple Variable[name=INPUT((n,x))] (if its there, otherwise throw an exception)
	at arb4j/arb.expressions.nodes.Variable.resolveReference(Variable.java:201)
	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:81)
	at arb4j/arb.expressions.Expression.eatFunctionInvocationOrVariableReference(Expression.java:791)
	at arb4j/arb.expressions.Expression.eat(Expression.java:667)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:815)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:998)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:701)
	at arb4j/arb.expressions.Expression.eatFunctionInvocationOrVariableReference(Expression.java:764)
	at arb4j/arb.expressions.Expression.eat(Expression.java:667)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:815)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:998)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:701)
	at arb4j/arb.expressions.Expression.eat(Expression.java:648)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:815)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:998)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:701)
	at arb4j/arb.expressions.Expression.eatRootNode(Expression.java:537)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:500)
	at arb4j/arb.expressions.Expression.generate(Expression.java:307)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:291)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:241)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1194)
	at arb4j/arb.functions.MultivariateFunction.express(MultivariateFunction.java:75)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:75)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:123)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: generate code to construct the identity polynomial x->x=[0 1] which corresponds to 0+x and put it on the stack
	at arb4j/arb.expressions.nodes.Variable.generate(Variable.java:133)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:63)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:62)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:62)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:511)
	at arb4j/arb.expressions.Expression.generate(Expression.java:308)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:291)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:241)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1195)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:81)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:121)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: add domainClass() and rangeClass() methods to Function so type checking can be done on the functions
	at arb4j/arb.expressions.Context.registerFunction(Context.java:108)
	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:635)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:74)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:127)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```



commit 1eb51424f303ed6f06b6dd61473edbf8da217ba0
Author: Stephen A. Crowley <crow@outsider.trading> 2023-12-29 02:27:37
Committer: Stephen A. Crowley <crow@outsider.trading> 2023-12-29 02:27:37
Parent: dbdc324614fe3396f4d275759c528b95608dc9c9 (getting closer to implement reordering to use type-specific unary functioons)
Branches: master, origin/HEAD, origin/master

nix multivariate tuple stuff. we dont need it cause (n,x) isnt a
multivatiate function its a function from the interger to the veector
space of coeffecients, not the pointwise evaluation functional
