### ISSUE TITLE
express compiler: compile expressions that produce RealPolynomials as elements of a vector space from integers, the vector space element is a RealPolynomial which can then be regarded as RealFunction (a real valued function of a real-valued scalar)

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#294]
express compiler: compile expressions that produce RealPolynomials as elements of a vector space from integers, the vector space element is a RealPolynomial which can then be regarded as RealFunction (a real valued function of a real-valued scalar)

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: handle placeholder variable when treating the functions elements as members of a vector space  rather than treating it as a real-valued variable to be used in the pointwise evaluation of the polynomial
	at arb4j/arb.expressions.Expression.eatFunctionInvocationOrVariableReference(Expression.java:793)
	at arb4j/arb.expressions.Expression.eat(Expression.java:667)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:819)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:1002)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:701)
	at arb4j/arb.expressions.Expression.eatFunctionInvocationOrVariableReference(Expression.java:764)
	at arb4j/arb.expressions.Expression.eat(Expression.java:667)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:819)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:1002)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:701)
	at arb4j/arb.expressions.Expression.eat(Expression.java:648)
	at arb4j/arb.expressions.Expression.eatLast(Expression.java:819)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:1002)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:701)
	at arb4j/arb.expressions.Expression.eatRootNode(Expression.java:537)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:500)
	at arb4j/arb.expressions.Expression.generate(Expression.java:307)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:291)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:241)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1198)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:81)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:121)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
Your approach to handling polynomials in your arbitrary precision library for Java, which is a SWIG wrapper around ArbLib, seems well-thought-out and technically sound. Let's break down the key points:

1. **Handling Variables**: When a variable is encountered and is not recognized in the existing context, you're treating it as an input variable. This is a standard approach in expression parsing and should work well for most cases.

2. **Dealing with Polynomials**: For generating a function that outputs a polynomial type, you are treating it as a function from integers to a vector space of the coefficients. This is a good abstraction for representing polynomials.

3. **Independent Variable Naming**: In polynomial mathematics, the independent variable is often denoted by 'x', especially in single-variable polynomials. For multivariate polynomials, variables are usually named 'x', 'y', 'z', etc.

4. **Multivariate Case Handling**: Your approach to treat the input type as a tuple for multivariate functions and resolving references is a robust method for handling more complex expressions.

5. **Identity Polynomial as Placeholder**: Your idea to declare a newly instantiated placeholder variable of the real polynomial type and assign it an identity (like ax + b) is a smart way to handle operations on polynomials. Setting b = 0 and a = 1 makes it the identity polynomial, which is a good starting point for transformations.

6. **Code Generation and Evaluation**: Using the identity polynomial as a base for transforming the real polynomial object during code generation seems effective. After the expression is evaluated, returning the resulting polynomial is a logical conclusion to the process.

Overall, your approach to handling expressions, especially polynomial types in your library, appears robust and well-aligned with standard mathematical practices. It should effectively leverage the capabilities of ArbLib while adding the flexibility needed for various mathematical expressions in Java.

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: generate code to construct the identity polynomial x->x=[0 1] which corresponds to 0+x and put it on the stack
	at arb4j/arb.expressions.nodes.Variable.generate(Variable.java:133)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:63)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:62)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:62)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:511)
	at arb4j/arb.expressions.Expression.generate(Expression.java:308)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:291)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:241)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1195)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:81)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:121)


```

**Comment by crowlogic** [comment]
decompiled version of what its producing now.. need to update the declarations of the fields to be their correct type

```java
package arb.functions;

import arb.Integer;
import arb.RealPolynomial;

public abstract class A implements
                        Function<Integer, RealPolynomial>
{
  public Integer      c0 = new Integer("1",
                                       128);
  public Integer      c1 = new Integer("2",
                                       128);
  public Integer      G;
  public Integer      x;
  public Integer      l0;
  public Integer      l1;
  public Integer      l2;
  public Integer      l3;
  public Integer      l4;
  public RealFunction C;
  public RealFunction F;

  public RealPolynomial evaluate(Integer in, int order, int bits, RealPolynomial result)
  {
    return F.evaluate(in, order, bits, result)
            .mul(result, bits, l0)
            .add(G, bits, l1)
            .mul(C.evaluate(in, order, bits, l2).sub(c0, bits, l3), bits, l4)
            .div(c1, bits, result);
  }

  public A() {
    l0 = new RealPolynomial();
    l1 = new RealPolynomial();
    l2 = new RealPolynomial();
    l3 = new RealPolynomial();
    l4 = new RealPolynomial();
    C = null;
    F = null;
  }

  public void close()
  {
    c0.close();
    c1.close();
    l0.close();
    l1.close();
    l2.close();
    l3.close();
    l4.close();
  }
}
```

**Comment by crowlogic** [comment]
TOOD: refactor this in Compiler.java, it needs the types passed in with it rather than declaring all the intermediate variables as the domain type as is presently done


```java
  /**
   * Declares the given variables as fields in the class being generated.
   * 
   * TODO: needs to be refactored so that the variable type is passed in
   * 
   * @param classVisitor The {@link ClassVisitor} for the class being generated
   * @param variables    A {@link Collection} of variable names to be declared as
   *                     fields
   * @return classVisitor
   */
  public static <D, R, F extends Function<D, R>> ClassVisitor declareVariables(Expression<D, R, F> expression,
                                                                               ClassVisitor classVisitor,
                                                                               Iterable<String> variables)
  {
    for (var variableName : variables)
    {
      classVisitor.visitField(ACC_PUBLIC, variableName, expression.domainClassDescriptor, null, null);
    }
    return classVisitor;
  }
```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: Todo: add type of intermediate variable to locateExistingOrInstantiateNewIntermediateResultVariable
	at arb4j/arb.expressions.Expression.locateExistingOrInstantiateNewIntermediateResultVariable(Expression.java:1159)
	at arb4j/arb.expressions.nodes.BinaryOperation.invokeMethod(BinaryOperation.java:101)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:64)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:62)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:62)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:511)
	at arb4j/arb.expressions.Expression.generate(Expression.java:308)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:287)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:237)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1201)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:75)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:128)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: generate code to call the identity function on the polynomial result which has been loaded onto the stack
	at arb4j/arb.expressions.nodes.Variable.generate(Variable.java:130)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:65)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:64)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:64)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:64)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:542)
	at arb4j/arb.expressions.Expression.generate(Expression.java:309)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:149)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:99)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1228)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:78)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:127)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: generate code to call the identity function on the polynomial result which has been loaded onto the stack
	at arb4j/arb.expressions.nodes.Variable.generate(Variable.java:130)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:65)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:64)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:64)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:64)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:542)
	at arb4j/arb.expressions.Expression.generate(Expression.java:309)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:149)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:99)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1228)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:78)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:126)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    nFnTimesxPlusGTimesCnMinusOneDividedByTwo.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @78: invokevirtual
  Reason:
    Type 'arb/Integer' (current frame, stack[2]) is not assignable to 'arb/Real'
  Current Frame:
    bci: @78
    flags: { }
    locals: { 'nFnTimesxPlusGTimesCnMinusOneDividedByTwo', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial', 'arb/RealPolynomial', 'arb/Integer', integer, 'arb/RealPolynomial' }
  Bytecode:
    0000000: 2ab4 000d 2bc0 000f 1c1d 1904 c000 11b6
    0000010: 0015 c000 1119 04c0 0011 b600 191d 2ab4
    0000020: 001d b600 212a b400 251d 2ab4 0028 b600
    0000030: 2c2a b400 302b c000 0f1c 1d2a b400 33b6
    0000040: 0036 c000 112a b400 3a1d 2ab4 003d b600
    0000050: 401d 2ab4 0043 b600 462a b400 491d 1904
    0000060: c000 11b6 004c b0                      

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:208)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1241)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:81)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:128)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: FunctionCall[name=C, contextual=true, function=Mapping[name=C, func=TwoTimesnPlusαPlusβ@6107227e, domain=arb.Real, range=arb.Real], arg=BinaryOperation[left=Variable[reference=INPUT(Reference[name=n, index=null, type=arb.Integer]), type=arb.Integer], right=LiteralConstant[fieldName=c0, value=1, depth=0, type=arb.Integer], operation=sub, castResult=false, generatedType=class arb.Real], targetResultType=arb.Real]: arg.type = arb.Integer ≠ function.domain = arb.Real
	at arb4j/arb.expressions.nodes.unary.FunctionCall.generateContextualFunctionCall(FunctionCall.java:240)
	at arb4j/arb.expressions.nodes.unary.FunctionCall.generate(FunctionCall.java:78)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:113)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:512)
	at arb4j/arb.expressions.Expression.generate(Expression.java:311)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:136)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:86)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1175)
	at arb4j/arb.functions.Function.express(Function.java:124)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:80)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testB(JacobiPolynomialTest.java:70)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: type conversion expression.domainType = class arb.Integer != resultType = class arb.Real

	at arb4j/arb.expressions.nodes.Variable.generate(Variable.java:134)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:98)
	at arb4j/arb.expressions.nodes.unary.FunctionCall.generateContextualFunctionCall(FunctionCall.java:153)
	at arb4j/arb.expressions.nodes.unary.FunctionCall.generate(FunctionCall.java:72)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:98)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:512)
	at arb4j/arb.expressions.Expression.generate(Expression.java:311)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:136)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:86)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1153)
	at arb4j/arb.functions.Function.express(Function.java:124)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:80)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testB(JacobiPolynomialTest.java:70)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.NoSuchMethodError: 'arb.RealPolynomial arb.RealPolynomial.div(arb.Integer, int, arb.RealPolynomial)'
	at nFnTimesxPlusGTimesCnMinusOneDividedByTwo.evaluate(Unknown Source)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testA(JacobiPolynomialTest.java:36)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
another one bites the dust
