### ISSUE TITLE
expression compiler: add type to registerBuiltinFunction and use [functionName,domain] as the key instead of just functionName

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#296]
TODO: add Class<?> type to Node to support mixed-types of variables in expressions and then use that when calling reserveIntermediateVariable

**Comment by crowlogic** [comment]
mostly done.. now use it to fix 

```java
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    nTwoTimesnPlusαPlusβ.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @14: invokevirtual
  Reason:
    Type 'arb/Integer' (current frame, stack[1]) is not assignable to 'arb/Real'
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'nTwoTimesnPlusαPlusβ', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/Integer', 'arb/Integer', integer, 'arb/Real' }
  Bytecode:
    0000000: 2ab4 000d 2bc0 000f 1d19 04c0 0011 b600
    0000010: 152a b400 191d 2ab4 001c b600 1f2a b400
    0000020: 221d 1904 c000 0fb6 001f b0            

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:208)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1218)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:75)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testA(JacobiPolynomialTest.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
the builtin functions need to have a type created that specifies their names and their domain and range classes 


```java
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    nTwoTimesnPlusαPlusβ.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @14: invokevirtual
  Reason:
    Type 'arb/Integer' (current frame, stack[1]) is not assignable to 'arb/Real'
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'nTwoTimesnPlusαPlusβ', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/Integer', 'arb/Integer', integer, 'arb/Real' }
  Bytecode:
    0000000: 2ab4 000d 2bc0 000f 1d19 04c0 0011 b600
    0000010: 152a b400 191d 2ab4 001c b600 1f2a b400
    0000020: 221d 1904 c000 0fb6 001f b0            

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:208)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1218)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:75)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:128)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
line 14 is calling the wrong version of the mul method, hence its complaining that it cant put a Real where an Integer belongs

```java
//  (version 21 : 65.65535, no super bit)
public class nTwoTimesnPlusαPlusβ implements arb.functions.Function {
  
  // Field descriptor #11 Larb/Integer;
  public arb.Integer c0;
  
  // Field descriptor #11 Larb/Integer;
  public arb.Integer α;
  
  // Field descriptor #11 Larb/Integer;
  public arb.Integer β;
  
  // Field descriptor #23 Larb/Real;
  public arb.Real l0;
  
  // Method descriptor #8 (Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object;
  // Signature: (Larb/Integer;IILarb/Real;)Larb/Real;
  // Stack: 4, Locals: 5
  public java.lang.Object evaluate(java.lang.Object in, int order, int bits, java.lang.Object result);
     0  aload_0 [this]
     1  getfield nTwoTimesnPlusαPlusβ.c0 : arb.Integer [13]
     4  aload_1 [in]
     5  checkcast arb.Integer [15]
     8  iload_3 [bits]
     9  aload 4 [result]
    11  checkcast arb.Real [17]
    14  invokevirtual arb.Real.mul(arb.Real, int, arb.Real) : arb.Real [21]
    17  aload_0 [this]
    18  getfield nTwoTimesnPlusαPlusβ.α : arb.Real [25]
    21  iload_3 [bits]
    22  aload_0 [this]
    23  getfield nTwoTimesnPlusαPlusβ.l0 : arb.Real [28]
    26  invokevirtual arb.Real.add(arb.Real, int, arb.Real) : arb.Real [31]
    29  aload_0 [this]
    30  getfield nTwoTimesnPlusαPlusβ.β : arb.Real [34]
    33  iload_3 [bits]
    34  aload 4 [result]
    36  checkcast arb.Integer [15]
    39  invokevirtual arb.Real.add(arb.Real, int, arb.Real) : arb.Real [31]
    42  areturn
      Local variable table:
        [pc: 0, pc: 43] local: in index: 1 type: java.lang.Object
        [pc: 0, pc: 43] local: order index: 2 type: int
        [pc: 0, pc: 43] local: bits index: 3 type: int
        [pc: 0, pc: 43] local: result index: 4 type: java.lang.Object
      Local variable type table:
        [pc: 0, pc: 43] local: in index: 1 type: arb.Integer
        [pc: 0, pc: 43] local: result index: 4 type: arb.Real
  
  // Method descriptor #42 ()V
  // Stack: 5, Locals: 1
  public nTwoTimesnPlusαPlusβ();
     0  aload_0 [this]
     1  invokespecial java.lang.Object() [44]
     4  aload_0 [this]
     5  new arb.Integer [15]
     8  dup
     9  ldc <String "2"> [46]
    11  sipush 128
    14  invokespecial arb.Integer(java.lang.String, int) [49]
    17  putfield nTwoTimesnPlusαPlusβ.c0 : arb.Integer [13]
    20  aload_0 [this]
    21  new arb.Real [17]
    24  dup
    25  invokespecial arb.Real() [50]
    28  putfield nTwoTimesnPlusαPlusβ.l0 : arb.Real [28]
    31  return

  
  // Method descriptor #42 ()V
  // Stack: 1, Locals: 1
  public void close();
     0  aload_0 [this]
     1  getfield nTwoTimesnPlusαPlusβ.c0 : arb.Integer [13]
     4  invokevirtual arb.Integer.close() : void [53]
     7  aload_0 [this]
     8  getfield nTwoTimesnPlusαPlusβ.l0 : arb.Integer [55]
    11  invokevirtual arb.Integer.close() : void [53]
    14  return

}
```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: todo: determine result type, left=LiteralConstant[fieldName=c0, value=2, depth=0, type=class arb.Integer] right=Variable[name=INPUT(n), type=class arb.Real]
	at arb4j/arb.expressions.nodes.BinaryOperation.determineResultType(BinaryOperation.java:71)
	at arb4j/arb.expressions.nodes.BinaryOperation.<init>(BinaryOperation.java:60)
	at arb4j/arb.expressions.nodes.Multiply.<init>(Multiply.java:23)
	at arb4j/arb.expressions.Expression.eatSecond(Expression.java:1006)
	at arb4j/arb.expressions.Expression.eatFirst(Expression.java:703)
	at arb4j/arb.expressions.Expression.eatRootNode(Expression.java:539)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:502)
	at arb4j/arb.expressions.Expression.generate(Expression.java:309)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:147)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:97)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1192)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:73)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP1(JacobiPolynomialTest.java:127)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: add domainClass() and rangeClass() methods to Function so type checking can be done on the functions
	at arb4j/arb.expressions.Context.registerFunction(Context.java:108)
	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:635)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:74)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testE(JacobiPolynomialTest.java:47)

```

**Comment by crowlogic** [comment]
```java
@Override
public MethodVisitor generate(MethodVisitor mv) {
    // ... existing code ...

    if (isIndeterminant) {
        // Assuming the polynomial result is already on the stack
        // Call the identity function
        mv.visitMethodInsn(INVOKEVIRTUAL, 
                           "YourClassContainingIdentityFunction", // Replace with the actual class name
                           "identityFunction", // Replace with the actual method name
                           "(TypeOfPolynomialResult)Ljava/lang/Object;", // Replace with the actual method descriptor
                           false);

        // Handle the result of the identity function
        // For example, store it back to a variable or leave it on the stack
    }

    // ... existing code ...

    return mv;
}
```

**Comment by crowlogic** [comment]
The Mapping class contains the function its name it's type of domain and its type of range
