### ISSUE TITLE
expression compiler: type conversion

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#298]
Integer->Real
and 
Real->RealPolynomial

**Comment by crowlogic** [comment]
nevermind no need

**Comment by crowlogic** [comment]
```java
arb.expressions.ExpressionCompilerException: "todo: allocate intermediate variable of type class arb.Real and call its set(class arb.Integer) function before it gets passed on to the C function
	at arb4j/arb.expressions.nodes.FunctionCall.generateContextualFunctionCall(FunctionCall.java:168)
	at arb4j/arb.expressions.nodes.FunctionCall.generate(FunctionCall.java:57)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:66)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:556)
	at arb4j/arb.expressions.Expression.generate(Expression.java:320)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:96)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1244)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:80)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testC(JacobiPolynomialTest.java:84)
```

**Comment by crowlogic** [comment]
```java
arb.expressions.ExpressionCompilerException: todo: call C(((class arb.Real)l1).set(class arb.Integer))
	at arb4j/arb.expressions.nodes.FunctionCall.generateContextualFunctionCall(FunctionCall.java:170)
	at arb4j/arb.expressions.nodes.FunctionCall.generate(FunctionCall.java:57)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:66)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:556)
	at arb4j/arb.expressions.Expression.generate(Expression.java:320)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:96)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1244)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:80)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testC(JacobiPolynomialTest.java:84)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: FIXME: stopping point, do type-casting here, left.type=class arb.Integer != type=class arb.Real

	at arb4j/arb.expressions.nodes.BinaryOperation.invokeMethod(BinaryOperation.java:112)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:69)
	at arb4j/arb.expressions.nodes.FunctionCall.generateContextualFunctionCall(FunctionCall.java:192)
	at arb4j/arb.expressions.nodes.FunctionCall.generate(FunctionCall.java:59)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:66)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:559)
	at arb4j/arb.expressions.Expression.generate(Expression.java:320)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:96)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1246)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:80)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testC(JacobiPolynomialTest.java:84)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: FIXME: stopping point at 'n - 1', do type-casting here, left.type=class arb.Integer != type=class arb.Real

	at arb4j/arb.expressions.nodes.BinaryOperation.invokeMethod(BinaryOperation.java:112)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:69)
	at arb4j/arb.expressions.nodes.FunctionCall.generateContextualFunctionCall(FunctionCall.java:192)
	at arb4j/arb.expressions.nodes.FunctionCall.generate(FunctionCall.java:59)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:66)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:559)
	at arb4j/arb.expressions.Expression.generate(Expression.java:320)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:96)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1246)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:80)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testC(JacobiPolynomialTest.java:84)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: type conversion from class arb.Integer to class arb.Real for result of binary operation
	at arb4j/arb.expressions.nodes.BinaryOperation.invokeMethod(BinaryOperation.java:92)
	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:68)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:529)
	at arb4j/arb.expressions.Expression.generate(Expression.java:317)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:121)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:71)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1211)
	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:642)
	at arb4j/arb.expressions.ExpressionCompilerRealFunctionTest.testOnePlusTwoPlusThree(ExpressionCompilerRealFunctionTest.java:431)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
thgis is what the generated decompiled  code should be like in the case where the result is not the same type as the last node in the expression

```java
package arb.functions;

import arb.Integer;
import arb.Real;
import arb.RealPolynomial;


public abstract class A implements
                        Function<Integer, RealPolynomial>
{
  public Integer c0 = new Integer("42");
  public Integer c1 = new Integer("6");
  public Integer l0 = new Integer();

  public Real evaluate(Real in, int order, int bits, Real result)
  {
    return result.set(c0.div(this.c1, bits, this.l0));
  }

  public void close()
  {
    this.c0.close();
    this.c1.close();
    this.l0.close();
  }
}```

**Comment by crowlogic** [comment]
the corresponding bytecode is

```java
public abstract class arb.functions.A implements arb.functions.Function<arb.Integer, arb.RealPolynomial> {
  public arb.Integer c0;

  public arb.Integer c1;

  public arb.Integer l0;

  public arb.functions.A();
    Code:
       0: aload_0
       1: invokespecial #14                 // Method java/lang/Object."<init>":()V
       4: aload_0
       5: new           #16                 // class arb/Integer
       8: dup
       9: ldc           #18                 // String 42
      11: invokespecial #20                 // Method arb/Integer."<init>":(Ljava/lang/String;)V
      14: putfield      #23                 // Field c0:Larb/Integer;
      17: aload_0
      18: new           #16                 // class arb/Integer
      21: dup
      22: ldc           #25                 // String 6
      24: invokespecial #20                 // Method arb/Integer."<init>":(Ljava/lang/String;)V
      27: putfield      #27                 // Field c1:Larb/Integer;
      30: aload_0
      31: new           #16                 // class arb/Integer
      34: dup
      35: invokespecial #29                 // Method arb/Integer."<init>":()V
      38: putfield      #30                 // Field l0:Larb/Integer;
      41: return

  public arb.Real evaluate(arb.Real, int, int, arb.Real);
    Code:
       0: aload         4
       2: aload_0
       3: getfield      #23                 // Field c0:Larb/Integer;
       6: aload_0
       7: getfield      #27                 // Field c1:Larb/Integer;
      10: iload_3
      11: aload_0
      12: getfield      #30                 // Field l0:Larb/Integer;
      15: invokevirtual #38                 // Method arb/Integer.div:(Larb/Integer;ILarb/Integer;)Larb/Integer;
      18: invokevirtual #42                 // Method arb/Real.set:(Larb/Integer;)Larb/Real;
      21: areturn

  public void close();
    Code:
       0: aload_0
       1: getfield      #23                 // Field c0:Larb/Integer;
       4: invokevirtual #55                 // Method arb/Integer.close:()V
       7: aload_0
       8: getfield      #27                 // Field c1:Larb/Integer;
      11: invokevirtual #55                 // Method arb/Integer.close:()V
      14: aload_0
      15: getfield      #30                 // Field l0:Larb/Integer;
      18: invokevirtual #55                 // Method arb/Integer.close:()V
      21: return
}
```

**Comment by crowlogic** [comment]
Yes, your approach for handling type conversion and binary operations in JVM instruction generation seems sound. To summarize and clarify:

1. **Load Target Type Result**: Initially, load the result of the target type onto the stack. This ensures that the subsequent operations work with the correct type.

2. **Push Operands**: Push the left and right operands onto the stack. These are the values that will be involved in the binary operation (add, subtract, multiply, divide, etc.).

3. **Invoke Operation Method**: Perform the binary operation. This method will consume the operands from the stack and perform the specified operation.

4. **Emit Result on Stack**: The result of the operation, which should be of the source class type, is then placed on the stack.

5. **Invoke `set` Method**: Finally, invoke a virtual method named `set`. This method seems to be designed to handle the result on the stack and possibly perform additional operations or state changes. When `set` is called, it returns `this`, which refers to the object of the target type.

This process effectively handles type conversions and binary operations while maintaining stack consistency and type safety in the JVM environment. Your description indicates a well-thought-out process for JVM bytecode generation or similar tasks.

**Comment by crowlogic** [comment]
correct

```java
package arb.functions;

import arb.Integer;
import arb.Real;
import arb.functions.real.RealFunction;

public class OnePlusTwoPlusThree implements
                                 RealFunction
{
  public Integer c0 = new Integer("1");
  public Integer c1 = new Integer("2");
  public Integer c2 = new Integer("3");
  public Integer l0 = new Integer();
  public Integer l1 = new Integer();

  public Real evaluate(Real in, int order, int bits, Real result)
  {
    return result.set(c0.add(c1, bits, l0).add(c2, bits, l1));
  }

  public void close()
  {
    this.c0.close();
    this.c1.close();
    this.c2.close();
    this.l0.close();
  }
}
```


currently generating


```java
import arb.Integer;
import arb.Real;
import arb.functions.real.RealFunction;

public class OnePlusTwoPlusThree implements RealFunction {
	public Integer c0 = new Integer("1");
	public Integer c1 = new Integer("2");
	public Integer c2 = new Integer("3");
	public Integer l0 = new Integer();

	public Real evaluate(Real in, int order, int bits, Real result) {
		return this.c0.add(this.c1, bits, this.l0).add(this.c2, bits, (Integer) result);
	}

	public void close() {
		this.c0.close();
		this.c1.close();
		this.c2.close();
		this.l0.close();
	}
}
```
