### ISSUE TITLE
expression compiler: add when operator that operates like case/switch/when/if/piecewise

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#301]
/**
   * TODO: when function, when(n=0,1,n=1,p1(z),otherwise,(A(n) * z *
P(n-1) - B(n) * P(n-2)) / 2)
   */

**Comment by crowlogic** [comment]
```java
java.lang.RuntimeException: expected closing paranthesis at: startPos=2, position=8, identifier='Reference[name=when, index=null, type=null]', isFunction=true, depth=0
, expression=n➔when(n=0,1,n=1,(C(1)*x-β+α)/2,else,(A(n)*P(n-1)-B(n)*P(n-2))/E(n))

	at arb4j/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:848)
	at arb4j/arb.expressions.Expression.parse(Expression.java:742)
	at arb4j/arb.expressions.Expression.parseLast(Expression.java:893)
	at arb4j/arb.expressions.Expression.parseSecond(Expression.java:1076)
	at arb4j/arb.expressions.Expression.parseFirst(Expression.java:776)
	at arb4j/arb.expressions.Expression.parseRootNode(Expression.java:589)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:549)
	at arb4j/arb.expressions.Expression.generate(Expression.java:348)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:118)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:82)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1218)
	at arb4j/arb.functions.Function.express(Function.java:129)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:104)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testA(JacobiPolynomialTest.java:32)
```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: todo: parse when function n➔when(n=0,1,n=1,(C(1)*x-β+α)/2,else,(A(n)*P(n-1)-B(n)*P(n-2))/E(n))
	at arb4j/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:840)
	at arb4j/arb.expressions.Expression.parse(Expression.java:742)
	at arb4j/arb.expressions.Expression.parseLast(Expression.java:901)
	at arb4j/arb.expressions.Expression.parseSecond(Expression.java:1084)
	at arb4j/arb.expressions.Expression.parseFirst(Expression.java:776)
	at arb4j/arb.expressions.Expression.parseRootNode(Expression.java:589)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:549)
	at arb4j/arb.expressions.Expression.generate(Expression.java:348)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:118)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:82)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1226)
	at arb4j/arb.functions.Function.express(Function.java:129)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:104)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testA(JacobiPolynomialTest.java:32)
	at ```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: make a When class that extends Node and contains cases={0=LiteralConstant[fieldName=c1, value=1, depth=0, type=arb.Integer], 1=BinaryOperation[left={C(1)} \cdot {x} - β + α, right=2, operation=div, generatedType=null]} defaultValue=BinaryOperation[left={A(n)} \cdot {P(n - 1)} - {B(n)} \cdot {P(n - 2)}, right=E(n), operation=div, generatedType=null]
	at arb4j/arb.expressions.Expression.parseWhen(Expression.java:1005)
	at arb4j/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:1037)
	at arb4j/arb.expressions.Expression.parse(Expression.java:669)
	at arb4j/arb.expressions.Expression.parseThird(Expression.java:766)
	at arb4j/arb.expressions.Expression.parseSecond(Expression.java:885)
	at arb4j/arb.expressions.Expression.parseFirst(Expression.java:721)
	at arb4j/arb.expressions.Expression.parseRootNode(Expression.java:871)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:452)
	at arb4j/arb.expressions.Expression.generate(Expression.java:350)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:119)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:91)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:90)
	at arb4j/arb.functions.Function.express(Function.java:129)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:104)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testA(JacobiPolynomialTest.java:32)
	

```

**Comment by crowlogic** [comment]
```java
case 0 -> LiteralConstant[fieldName=c1, value=1, depth=0, type=arb.Integer]
case 1 -> BinaryOperation[left={C(1)} \cdot {x} - β + α, right=2, operation=div, generatedType=null]
default -> BinaryOperation[left={A(n)} \cdot {P(n - 1)} - {B(n)} \cdot {P(n - 2)}, right=E(n), operation=div, generatedType=null]
```
