### ISSUE TITLE
implement (terminating) polynomial case of hypergeometric function as a ratio of finite products of rising factorials: n➔when(n=0,1,else,x*F(n-1)*(∏α₍ₖ₎(k=1..p)/∏β₍ₖ₎(k=1..q))

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#308]

**Comment by crowlogic** [comment]
'n➔when(n=0,1,else,x*F(n-1)*(∏αₖ(k=1..p)/∏βₖ(k=1..q))'

```java
Exception in thread "main" arb.exceptions.ExpressionCompilerException: expected closing parenthesis at: depth=2 startPos=27, position=28 in expression 'n➔when(n=0,1,else,x*F(n-1)*(∏αₖ(k=1..p)/∏βₖ(k=1..q))' of length 52
	at arb4j/arb.expressions.Expression.parse(Expression.java:695)
	at arb4j/arb.expressions.Expression.parseFinally(Expression.java:773)
	at arb4j/arb.expressions.Expression.parseMultiplicationAndDivisionOperations(Expression.java:884)
	at arb4j/arb.expressions.Expression.parseSecond(Expression.java:873)
	at arb4j/arb.expressions.Expression.parseFirst(Expression.java:734)
	at arb4j/arb.expressions.nodes.unary.When.parseWhenCondition(When.java:186)
	at arb4j/arb.expressions.nodes.unary.When.parse(When.java:146)
	at arb4j/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:948)
	at arb4j/arb.expressions.Expression.parse(Expression.java:707)
	at arb4j/arb.expressions.Expression.parseFinally(Expression.java:773)
	at arb4j/arb.expressions.Expression.parseSecond(Expression.java:871)
	at arb4j/arb.expressions.Expression.parseFirst(Expression.java:734)
	at arb4j/arb.expressions.Expression.parseRootNode(Expression.java:863)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:457)
	at arb4j/arb.expressions.Expression.generate(Expression.java:362)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:118)
	at arb4j/arb.functions.Function.express(Function.java:145)
	at arb4j/arb.functions.real.HypergeometricFunctionSequence.<init>(HypergeometricFunctionSequence.java:47)
	at arb4j/arb.functions.real.HypergeometricFunctionSequence.main(HypergeometricFunctionSequence.java:20)
```

**Comment by crowlogic** [comment]
a_n denotes an indexed variable a[n], it has to be within a parenthesis to be a rising factorial: 'n➔when(n=0,1,else,x*F(n-1)*(∏α₍ₖ₎(k=1..p)/∏β₍ₖ₎(k=1..q))' .. will have to come up with alternative syntax for when whatever the power is cant be expressed as a set of utf subscript chars.. that would be kind of ridiculous to figure out how to express something like that anyway

**Comment by crowlogic** [comment]
```java
Exception in thread "main" arb.exceptions.ExpressionCompilerException: expected closing parenthesis, instead got ∏ at position 27 in expression 'n➔when(n=0,1,else,x*F(n-1)*(∏α₍ₖ₎{k=1…p}/∏β₍ₖ₎{k=1…q}))'
	at arb4j/arb.expressions.Expression.parse(Expression.java:695)
	at arb4j/arb.expressions.Expression.parseFinally(Expression.java:773)
	at arb4j/arb.expressions.Expression.parseMultiplicationAndDivisionOperations(Expression.java:884)
	at arb4j/arb.expressions.Expression.parseSecond(Expression.java:873)
	at arb4j/arb.expressions.Expression.parseFirst(Expression.java:734)
	at arb4j/arb.expressions.nodes.unary.When.parseWhenCondition(When.java:186)
	at arb4j/arb.expressions.nodes.unary.When.parse(When.java:146)
	at arb4j/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:948)
	at arb4j/arb.expressions.Expression.parse(Expression.java:707)
	at arb4j/arb.expressions.Expression.parseFinally(Expression.java:773)
	at arb4j/arb.expressions.Expression.parseSecond(Expression.java:871)
	at arb4j/arb.expressions.Expression.parseFirst(Expression.java:734)
	at arb4j/arb.expressions.Expression.parseRootNode(Expression.java:863)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:457)
	at arb4j/arb.expressions.Expression.generate(Expression.java:362)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:118)
	at arb4j/arb.functions.Function.express(Function.java:145)
	at arb4j/arb.functions.real.HypergeometricFunctionSequence.<init>(HypergeometricFunctionSequence.java:47)
	at arb4j/arb.functions.real.HypergeometricFunctionSequence.main(HypergeometricFunctionSequence.java:20)
```

**Comment by crowlogic** [comment]
```java
arb.exceptions.ExpressionCompilerException: expected closing parenthesis, instead got ∏ at position 27 in expression 'n➔when(n=0,1,else,x*F(n-1)*(∏α₍ₖ₎{k=1…p}/∏β₍ₖ₎{k=1…q}))'
	at arb4j/arb.expressions.Expression.parse(Expression.java:695)
	at arb4j/arb.expressions.Expression.parseFinally(Expression.java:773)
	at arb4j/arb.expressions.Expression.parseMultiplicationAndDivisionOperations(Expression.java:884)
	at arb4j/arb.expressions.Expression.parseSecond(Expression.java:873)
	at arb4j/arb.expressions.Expression.parseFirst(Expression.java:734)
	at arb4j/arb.expressions.nodes.unary.When.parseWhenCondition(When.java:186)
	at arb4j/arb.expressions.nodes.unary.When.parse(When.java:146)
	at arb4j/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:948)
	at arb4j/arb.expressions.Expression.parse(Expression.java:707)
	at arb4j/arb.expressions.Expression.parseFinally(Expression.java:773)
	at arb4j/arb.expressions.Expression.parseSecond(Expression.java:871)
	at arb4j/arb.expressions.Expression.parseFirst(Expression.java:734)
	at arb4j/arb.expressions.Expression.parseRootNode(Expression.java:863)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:457)
	at arb4j/arb.expressions.Expression.generate(Expression.java:362)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:118)
	at arb4j/arb.functions.Function.express(Function.java:145)
	at arb4j/arb.functions.real.HypergeometricFunctionSequence.<init>(HypergeometricFunctionSequence.java:47)
	at arb4j/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: create Product node and return  it here
	at arb4j/arb.expressions.Expression.multiplyAndDivide(Expression.java:899)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:875)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivideAddAndSubtract(Expression.java:735)
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:692)
	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:774)
	at arb4j/arb.expressions.Expression.multiplyAndDivide(Expression.java:886)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:875)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivideAddAndSubtract(Expression.java:735)
	at arb4j/arb.expressions.nodes.unary.When.evaluateDefaultValue(When.java:237)
	at arb4j/arb.expressions.nodes.unary.When.evaluateValue(When.java:182)
	at arb4j/arb.expressions.nodes.unary.When.evaluate(When.java:146)
	at arb4j/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:954)
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:708)
	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:774)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:873)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivideAddAndSubtract(Expression.java:735)
	at arb4j/arb.expressions.Expression.evaluateRootNode(Expression.java:864)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:457)
	at arb4j/arb.expressions.Expression.generate(Expression.java:362)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:118)
	at arb4j/arb.functions.Function.express(Function.java:145)
	at arb4j/arb.functions.real.HypergeometricFunctionSequence.<init>(HypergeometricFunctionSequence.java:47)
	at arb4j/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
```

**Comment by crowlogic** [comment]
duplicate of https://github.com/crowlogic/arb4j/issues/308
