### ISSUE TITLE
expression compiler: implement product

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#310]
```java
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import static org.objectweb.asm.Opcodes.*;

public class FluentLoopWithRealAndIncrement {

    public static byte[] generateFluentLoopWithRealAndIncrement() {
        ClassWriter classWriter = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        MethodVisitor mv;

        // Define a method that takes a Real instance as an argument, modifies it in a loop, and returns it
        mv = classWriter.visitMethod(ACC_PUBLIC, "calculateProductFluently", "(Larb/Real;)Larb/Real;", null, null);
        mv.visitCode();

        // Initialize or reset the Real instance to one at the beginning of the method
        mv.visitVarInsn(ALOAD, 1); // Load the Real instance argument onto the stack
        mv.visitMethodInsn(INVOKEVIRTUAL, "arb/Real", "one", "()Larb/Real;", false); 

        // Define the start of the loop
        Label loopStart = new Label();
        Label afterLoop = new Label();
        mv.visitLabel(loopStart);

        // Assuming 'index' and 'endIndex' comparison logic here
        // For demonstration, let's assume 'index' is a field of type YourMutableIntegerClass and we're comparing it to 'endIndex'
        getField(mv, "YourClass", "index", "LYourMutableIntegerClass;"); // Load 'index'
        getField(mv, "YourClass", "endIndex", "LYourMutableIntegerClass;"); // Load 'endIndex'
        mv.visitMethodInsn(INVOKEVIRTUAL, "YourMutableIntegerClass", "compareTo", "(LYourMutableIntegerClass;)I", false);
        mv.visitJumpInsn(IFGE, afterLoop); // If 'index' >= 'endIndex', jump to the end of the loop

        // Apply the 'factor' function to the Real instance, using the current 'index'
        // This assumes 'factor' is a method in 'YourClass' that operates on 'Real'
        mv.visitVarInsn(ALOAD, 0); // Load 'this'
        mv.visitVarInsn(ALOAD, 1); // Load the 'Real' instance
        getField(mv, "YourClass", "index", "LYourMutableIntegerClass;"); // Load 'index'
        mv.visitMethodInsn(INVOKEVIRTUAL, "YourClass", "factor", "(Larb/Real;LYourMutableIntegerClass;)Larb/Real;", false);
        mv.visitVarInsn(ASTORE, 1); // Store the result back into the 'Real' instance variable

        // Increment 'index'
        getField(mv, "YourClass", "index", "LYourMutableIntegerClass;"); // Load 'index'
        mv.visitMethodInsn(INVOKEVIRTUAL, "YourMutableIntegerClass", "increment", "()V", false);

        // Jump back to the start of the loop
        mv.visitJumpInsn(GOTO, loopStart);
        mv.visitLabel(afterLoop);

        // Return the modified Real instance
        mv.visitVarInsn(ALOAD, 1);
        mv.visitInsn(ARETURN);

        mv.visitMaxs(4, 2); // Automatically compute the maximum stack size and the number of local variables
        mv.visitEnd();

        return classWriter.toByteArray();
    }

    private static void getField(MethodVisitor mv, String owner, String name, String descriptor) {
        mv.visitVarInsn(ALOAD, 0); // Load 'this'
        mv.visitFieldInsn(GETFIELD, owner, name, descriptor);
    }
}```

**Comment by crowlogic** [comment]
```java

arb.exceptions.ExpressionCompilerException: expected closing parenthesis, instead got ₍ at position 28 in expression 'n➔when(n=0,1,else,x*F(n-1)/((∏αₖ₌₁…ₚ₍ₙ₋₁₎)/(∏βₖ₌₁…q₍ₙ₋₁₎)))'
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:701)
	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:787)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:898)
	at arb4j/arb.expressions.Expression.reckon(Expression.java:751)
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:697)
	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:787)
	at arb4j/arb.expressions.Expression.multiplyAndDivide(Expression.java:918)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:900)
	at arb4j/arb.expressions.Expression.reckon(Expression.java:751)
	at arb4j/arb.expressions.nodes.unary.When.evaluateDefaultValue(When.java:211)
	at arb4j/arb.expressions.nodes.unary.When.evaluateValue(When.java:151)
	at arb4j/arb.expressions.nodes.unary.When.<init>(When.java:117)
	at arb4j/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:974)
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:713)
	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:787)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:898)
	at arb4j/arb.expressions.Expression.reckon(Expression.java:751)
	at arb4j/arb.expressions.Expression.evaluateRootNode(Expression.java:889)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:462)
	at arb4j/arb.expressions.Expression.generate(Expression.java:367)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:123)
	at arb4j/arb.functions.Function.express(Function.java:145)
	at arb4j/arb.functions.real.HypergeometricFunctionSequence.<init>(HypergeometricFunctionSequence.java:61)
	at arb4j/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by crowlogic** [comment]
```java
java.lang.NoSuchMethodError: 'arb.Real arb.Integer.risingFactorial(arb.Integer, int, arb.Real)'
	at x₍₃₎.evaluate(Unknown Source)
	at arb4j/arb.expressions.ExpressionTest.testRisingFactorial(ExpressionTest.java:17)
```

**Comment by crowlogic** [comment]
```java
arb.exceptions.ExpressionCompilerException: expected closing parenthesis, instead got { at position 28 in expression 'n➔when(n=0,1,else,x*F(n-1)/((∏αₖ₍ₙ₋₁₎{k=1…p})/(∏βₖ₍ₙ₋₁₎{k=1…q})))' but got { at pos 37
	at arb4j@0.85/arb.expressions.Expression.evaluate(Expression.java:705)
	at arb4j@0.85/arb.expressions.Expression.exponentiate(Expression.java:801)
	at arb4j@0.85/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:919)
	at arb4j@0.85/arb.expressions.Expression.determine(Expression.java:750)
	at arb4j@0.85/arb.expressions.Expression.evaluate(Expression.java:701)
	at arb4j@0.85/arb.expressions.Expression.exponentiate(Expression.java:801)
	at arb4j@0.85/arb.expressions.Expression.multiplyAndDivide(Expression.java:941)
	at arb4j@0.85/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:921)
	at arb4j@0.85/arb.expressions.Expression.determine(Expression.java:750)
	at arb4j@0.85/arb.expressions.nodes.unary.When.evaluateDefaultValue(When.java:211)
	at arb4j@0.85/arb.expressions.nodes.unary.When.evaluateValue(When.java:151)
	at arb4j@0.85/arb.expressions.nodes.unary.When.<init>(When.java:117)
	at arb4j@0.85/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:998)
	at arb4j@0.85/arb.expressions.Expression.evaluate(Expression.java:722)
	at arb4j@0.85/arb.expressions.Expression.exponentiate(Expression.java:801)
	at arb4j@0.85/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:919)
	at arb4j@0.85/arb.expressions.Expression.determine(Expression.java:750)
	at arb4j@0.85/arb.expressions.Expression.evaluateRootNode(Expression.java:910)
	at arb4j@0.85/arb.expressions.Expression.generateEvaluationMethod(Expression.java:464)
	at arb4j@0.85/arb.expressions.Expression.generate(Expression.java:369)
	at arb4j@0.85/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j@0.85/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j@0.85/arb.expressions.Expression.instantiate(Expression.java:125)
	at arb4j@0.85/arb.functions.Function.express(Function.java:145)
	at arb4j@0.85/arb.functions.real.HypergeometricFunctionSequence.<init>(HypergeometricFunctionSequence.java:61)
	at arb4j@0.85/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: generate code to evaluate Product[factor=BinaryOperation[left=α[k], right=n - 1, operation=risingFactorial, generatedType=null], k=LiteralConstant[fieldName=c2, value=1, type=arb.Integer]..Variable[reference=VariableReference[name=p, index=null, type=arb.Integer], type=arb.Integer]]
	at arb4j@0.85/arb.expressions.nodes.nary.Product.generate(Product.java:42)
	at arb4j@0.85/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:113)
	at arb4j@0.85/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:114)
	at arb4j@0.85/arb.expressions.nodes.unary.UnaryOperation.generate(UnaryOperation.java:58)
	at arb4j@0.85/arb.expressions.nodes.unary.When.generate(When.java:79)
	at arb4j@0.85/arb.expressions.Expression.generateEvaluationMethod(Expression.java:482)
	at arb4j@0.85/arb.expressions.Expression.generate(Expression.java:369)
	at arb4j@0.85/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j@0.85/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j@0.85/arb.expressions.Expression.instantiate(Expression.java:125)
	at arb4j@0.85/arb.functions.Function.express(Function.java:145)
	at arb4j@0.85/arb.functions.real.HypergeometricFunctionSequence.<init>(HypergeometricFunctionSequence.java:61)
	at arb4j@0.85/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)

```

**Comment by crowlogic** [comment]
```java
java.lang.AssertionError: TODO: generate calculation Product[factor=BinaryOperation[left=α[k], right=n - 1, operation=risingFactorial, generatedType=null], indexVar=Variable[reference=VariableReference[name=k, index=null, type=arb.Integer], type=arb.RealPolynomial], startIndex=LiteralConstant[fieldName=c2, value=1, type=arb.Integer], endIndex=Variable[reference=VariableReference[name=p, index=null, type=arb.Integer], type=arb.Integer]]
	at arb4j/arb.expressions.nodes.nary.Product.generate(Product.java:50)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:114)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:115)
	at arb4j/arb.expressions.nodes.unary.UnaryOperation.generate(UnaryOperation.java:59)
	at arb4j/arb.expressions.nodes.unary.When.generate(When.java:80)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:482)
	at arb4j/arb.expressions.Expression.generate(Expression.java:369)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:125)
	at arb4j/arb.functions.Function.express(Function.java:145)
	at arb4j/arb.functions.real.HypergeometricFunctionSequence.<init>(HypergeometricFunctionSequence.java:61)
	at arb4j/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
```

**Comment by crowlogic** [comment]
```java
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import static org.objectweb.asm.Opcodes.*;

public class LoopBytecodeGenerator {

    public static byte[] generateLoopClass() {
        ClassWriter classWriter = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        MethodVisitor mv;

        // Define the class
        classWriter.visit(V1_8, ACC_PUBLIC, "GeneratedLoopClass", null, "java/lang/Object", null);

        // Define the method
        mv = classWriter.visitMethod(ACC_PUBLIC + ACC_STATIC, "calculateProduct", "(II)I", null, null);
        mv.visitCode();

        // Define local variables: startIndex, endIndex, product
        // Assume startIndex and endIndex are method arguments (at indices 0 and 1)
        int productVarIndex = 2;
        mv.visitInsn(ICONST_1); // Initial product value (1)
        mv.visitVarInsn(ISTORE, productVarIndex); // Store in local variable

        // Start of the loop
        Label loopStart = new Label();
        mv.visitLabel(loopStart);

        // Check loop condition (startIndex < endIndex)
        // Load indices and compare
        mv.visitVarInsn(ILOAD, 0); // Load startIndex
        mv.visitVarInsn(ILOAD, 1); // Load endIndex
        Label loopEnd = new Label();
        mv.visitJumpInsn(IF_ICMPGE, loopEnd); // Jump to loopEnd if startIndex >= endIndex

        // Body of the loop
        // TODO: Add code to load element and multiply with the product accumulator
        // ...

        // Increment startIndex
        mv.visitIincInsn(0, 1); // Increment startIndex

        // Jump back to the start of the loop
        mv.visitJumpInsn(GOTO, loopStart);

        // End of the loop
        mv.visitLabel(loopEnd);
        mv.visitVarInsn(ILOAD, productVarIndex); // Load the product result
        mv.visitInsn(IRETURN); // Return the product

        // Complete the method
        mv.visitMaxs(-1, -1); // These are computed because of COMPUTE_FRAMES and COMPUTE_MAXS
        mv.visitEnd();

        // Complete the class
        classWriter.visitEnd();

        return classWriter.toByteArray();
    }

    public static void main(String[] args) {
        byte[] classData = generateLoopClass();
        // TODO: Load and use the generated class
        // ...
    }
}
```

**Comment by crowlogic** [comment]
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import static org.objectweb.asm.Opcodes.*;

public class FluentLoopWithRealAndIncrement {

    public static byte[] generateFluentLoopWithRealAndIncrement() {
        ClassWriter classWriter = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        MethodVisitor mv;

        // Define a method that takes a Real instance as an argument, modifies it in a loop, and returns it
        mv = classWriter.visitMethod(ACC_PUBLIC, "calculateProductFluently", "(Larb/Real;)Larb/Real;", null, null);
        mv.visitCode();

        // Initialize or reset the Real instance to one at the beginning of the method
        mv.visitVarInsn(ALOAD, 1); // Load the Real instance argument onto the stack
        mv.visitMethodInsn(INVOKEVIRTUAL, "arb/Real", "one", "()Larb/Real;", false); 

        // Define the start of the loop
        Label loopStart = new Label();
        Label afterLoop = new Label();
        mv.visitLabel(loopStart);

        // Assuming 'index' and 'endIndex' comparison logic here
        // For demonstration, let's assume 'index' is a field of type YourMutableIntegerClass and we're comparing it to 'endIndex'
        getField(mv, "YourClass", "index", "LYourMutableIntegerClass;"); // Load 'index'
        getField(mv, "YourClass", "endIndex", "LYourMutableIntegerClass;"); // Load 'endIndex'
        mv.visitMethodInsn(INVOKEVIRTUAL, "YourMutableIntegerClass", "compareTo", "(LYourMutableIntegerClass;)I", false);
        mv.visitJumpInsn(IFGE, afterLoop); // If 'index' >= 'endIndex', jump to the end of the loop

        // Apply the 'factor' function to the Real instance, using the current 'index'
        // This assumes 'factor' is a method in 'YourClass' that operates on 'Real'
        mv.visitVarInsn(ALOAD, 0); // Load 'this'
        mv.visitVarInsn(ALOAD, 1); // Load the 'Real' instance
        getField(mv, "YourClass", "index", "LYourMutableIntegerClass;"); // Load 'index'
        mv.visitMethodInsn(INVOKEVIRTUAL, "YourClass", "factor", "(Larb/Real;LYourMutableIntegerClass;)Larb/Real;", false);
        mv.visitVarInsn(ASTORE, 1); // Store the result back into the 'Real' instance variable

        // Increment 'index'
        getField(mv, "YourClass", "index", "LYourMutableIntegerClass;"); // Load 'index'
        mv.visitMethodInsn(INVOKEVIRTUAL, "YourMutableIntegerClass", "increment", "()V", false);

        // Jump back to the start of the loop
        mv.visitJumpInsn(GOTO, loopStart);
        mv.visitLabel(afterLoop);

        // Return the modified Real instance
        mv.visitVarInsn(ALOAD, 1);
        mv.visitInsn(ARETURN);

        mv.visitMaxs(4, 2); // Automatically compute the maximum stack size and the number of local variables
        mv.visitEnd();

        return classWriter.toByteArray();
    }

    private static void getField(MethodVisitor mv, String owner, String name, String descriptor) {
        mv.visitVarInsn(ALOAD, 0); // Load 'this'
        mv.visitFieldInsn(GETFIELD, owner, name, descriptor);
    }
}

**Comment by crowlogic** [comment]
why is it generating super.k instead of this.k?

**Comment by crowlogic** [comment]
* FIXME: make this a prototype then run asmifier on it then work back from there

**Comment by crowlogic** [comment]
generator works.. now to integrate it

```java
package arb;

import arb.functions.Function;

public class GeneratedProductClass {
   public Function<Integer, Real> factor;
   public Integer startIndex = new Integer();
   public Integer endIndex = new Integer();
   public Integer index = new Integer();
   Real value = new Real();

   public Real evaluate(int var1, Real var2) {
      var2.one();
      index.set(startIndex);

      while(index.compareTo(endIndex) <= 0) {
         var2.mul(factor.evaluate(index, var1, value), var1, var2);
         index.increment();
      }

      return var2;
   }
}
```

**Comment by crowlogic** [comment]
finally got the fuckin asm stuff now to debug


```java
java.lang.IndexOutOfBoundsException: Trying to set an inexistant local variable 0
	at arb4j/arb.expressions.executionflow.Frame.setLocal(Frame.java:202)
	at arb4j/arb.expressions.executionflow.Analyzer.computeInitialFrame(Analyzer.java:524)
	at arb4j/arb.expressions.executionflow.Analyzer.analyze(Analyzer.java:273)
	at arb4j/arb.expressions.Expression.analyze(Expression.java:116)
	at arb4j/arb.expressions.Expression.load(Expression.java:445)
	at arb4j/arb.expressions.Compiler.reify(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.reify(Compiler.java:115)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:143)
	at arb4j/arb.functions.real.NullaryFunction.express(NullaryFunction.java:31)
	at arb4j/arb.functions.real.RealNullaryFunction.express(RealNullaryFunction.java:26)
	at arb4j/arb.expressions.nodes.nary.ProductTest.testOneTimesTwoTimesThreeEqualsSix(ProductTest.java:31)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
crow@c17:~/a/src/main/java/arb/expressions/executionflow$ grep -r -i compute *
Analyzer.java:   * Computes and returns the maximum number of local variables used in the given
Analyzer.java:  private static int computeMaxLocals(final MethodNode method)
Analyzer.java:   * Computes and returns the maximum stack size of a method, given its stack map
Analyzer.java:  private static int computeMaxStack(final Frame<?>[] frames)
Analyzer.java:    currentFrame = computeInitialFrame(owner, method);
Analyzer.java:   * Analyzes the given method and computes and sets its maximum stack size and
Analyzer.java:  public Frame<V>[] analyzeAndComputeMaxs(final String owner, final MethodNode method) throws AnalyzerException
Analyzer.java:    method.maxLocals = computeMaxLocals(method);
Analyzer.java:    method.maxStack = computeMaxStack(frames);
Analyzer.java:   * Computes the initial execution stack frame of the given method.
Analyzer.java:  private Frame<V> computeInitialFrame(final String owner, final MethodNode method)
Analyzer.java:    // For each instruction, compute the subroutine to which it belongs.
Frame.java:   * @param interpreter the interpreter to use to compute values from other
SimpleVerifier.java: * This verifier computes exact class types, instead of using a single "object
SimpleVerifier.java:   * can be computed from the class being verified, and the types of its super
```

**Comment by crowlogic** [comment]
milestone!!

```bash
crow@c17:~/a$ decompile '∏k{k=OnePointPointThree}.class'
```

```java
INFO:  JVM info: Oracle Corporation - 21.0.1 - 21.0.1+12-LTS-29
INFO:  Scanning classes from file ∏k{k=OnePointPointThree}.class
INFO:  Loading Class: ∏k{k=OnePointPointThree} from file ∏k{k=OnePointPointThree}.class
INFO:  Preprocessing class ∏k{k=OnePointPointThree}
INFO:  ... done
INFO:  Decompiling class ∏k{k=OnePointPointThree}
INFO:  ... done
import arb.Integer;
import arb.Real;
import arb.functions.real.NullaryFunction;

public class ∏k{k=OnePointPointThree} implements NullaryFunction {
   Integer c1 = new Integer("1");
   Integer c2 = new Integer("3");
   public Real ℝ1 = new Real();

   public Real evaluate(Void in, int order, int bits, Real result) {
      ℝ1.identity();
      index.set(startIndex);

      do {
         ℝ1.mul(factor.evaluate(index, bits, factorValue), bits);
      } while(index.increment().compareTo(endIndex) <= 0);

      return result.set(ℝ1);
   }

   public void close() {
      c1.close();
      c2.close();
      ℝ1.close();
   }
}
```

**Comment by crowlogic** [comment]
```java
java.lang.NoSuchFieldError: Class ∏k{k=1…3} does not have member field 'arb.Integer startIndex'
	at ∏k{k=1…3}.evaluate(Unknown Source)
	at arb4j/arb.functions.Function.evaluate(Function.java:111)
	at arb4j/arb.expressions.nodes.nary.ProductTest.testOneTimesTwoTimesThreeEqualsSix(ProductTest.java:30)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

```java
import arb.Integer;
import arb.Real;
import arb.functions.real.RealNullaryFunction;

public class ∏k{k=1…3} implements RealNullaryFunction {
   Integer c1 = new Integer("1");
   Integer c2 = new Integer("3");
   public Integer index;
   public Real ℝ1 = new Real();

   public Real evaluate(Void in, int order, int bits, Real result) {
      ℝ1.multiplicativeIdentity();
      index.set(startIndex);

      do {
         ℝ1.mul(factor.evaluate(index, bits, factorValue), bits);
      } while(index.increment().compareTo(endIndex) <= 0);

      return result.set(ℝ1);
   }

   public void close() {
      c1.close();
      c2.close();
      ℝ1.close();
   }
}
```
```

**Comment by crowlogic** [comment]
```javapackage arb.functions.real;

import arb.Integer;
import arb.Real;
import arb.functions.Function;

public class GeneratedProductTest implements
                                  RealNullaryFunction
{
  Integer                 startIndex  = new Integer("1");
  Integer                 endIndex    = new Integer("3");
  public Integer          k;
  public Real             ℝ1          = new Real();
  Function<Integer, Real> factor;
  Real                    factorValue = new Real();

  public Real evaluate(Void in, int order, int bits, Real result)
  {
    ℝ1.multiplicativeIdentity();
    k.set(startIndex);

    do
    {
      ℝ1.mul(factor.evaluate(k, bits, factorValue), bits);
    }
    while (k.increment().compareTo(endIndex) <= 0);

    return result.set(ℝ1);
  }

  public void close()
  {
    startIndex.close();
    endIndex.close();
    ℝ1.close();
  }

  public static void main(String args[])
  {
    GeneratedProductTest prod = new GeneratedProductTest();
    prod.factor = (t, order, bits, res) ->
    {
      System.out.format("factor %s\n", t);
      return res.set(t);
    };
    Real result = prod.evaluate(null, 128, new Real());
    System.out.println("Result=" + result);
  }
}
```

**Comment by crowlogic** [comment]
```java
crow@c15:~/a$ decompile factor.class
INFO:  JVM info: Oracle Corporation - 21.0.1 - 21.0.1+12-LTS-29
INFO:  Scanning classes from file factor.class
INFO:  Loading Class: factor from file factor.class
INFO:  Preprocessing class factor
INFO:  ... done
INFO:  Decompiling class factor
INFO:  ... done
import arb.Integer;
import arb.Real;
import arb.functions.Function;

public class factor implements Function<Integer, Real> {
   public Integer k;

   public Real evaluate(Integer in, int order, int bits, Real result) {
      return result.set(in);
   }
}
crow@c15:~/a$ 
crow@c15:~/a$ 
crow@c15:~/a$ decompile factor.class
INFO:  JVM info: Oracle Corporation - 21.0.1 - 21.0.1+12-LTS-29
INFO:  Scanning classes from file factor.class
INFO:  Loading Class: factor from file factor.class
INFO:  Preprocessing class factor
INFO:  ... done
INFO:  Decompiling class factor
INFO:  ... done
import arb.Integer;
import arb.Real;
import arb.functions.Function;

public class factor implements Function<Integer, Real> {
   public Integer k;

   public Real evaluate(Integer in, int order, int bits, Real result) {
      return result.set(in);
   }
}
crow@c15:~/a$ decompile '∏k{k=1…3}.class'
INFO:  JVM info: Oracle Corporation - 21.0.1 - 21.0.1+12-LTS-29
INFO:  Scanning classes from file ∏k{k=1…3}.class
INFO:  Loading Class: ∏k{k=1…3} from file ∏k{k=1…3}.class
INFO:  Preprocessing class ∏k{k=1…3}
INFO:  ... done
INFO:  Decompiling class ∏k{k=1…3}
INFO:  ... done
import arb.Integer;
import arb.Real;
import arb.functions.real.RealNullaryFunction;

public class ∏k{k=1…3} implements RealNullaryFunction {
   Integer startIndex;
   Integer endIndex;
   public Integer k;
   public Real ℝ1;
   public final factor factor = new factor();

   public Real evaluate(Void in, int order, int bits, Real result) {
      ℝ1.multiplicativeIdentity();
      k.set(startIndex);

      do {
         ℝ1.mul(factor.evaluate(k, bits, factorValue), bits);
      } while(k.increment().compareTo(endIndex) <= 0);

      return result.set(ℝ1);
   }

   public _k_k_1_3_/* $VF was: ∏k{k=1…3}*/() {
      startIndex = new Integer("1");
      endIndex = new Integer("3");
      ℝ1 = new Real();
   }

   public void close() {
      startIndex.close();
      endIndex.close();
      ℝ1.close();
   }
}```
