### ISSUE TITLE
expression compiler: implement rising factorial, a[k]₍ₙ₋₁₎ != a[k](n-1)

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#311]
```java
arb.exceptions.ExpressionCompilerException: expected closing parenthesis, instead got ₍ at position 28 in expression 'n➔when(n=0,1,else,x*F(n-1)/((∏αₖ₌₁…ₚ₍ₙ₋₁₎)/(∏βₖ₌₁…q₍ₙ₋₁₎)))'
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:701)
	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:787)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:898)
	at arb4j/arb.expressions.Expression.reckon(Expression.java:751)
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:697)
	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:787)
	at arb4j/arb.expressions.Expression.multiplyAndDivide(Expression.java:918)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:900)
	at arb4j/arb.expressions.Expression.reckon(Expression.java:751)
	at arb4j/arb.expressions.nodes.unary.When.evaluateDefaultValue(When.java:211)
	at arb4j/arb.expressions.nodes.unary.When.evaluateValue(When.java:151)
	at arb4j/arb.expressions.nodes.unary.When.<init>(When.java:117)
	at arb4j/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:974)
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:713)
	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:787)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:898)
	at arb4j/arb.expressions.Expression.reckon(Expression.java:751)
	at arb4j/arb.expressions.Expression.evaluateRootNode(Expression.java:889)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:462)
	at arb4j/arb.expressions.Expression.generate(Expression.java:367)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:123)
	at arb4j/arb.functions.Function.express(Function.java:145)
	at arb4j/arb.functions.real.HypergeometricFunctionSequence.<init>(HypergeometricFunctionSequence.java:61)
	at arb4j/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
arb.exceptions.ExpressionCompilerException: unexpected '₍' character at position=1 in expression 'x₍₃₎' of length 4

	at arb4j@0.85/arb.expressions.Expression.generateEvaluationMethod(Expression.java:467)
	at arb4j@0.85/arb.expressions.Expression.generate(Expression.java:368)
	at arb4j@0.85/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j@0.85/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j@0.85/arb.expressions.Expression.instantiate(Expression.java:124)
	at arb4j@0.85/arb.functions.real.RealFunction.express(RealFunction.java:611)
	at arb4j@0.85/arb.functions.real.RealFunction.express(RealFunction.java:606)
	at arb4j@0.85/arb.expressions.ExpressionTest.testRisingFactorial(ExpressionTest.java:15)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
I understand now, you're working with a more direct approach where your recursive descent parser processes the input character by character. Given this approach, integrating the parsing of a rising factorial with subscripted parentheses requires a specific handling strategy within your parser. Here's a way to do it:

1. **Detecting the Rising Factorial:** Modify your parser to recognize the pattern that indicates a rising factorial. Since you're processing character by character, you'll need to identify the start of the subscripted parentheses that denote the rising factorial. This could be a specific UTF character or a sequence of characters.

2. **Parsing the Operand:** When you encounter the start of the rising factorial pattern, you should have already parsed the operand (the expression to the left of the rising factorial). This operand needs to be temporarily stored as it will be part of the rising factorial expression.

3. **Parsing the Subscript:** Continue parsing the characters inside the subscripted parentheses. This will typically be the power to which the factorial will rise. This part of the parsing would involve recognizing the subscript numbers or expressions.

4. **Constructing the Expression Tree Node:** Once you have both the operand and the power, you can emit an expression tree node representing the rising factorial operation. This node will have the operand as its left child (or its base expression) and the power as its right child (or the exponent).

5. **Handling Precedence and Associativity:** Ensure that the precedence and associativity rules of the rising factorial operation are correctly implemented. This might involve adjusting how your parser handles the surrounding expressions and operators.

6. **Integrating with JVM Code Generation:** Finally, integrate this new node type into your JVM code generation logic. This will involve writing the code to handle the rising factorial operation, likely translating it into a method call or a series of instructions that implement the factorial computation.

By following these steps and adjusting them to fit the specifics of your existing parser implementation, you should be able to integrate the rising factorial with subscripted parentheses into your system.

**Comment by crowlogic** [comment]
I understand now, you're working with a more direct approach where your recursive descent parser processes the input character by character. Given this approach, integrating the parsing of a rising factorial with subscripted parentheses requires a specific handling strategy within your parser. Here's a way to do it:

1. **Detecting the Rising Factorial:** Modify your parser to recognize the pattern that indicates a rising factorial. Since you're processing character by character, you'll need to identify the start of the subscripted parentheses that denote the rising factorial. This could be a specific UTF character or a sequence of characters.

2. **Parsing the Operand:** When you encounter the start of the rising factorial pattern, you should have already parsed the operand (the expression to the left of the rising factorial). This operand needs to be temporarily stored as it will be part of the rising factorial expression.

3. **Parsing the Subscript:** Continue parsing the characters inside the subscripted parentheses. This will typically be the power to which the factorial will rise. This part of the parsing would involve recognizing the subscript numbers or expressions.

4. **Constructing the Expression Tree Node:** Once you have both the operand and the power, you can emit an expression tree node representing the rising factorial operation. This node will have the operand as its left child (or its base expression) and the power as its right child (or the exponent).

5. **Handling Precedence and Associativity:** Ensure that the precedence and associativity rules of the rising factorial operation are correctly implemented. This might involve adjusting how your parser handles the surrounding expressions and operators.

6. **Integrating with JVM Code Generation:** Finally, integrate this new node type into your JVM code generation logic. This will involve writing the code to handle the rising factorial operation, likely translating it into a method call or a series of instructions that implement the factorial computation.

By following these steps and adjusting them to fit the specifics of your existing parser implementation, you should be able to integrate the rising factorial with subscripted parentheses into your system.

**Comment by crowlogic** [comment]
You've identified an interesting approach. The rising factorial notation does indeed behave somewhat like an operator, with the key difference being its postfix position relative to its operand. This distinction changes how you parse and handle it compared to standard infix operators like plus, minus, divide, or multiply. Let's break down how to handle this:

1. **Operand Precedence:** In standard expressions, operators are placed between operands, and the parser handles them as it encounters them. However, for a postfix operator like the rising factorial, the operand appears before the operator. Since your existing parsing strategy handles operands on the fly, you need to modify it to retain the last parsed operand when a postfix operator is encountered.

2. **Treating Rising Factorial as an Operator:** You can indeed treat the rising factorial's opening subscripted parenthesis as a special kind of operator. This operator would not have a left operand immediately preceding it (since the operand is already parsed), but it would have a right-hand side expression within the subscripted parentheses.

3. **Parsing the Subscripted Expression:** Once you identify the start of the rising factorial (the opening subscripted parenthesis), you can parse the subscripted content as a regular expression. This would involve temporarily treating the subscripted parentheses as regular ones for the purpose of parsing the expression inside them.

4. **Inserting the Implied Opening Parenthesis:** Your idea to insert an implied opening parenthesis is a clever way to reuse your existing parsing logic. By treating the start of the rising factorial as an opening parenthesis, you can parse the enclosed expression using your standard mechanism for handling parenthetical expressions.

5. **Combining the Operand and the Subscripted Expression:** After parsing the subscripted expression, you combine it with the previously parsed operand to form the rising factorial expression. This combination is unique to postfix operators like the rising factorial.

6. **Generating the AST Node:** Finally, generate an AST node representing the rising factorial operation. This node will include the previously parsed operand and the result of parsing the subscripted expression.

By adapting your parser to treat the rising factorial as a special case of operator with its unique parsing requirements, you can integrate it into your existing recursive descent parsing framework. This approach leverages the strengths of your current system while accommodating the peculiarities of the rising factorial notation.

**Comment by crowlogic** [comment]
Given your description, it sounds like the main challenge is adapting your existing `Evaluate` function to correctly handle the rising factorial, which is a binary operation with postfix notation. The key here is to modify your parser to correctly interpret and store the left-hand side expression (the operand of the rising factorial) and then process the right-hand side (the subscript) as the second operand of this binary operation. Here's a strategy to consider:

1. **Handling the Left-hand Side (Operand):** Since the left-hand side can be any expression and not just a variable, your parser needs to store the last evaluated node before encountering the rising factorial notation. Ensure that your mechanism for storing the last node is correctly capturing the entire left-hand side expression, not just variables or simple nodes.

2. **Modifying the 'Evaluate' Function:**
    - When your `Evaluate` function encounters an opening subscripted parenthesis, instead of treating it as a function call or a variable declaration, recognize it as the start of a rising factorial operation.
    - At this point, the left-hand side expression should have already been processed and stored. Ensure this expression is retained and not overwritten as you begin to parse the right-hand side.

3. **Parsing the Right-hand Side (Subscript):**
    - Treat the content within the subscripted parentheses as a regular expression. This will be the second operand of your binary operation (the rising factorial's power).
    - Once this expression is parsed, you will have both operands needed for the rising factorial operation.

4. **Constructing the Binary Operation Node:**
    - Create a new type of node in your AST that represents the rising factorial operation. This node should be binary, holding two child nodes: the left-hand side expression and the right-hand side subscript expression.
    - This node type is distinct from your unary function invocation nodes, reflecting the binary nature of the operation.

5. **Integrating into the AST:**
    - Integrate this new node into your AST at the point where you previously stored the last node. This new node replaces the last node as the current focus of the parsing process.

6. **Ensuring Precedence and Associativity:** 
    - Ensure that the precedence and associativity rules are correctly implemented, especially since the rising factorial is a postfix operator and might interact differently with surrounding operators and expressions compared to infix or prefix operators.

By making these adjustments, your `Evaluate` function and parsing mechanism should be able to correctly interpret and process rising factorial expressions, integrating them seamlessly into your existing framework for handling mathematical expressions.

**Comment by crowlogic** [comment]
need to move it.. theres a better way to do it

```java
java.lang.AssertionError: TODO: instantiate RisingFactorial here
	at arb4j@0.85/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:1048)
	at arb4j@0.85/arb.expressions.Expression.evaluate(Expression.java:734)
	at arb4j@0.85/arb.expressions.nodes.nary.Product.<init>(Product.java:48)
	at arb4j@0.85/arb.expressions.Expression.multiplyAndDivide(Expression.java:958)
	at arb4j@0.85/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:933)
	at arb4j@0.85/arb.expressions.Expression.determine(Expression.java:762)
	at arb4j@0.85/arb.expressions.Expression.evaluate(Expression.java:701)
	at arb4j@0.85/arb.expressions.Expression.exponentiate(Expression.java:813)
	at arb4j@0.85/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:931)
	at arb4j@0.85/arb.expressions.Expression.determine(Expression.java:762)
	at arb4j@0.85/arb.expressions.Expression.evaluate(Expression.java:701)
	at arb4j@0.85/arb.expressions.Expression.exponentiate(Expression.java:813)
	at arb4j@0.85/arb.expressions.Expression.multiplyAndDivide(Expression.java:953)
	at arb4j@0.85/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:933)
	at arb4j@0.85/arb.expressions.Expression.determine(Expression.java:762)
	at arb4j@0.85/arb.expressions.nodes.unary.When.evaluateDefaultValue(When.java:211)
	at arb4j@0.85/arb.expressions.nodes.unary.When.evaluateValue(When.java:151)
	at arb4j@0.85/arb.expressions.nodes.unary.When.<init>(When.java:117)
	at arb4j@0.85/arb.expressions.Expression.resolveFunctionInvocationOrVariableReference(Expression.java:1010)
	at arb4j@0.85/arb.expressions.Expression.evaluate(Expression.java:734)
	at arb4j@0.85/arb.expressions.Expression.exponentiate(Expression.java:813)
	at arb4j@0.85/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:931)
	at arb4j@0.85/arb.expressions.Expression.determine(Expression.java:762)
	at arb4j@0.85/arb.expressions.Expression.evaluateRootNode(Expression.java:922)
	at arb4j@0.85/arb.expressions.Expression.generateEvaluationMethod(Expression.java:464)
	at arb4j@0.85/arb.expressions.Expression.generate(Expression.java:369)
	at arb4j@0.85/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j@0.85/arb.expressions.Compiler.compile(Compiler.java:115)
	at arb4j@0.85/arb.expressions.Expression.instantiate(Expression.java:125)
	at arb4j@0.85/arb.functions.Function.express(Function.java:145)
	at arb4j@0.85/arb.functions.real.HypergeometricFunctionSequence.<init>(HypergeometricFunctionSequence.java:61)
	at arb4j@0.85/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```
