### ISSUE TITLE
fix analyzer

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#323]
# Enhancing ASM for Better Debugging

## Introduction

Debugging bytecode-level issues requires a high level of detail and precision. Default exception messages provided by ASM when computing frames may be insufficient for complex debugging tasks. Enhancing ASM to output more informative debugging information can be highly beneficial.

## Strategy for Improvement

Encountering vague exceptions during frame computation often indicates a discrepancy between bytecode instructions and stack map frames. Customizing ASM to provide more informative exceptions can aid in pinpointing the cause of such issues.

## Customizing ASM

By modifying the `Analyzer` class to catch exceptions and log the frame state at the point of failure, better insight into ASM's internal state during analysis can be achieved. This involves:

- Overriding methods that throw exceptions
- Including more context in the error messages, such as:
  - Current instruction
  - Local variables
  - Stack contents

## Testing

It's crucial to thoroughly test the modified version of ASM. Changes to this low-level tool can significantly impact bytecode manipulation and analysis tasks.

**Comment by crowlogic** [comment]
'''java
import org.objectweb.asm.*;
import org.objectweb.asm.util.*;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;

public class ASMStackPrinter {
    public static void main(String[] args) throws IOException {
        // Assuming `classReader` is an instance of ClassReader initialized with a class.
        ClassReader classReader = new ClassReader("com/example/MyClass");

        // Create a ClassWriter with the COMPUTE_FRAMES flag to automatically compute stack map frames.
        ClassWriter classWriter = new ClassWriter(classReader, ClassWriter.COMPUTE_FRAMES);

        // Create a Printer that will print the methods with the stack and local variables.
        Printer printer = new Textifier();
        TraceClassVisitor traceVisitor = new TraceClassVisitor(null, printer, new PrintWriter(System.out));

        // Tell the ClassReader to expand the frames
        classReader.accept(traceVisitor, ClassReader.EXPAND_FRAMES);

        // Optionally, print the result to a StringWriter or directly to System.out
        StringWriter stringWriter = new StringWriter();
        printer.print(new PrintWriter(stringWriter));
        System.out.println(stringWriter.toString());
    }
}'''

**Comment by crowlogic** [comment]
'''java
import org.objectweb.asm.*;
import org.objectweb.asm.util.*;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;

public class ASMStackPrinter {
    public static void main(String[] args) throws IOException {
        // Assuming `classReader` is an instance of ClassReader initialized with a class.
        ClassReader classReader = new ClassReader("com/example/MyClass");

        // Create a ClassWriter with the COMPUTE_FRAMES flag to automatically compute stack map frames.
        ClassWriter classWriter = new ClassWriter(classReader, ClassWriter.COMPUTE_FRAMES);

        // Create a Printer that will print the methods with the stack and local variables.
        Printer printer = new Textifier();
        TraceClassVisitor traceVisitor = new TraceClassVisitor(null, printer, new PrintWriter(System.out));

        // Tell the ClassReader to expand the frames
        classReader.accept(traceVisitor, ClassReader.EXPAND_FRAMES);

        // Optionally, print the result to a StringWriter or directly to System.out
        StringWriter stringWriter = new StringWriter();
        printer.print(new PrintWriter(stringWriter));
        System.out.println(stringWriter.toString());
    }
}'''

**Comment by crowlogic** [comment]
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;
// Use your custom analyzer and related classes
import your.custom.package.Analyzer;
import your.custom.package.ClassNode;
import your.custom.package.MethodNode;
import your.custom.package.tree.analysis.BasicValue;
import your.custom.package.tree.analysis.BasicInterpreter;

// Bytecode generation with ClassWriter, not specifying COMPUTE_FRAMES
ClassWriter cw = new ClassWriter(0); // No automatic frame computation
cw.visit(Opcodes.V1_8, Opcodes.ACC_PUBLIC + Opcodes.ACC_SUPER, "Your/ClassName", null, "java/lang/Object", null);

// Add methods and fields to `cw` as needed

cw.visitEnd();

// Assuming you have a mechanism to convert `cw` bytecode to a ClassNode for analysis
// This might involve reading the generated bytecode back through a ClassReader into a ClassNode

// Analyze the bytecode with your custom Analyzer
Analyzer<BasicValue> analyzer = new Analyzer<>(new BasicInterpreter());
for (MethodNode method : classNode.methods) {
    analyzer.analyze("Your/ClassName", method);
    // Your analyzer processes each method, computing frames and adding debug info as configured
}

// At this point, the bytecode represented by `cw` has been processed by your analyzer,
// with frames computed as per the original ASM logic plus your debug enhancements.

**Comment by crowlogic** [comment]
how to use the AnalyzerAdapter for stack tracking purposes only

import org.objectweb.asm.commons.AnalyzerAdapter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
```
public class FrameSkippingAnalyzerAdapter extends AnalyzerAdapter {

    public FrameSkippingAnalyzerAdapter(String owner, int access, String name, String desc, MethodVisitor mv) {
        super(Opcodes.ASM9, owner, access, name, desc, mv);
    }

    @Override
    public void visitFrame(int type, int nLocal, Object[] local, int nStack, Object[] stack) {
        // Skip frame processing entirely by not calling super.visitFrame
        // This effectively ignores frame information during analysis
    }

    // The rest of AnalyzerAdapter's functionality remains unchanged and operational
}
```

**Comment by crowlogic** [comment]
```java
java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    F.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @82: iload_3
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @82
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial', 'arb/RealPolynomial' }
  Stackmap Frame:
    bci: @82
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial' }
  Bytecode:
    0000000: 2bc0 000c b600 10aa 0000 0021 0000 0000
    0000010: 0000 0000 0000 0011 2ab4 0014 1904 c000
    0000020: 165f b600 1aa7 011f 1904 c000 16b6 001e
    0000030: 2ab4 0021 2bc0 000c 2ab4 0014 1d2a b400
    0000040: 24b6 0028 1c1d 2ab4 002c b900 2e05 00c0
    0000050: 0016 1d2a b400 31b6 0035 2ab4 0039 2bc0
    0000060: 000c b500 3d2a b400 41b6 0047 572a b400
    0000070: 4a2a b400 14b6 004d 572a b400 502a b400
    0000080: 53b6 004d 572a b400 412a b400 392a b400
    0000090: 4a1d 2ab4 0056 b900 5904 00c0 0043 1db6
    00000a0: 005c 572a b400 4ab6 0060 2ab4 0050 b600
    00000b0: 649e ffd4 1d2a b400 67b6 006a 1904 2bc0
    00000c0: 000c 2ab4 0014 1d2a b400 6db6 0028 1d2a
    00000d0: b400 70b6 0074 b600 772a b400 7b2b c000
    00000e0: 0cb5 007d 2ab4 0080 b600 4757 2ab4 004a
    00000f0: 2ab4 0014 b600 4d57 2ab4 0083 2ab4 0086
    0000100: b600 4d57 2ab4 0080 2ab4 007b 2ab4 004a
    0000110: 1d2a b400 89b9 0059 0400 c000 431d b600
    0000120: 5c57 2ab4 004a b600 602a b400 83b6 0064
    0000130: 9eff d41d 2ab4 008c b600 8f1d 1904 c000
    0000140: 16b6 0092 b0                           
  Stackmap Table:
    same_frame(@0)
    same_frame(@24)
    same_frame(@40)
    same_locals_1_stack_item_frame(@48,Object[#22])
    same_locals_1_stack_item_frame(@82,Object[#22])
    same_frame(@133)
    same_frame_extended(@260)
    same_locals_1_stack_item_frame(@324,Object[#22])

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.constructNewInstance(Expression.java:1106)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1094)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:127)
	at arb4j/arb.functions.Function.express(Function.java:154)
	at arb4j/arb.functions.real.HypergeometricPolynomialSequence.<init>(HypergeometricPolynomialSequence.java:63)
	at arb4j/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
fuck that thing it needs a good fork
