### ISSUE TITLE
fix conditionallyInstantiate

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#326]
```java
  public static MethodVisitor conditionallyInstantiate(MethodVisitor mv,
                                                       String thisClassName,
                                                       String className,
                                                       String fieldName,
                                                       String fieldType)
  {
    mv.visitVarInsn(ALOAD, 0);
    mv.visitFieldInsn(GETFIELD, className, fieldName, fieldType);
    Label fieldAlreadyPopulated = new Label();
    mv.visitJumpInsn(IFNONNULL, fieldAlreadyPopulated);
    mv.visitVarInsn(ALOAD, 0);

    mv.visitTypeInsn(Opcodes.NEW, className);
    mv.visitInsn(Opcodes.DUP);
    mv.visitVarInsn(Opcodes.ALOAD, 0);
    mv.visitMethodInsn(Opcodes.INVOKESPECIAL, className, "<init>", format("(L%s;)V", className), false);

    mv.visitFieldInsn(PUTFIELD, thisClassName, fieldName, fieldType);
    mv.visitLabel(fieldAlreadyPopulated);
    mv.visitFrame(F_SAME, 0, null, 0, null);
    return mv;
  }
```

```java
java.lang.VerifyError: Inconsistent stackmap frames at branch target 182
Exception Details:
  Location:
    P.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @167: ifnonnull
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @167
    flags: { }
    locals: { 'P', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial', 'P' }
  Stackmap Frame:
    bci: @182
    flags: { }
    locals: { 'P', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { }
  Bytecode:
    0000000: 2ab4 000e 9a00 072a b600 122b c000 14b6
    0000010: 0018 aa00 0000 007b 0000 0000 0000 0001
    0000020: 0000 0016 0000 0026 2ab4 001c 1904 c000
    0000030: 1e5f b600 22a7 0133 2ab4 0026 2ab4 002a
    0000040: 2ab4 001c b600 2f1c 1d2a b400 32b9 0036
    0000050: 0500 c000 2c19 04c0 001e b600 3a1d 2ab4
    0000060: 003e b600 422a b400 451d 2ab4 0048 b600
    0000070: 4c2a b400 4f1d 2ab4 0052 b600 552a b400
    0000080: 581d 1904 c000 1eb6 005c a700 de2a b400
    0000090: 602b c000 141c 1d2a b400 63b9 0064 0500
    00000a0: c000 1e2a b400 67c7 000f 2abb 0002 592a
    00000b0: b700 6bb5 0067 2ab4 0067 2bc0 0014 2ab4
    00000c0: 001c 1d2a b400 6eb6 0071 1c1d 2ab4 0074
    00000d0: b900 6405 00c0 001e 1d2a b400 77b6 0078
    00000e0: 2ab4 007c 2ab4 007f 2bc0 0014 b600 2f1c
    00000f0: 1d2a b400 82b9 0036 0500 c000 2c2a b400
    0000100: 67c7 000f 2abb 0002 592a b700 6bb5 0067
    0000110: 2ab4 0067 2bc0 0014 2ab4 0058 1d2a b400
    0000120: 85b6 0071 1c1d 2ab4 0088 b900 6405 00c0
    0000130: 001e 1d2a b400 8bb6 0042 1d2a b400 8eb6
    0000140: 0090 2ab4 0094 2ab4 0097 2bc0 0014 b600
    0000150: 2f1c 1d2a b400 9ab9 0036 0500 c000 2c1d
    0000160: 1904 c000 1eb6 009c b0                 
  Stackmap Table:
    same_frame(@11)
    same_frame(@40)
    same_frame(@56)
    same_frame_extended(@141)
    same_frame(@182)
    same_frame_extended(@272)
    same_locals_1_stack_item_extended(@360,Object[#30])

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1082)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:123)
	at arb4j/arb.functions.Function.express(Function.java:154)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:115)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP0(JacobiPolynomialTest.java:54)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
Description	Resource	Path	Location	Type
endIndex cannot be resolved to a variable	GeneratedProductTest.java	/arb4j/src/main/java/arb/functions/real	line 22	Java Problem
factor cannot be resolved	GeneratedProductTest.java	/arb4j/src/main/java/arb/functions/real	line 20	Java Problem
factorValue cannot be resolved to a variable	GeneratedProductTest.java	/arb4j/src/main/java/arb/functions/real	line 20	Java Problem
index cannot be resolved	GeneratedProductTest.java	/arb4j/src/main/java/arb/functions/real	line 16	Java Problem
index cannot be resolved	GeneratedProductTest.java	/arb4j/src/main/java/arb/functions/real	line 22	Java Problem
index cannot be resolved to a variable	GeneratedProductTest.java	/arb4j/src/main/java/arb/functions/real	line 20	Java Problem
startIndex cannot be resolved to a variable	GeneratedProductTest.java	/arb4j/src/main/java/arb/functions/real	line 16	Java Problem
```

**Comment by crowlogic** [comment]
```java
java.lang.NoSuchFieldError: Class ∏k{k=1…3} does not have member field 'arb.Integer index'
	at ∏k{k=1…3}.evaluate(Unknown Source)
	at arb4j/arb.functions.Function.evaluate(Function.java:111)
	at arb4j/arb.expressions.nodes.nary.ProductTest.testOneTimesTwoTimesThreeEqualsSix(ProductTest.java:30)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```
