### ISSUE TITLE
when busted

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#327]
when statement busted

```java
arb.exceptions.UndefinedReferenceException: Undefined reference to variable 'else' in Expression[expression=when(n=0,5,n=1,7,else,10), className=whenn=ZeroFiven=OneSevenelseOneZero, functionName=null, recursive=false, className=whenn=ZeroFiven=OneSevenelseOneZero, functionClass=interface arb.functions.Function], independent variable is Variable[reference=INPUT(VariableReference[name=n, index=null, type=arb.Integer]), type=arb.Integer]
	at arb4j/arb.expressions.nodes.Variable.resolveReference(Variable.java:244)
	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:109)
	at arb4j/arb.expressions.Expression.newVariable(Expression.java:1172)
	at arb4j/arb.expressions.Expression.resolveFunctionOrVariableReference(Expression.java:1319)
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:485)
	at arb4j/arb.expressions.nodes.unary.When.evaluateCases(When.java:142)
	at arb4j/arb.expressions.nodes.unary.When.<init>(When.java:119)
	at arb4j/arb.expressions.Expression.resolveFunction(Expression.java:1283)
	at arb4j/arb.expressions.Expression.resolveFunctionOrVariableReference(Expression.java:1310)
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:485)
	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:601)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:648)
	at arb4j/arb.expressions.Expression.determine(Expression.java:438)
	at arb4j/arb.expressions.Expression.parse(Expression.java:593)
	at arb4j/arb.expressions.Compiler.express(Compiler.java:149)
	at arb4j/arb.expressions.Compiler.express(Compiler.java:118)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:117)
	at arb4j/arb.functions.Function.express(Function.java:161)
	at arb4j/arb.functions.Function.express(Function.java:175)
	at arb4j/arb.expressions.nodes.unary.WhenTest.testWhen(WhenTest.java:14)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
fixed
