### ISSUE TITLE
debug when statement: fix stackmap so COMPUTE_FRAMES can be turned off and performance increased even more

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#328]
```java
java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    F.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @81: iload_3
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @81
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/Real', 'arb/Real' }
  Stackmap Frame:
    bci: @81
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/Real' }
  Bytecode:
    0000000: 2ab4 000e 9a00 072a b600 122a b400 162a
    0000010: b400 1a2b c000 1c2a b400 201d 2ab4 0023
    0000020: b600 27b6 002d 1c1d 2ab4 0030 b900 3405
    0000030: 00c0 0029 2ab4 0016 2ab4 0037 2bc0 001c
    0000040: b600 2d1c 1d2a b400 3ab9 0034 0500 c000
    0000050: 291d 1904 c000 29b6 003e b0            
  Stackmap Table:
    same_frame(@11)
    same_locals_1_stack_item_frame(@52,Object[#41])
    same_locals_1_stack_item_frame(@81,Object[#41])

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1110)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:128)
	at arb4j/arb.functions.Function.express(Function.java:154)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:92)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP0(JacobiPolynomialTest.java:54)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
Yes, when using ObjectWeb ASM with the COMPUTE_FRAMES option for automatic stack map frame computation, and then examining the bytecode through ASM's debug tools (like TraceClassVisitor), the automatically computed frames will appear in the output as if they were regular visitFrame instructions.

Here's a bit more detail on how it works and what you can expect:

    Automatic Frame Computation: When you use the COMPUTE_FRAMES option with ASM's ClassWriter, ASM automatically calculates all the stack map frames needed for the bytecode verification by the JVM. This is crucial for bytecode targeting Java 6 (version 50) and above, where explicit stack map frames are required.

    Debugging and Viewing Bytecode: Tools provided by ASM, such as TraceClassVisitor combined with a printer like ASMifier or Textifier, allow you to generate a human-readable version of the bytecode. This includes the visitFrame method calls that represent the stack map frames ASM has inserted.

    Appearance in Debug Output: In the debug output generated by these tools, the frames inserted by ASM will appear as visitFrame calls. These calls provide information about the type of frame (F_FULL, F_APPEND, F_CHOP, F_SAME, or F_SAME1), the local variable array, and the operand stack for that frame. This output mimics what you would write if you were manually inserting frame information using the visitFrame method in your ASM code.

    Learning from Automatic Frames: By examining these automatically inserted visitFrame calls, you can learn how and where to place your own frames when manually manipulating bytecode. It provides a practical example of the correct frame structure expected by the JVM at specific points in the bytecode, based on the operational stack and local variables' state.

For manual frame manipulation, understanding the specifics of each visitFrame call is crucial. This includes knowing the differences between the frame types and correctly identifying the state of the local variable array and operand stack at various points in your bytecode. This knowledge allows you to manually insert frames accurately when automatic computation might not suit your needs, such as when performing complex bytecode transformations that ASM cannot automatically infer the correct frames for.

**Comment by crowlogic** [comment]
```java
java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    factorr̅1.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @19: aload_0
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @19
    flags: { }
    locals: { 'factorr̅1', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/Real', 'arb/RealPolynomial' }
  Stackmap Frame:
    bci: @19
    flags: { }
    locals: { 'factorr̅1', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial' }
  Bytecode:
    0000000: 2ab4 000e 2bc0 0010 b600 1619 04c0 0018
    0000010: b600 1c2a b400 201d 2ab4 0024 b600 281d
    0000020: 1904 c000 18b6 002c b0                 
  Stackmap Table:
    same_locals_1_stack_item_frame(@19,Object[#24])

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.constructNewInstance(Expression.java:1106)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1094)
	at arb4j/arb.expressions.nodes.nary.Product.generateFactorClass(Product.java:244)
	at arb4j/arb.expressions.nodes.nary.Product.generate(Product.java:189)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:115)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:114)
	at arb4j/arb.expressions.nodes.unary.UnaryOperation.generate(UnaryOperation.java:58)
	at arb4j/arb.expressions.nodes.unary.When.generate(When.java:193)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:930)
	at arb4j/arb.expressions.Expression.compile(Expression.java:691)
	at arb4j/arb.expressions.Compiler.express(Compiler.java:134)
	at arb4j/arb.expressions.Compiler.express(Compiler.java:147)
	at arb4j/arb.expressions.Compiler.express(Compiler.java:100)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:121)
	at arb4j/arb.functions.Function.express(Function.java:154)
	at arb4j/arb.functions.real.HypergeometricPolynomialSequence.<init>(HypergeometricPolynomialSequence.java:63)
	at arb4j/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
	
```
