### ISSUE TITLE
fix recursive stack issue, either an element should be popped off the stack and it hasnt been or the stackmap should be updated to reflect the recursion.. i think the latter is the correct fix

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#338]
without compute_frames

```Java

java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    F.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @94: iload_3
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @94
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial', 'arb/RealPolynomial' }
  Stackmap Frame:
    bci: @94
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial' }
  Bytecode:
    0000000: 2ab4 000e 9a00 072a b600 122b c000 14b6
    0000010: 0018 aa00 0000 0022 0000 0000 0000 0000
    0000020: 0000 0012 2ab4 001c 1904 c000 1e5f b600
    0000030: 22a7 011f 1904 c000 1eb6 0026 2ab4 0029
    0000040: 2bc0 0014 2ab4 001c 1d2a b400 2cb6 0030
    0000050: 1c1d 2ab4 0034 b900 3605 00c0 001e 1d2a
    0000060: b400 39b6 003d 2ab4 0041 2bc0 0014 b500
    0000070: 452a b400 49b6 004f 572a b400 522a b400
    0000080: 1cb6 0055 572a b400 582a b400 5bb6 0055
    0000090: 572a b400 492a b400 412a b400 521d 2ab4
    00000a0: 005e b900 6104 00c0 004b 1db6 0064 572a
    00000b0: b400 52b6 0068 2ab4 0058 b600 6c9e ffd4
    00000c0: 1d2a b400 6fb6 0072 1904 2bc0 0014 2ab4
    00000d0: 001c 1d2a b400 75b6 0030 1d2a b400 78b6
    00000e0: 007c b600 7f2a b400 832b c000 14b5 0085
    00000f0: 2ab4 0088 b600 4f57 2ab4 0052 2ab4 001c
    0000100: b600 5557 2ab4 008b 2ab4 008e b600 5557
    0000110: 2ab4 0088 2ab4 0083 2ab4 0052 1d2a b400
    0000120: 91b9 0061 0400 c000 4b1d b600 6457 2ab4
    0000130: 0052 b600 682a b400 8bb6 006c 9eff d41d
    0000140: 2ab4 0094 b600 971d 1904 c000 1eb6 009a
    0000150: b0                                     
  Stackmap Table:
    same_frame(@11)
    same_frame(@36)
    same_frame(@52)
    same_locals_1_stack_item_frame(@60,Object[#30])
    same_locals_1_stack_item_frame(@94,Object[#30])
    same_frame(@145)
    same_frame_extended(@272)
    same_locals_1_stack_item_frame(@336,Object[#30])

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.constructNewInstance(Expression.java:1154)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1142)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:126)
	at arb4j/arb.functions.Function.express(Function.java:154)
	at arb4j/arb.functions.real.HypergeometricPolynomialSequence.<init>(HypergeometricPolynomialSequence.java:63)
	at arb4j/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
```

*WITH* COMPUTE_FRAMES

```Java
java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    F.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @197: invokevirtual
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @197
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { integer, 'arb/Real' }
  Bytecode:
    0000000: 2ab4 000e 9a00 072a b600 122a b400 162b
    0000010: c000 18b5 001d 2ab4 0021 b600 2757 2ab4
    0000020: 002a 2ab4 002d b600 3157 2ab4 0034 2ab4
    0000030: 0037 b600 3157 2ab4 0021 2ab4 0016 2ab4
    0000040: 002a 1d2a b400 3ab9 003d 0400 c000 231d
    0000050: b600 4157 2ab4 002a b600 452a b400 34b6
    0000060: 0049 9eff d42a b400 4d2b c000 18b5 004f
    0000070: 2ab4 0052 b600 2757 2ab4 002a 2ab4 002d
    0000080: b600 3157 2ab4 0055 2ab4 0058 b600 3157
    0000090: 2ab4 0052 2ab4 004d 2ab4 002a 1d2a b400
    00000a0: 5bb9 003d 0400 c000 231d b600 4157 2ab4
    00000b0: 002a b600 452a b400 55b6 0049 9eff d41d
    00000c0: 1904 c000 23b6 005f b0                 
  Stackmap Table:
    same_frame(@11)
    same_frame(@54)
    same_frame_extended(@144)

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.constructNewInstance(Expression.java:1154)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1142)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:126)
	at arb4j/arb.functions.Function.express(Function.java:154)
	at arb4j/arb.expressions.nodes.nary.ProductTest.testRatioOfProducts(ProductTest.java:59)
	at 
```

**Comment by crowlogic** [comment]
theres nothing on the stack for the Real.div invocation to consume in the output generated with compute_frames 

```java
       178: invokevirtual #69                 // Method arb/Integer.increment:()Larb/Integer;
       181: aload_0
       182: getfield      #85                 // Field endIndexℤ2:Larb/Integer;
       185: invokevirtual #73                 // Method arb/Integer.compareTo:(Larb/Integer;)I
       188: ifle          144
       191: iload_3
       192: aload         4
       194: checkcast     #35                 // class arb/Real
       197: invokevirtual #95                 // Method arb/Real.div:(Larb/Real;ILarb/Real;)Larb/Real;
       200: areturn
```
