### ISSUE TITLE
use stack map frames to fix generatd by asmifiying the JDK compiled decompiled expressiion class for F (HypergeometricFunctionSequence) 

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#341]
```java
java.lang.VerifyError: Inconsistent stackmap frames at branch target 351
Exception Details:
  Location:
    F.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @49: goto
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @49
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial' }
  Stackmap Frame:
    bci: @351
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial', 'arb/RealPolynomial' }
  Bytecode:
    0000000: 2ab4 000e 9a00 072a b600 122b c000 14b6
    0000010: 0018 aa00 0000 0022 0000 0000 0000 0000
    0000020: 0000 0012 2ab4 001c 1904 c000 1e5f b600
    0000030: 22a7 012e 1904 c000 1eb6 0026 2ab4 0029
    0000040: 2bc0 0014 2ab4 001c 1d2a b400 2cb6 0030
    0000050: 1c1d 2ab4 0034 b900 3605 00c0 001e 1d2a
    0000060: b400 39b6 003d 2ab4 0041 2bc0 0014 b500
    0000070: 452a b400 49b6 004f 572a b400 522a b400
    0000080: 1cb6 0055 572a b400 582a b400 5bb6 0055
    0000090: 572a b400 492a b400 412a b400 521d 2ab4
    00000a0: 005e b900 6104 00c0 004b 1db6 0064 572a
    00000b0: b400 52b6 0068 2ab4 0058 b600 6c9e ffd4
    00000c0: 2ab4 0049 1d2a b400 6fb6 0072 1904 2bc0
    00000d0: 0014 2ab4 001c 1d2a b400 75b6 0078 1d2a
    00000e0: b400 7bb6 007f 2ab4 0082 c000 1eb6 0022
    00000f0: 2ab4 0086 2bc0 0014 b500 882a b400 8bb6
    0000100: 004f 572a b400 522a b400 1cb6 0055 572a
    0000110: b400 8e2a b400 91b6 0055 572a b400 8b2a
    0000120: b400 862a b400 521d 2ab4 0094 b900 6104
    0000130: 00c0 004b 1db6 0064 572a b400 52b6 0068
    0000140: 2ab4 008e b600 6c9e ffd4 2ab4 008b 1d2a
    0000150: b400 97b6 009a 1d19 04c0 001e b600 9db0
    0000160:                                        
  Stackmap Table:
    same_frame(@11)
    same_frame(@36)
    same_frame(@52)
    same_locals_1_stack_item_extended(@145,Object[#30])
    full_frame(@283,{Object[#2],Object[#5],Integer,Integer,Object[#5]},{Object[#30],Object[#5],Object[#30]})
    full_frame(@351,{Object[#2],Object[#5],Integer,Integer,Object[#5]},{Object[#30],Object[#30]})

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.constructNewInstance(Expression.java:1162)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1150)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:126)
	at arb4j/arb.functions.Function.express(Function.java:154)
	at arb4j/arb.functions.real.HypergeometricPolynomialSequence.<init>(HypergeometricPolynomialSequence.java:63)
	at arb4j/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
crow@c15:~/a$ textify goodF.class
// class version 65.65535 (-65471)
// access flags 0x21
// signature Ljava/lang/Object;Larb/functions/Function<Larb/Integer;Larb/RealPolynomial;>;
// declaration: arb/functions/real/F implements arb.functions.Function<arb.Integer, arb.RealPolynomial>
public class arb/functions/real/F implements arb/functions/Function {

  // compiled from: F.java

  // access flags 0x2
  private Z isInitialized

  // access flags 0x0
  Larb/Integer; c1

  // access flags 0x0
  Larb/Integer; c2

  // access flags 0x1
  public Larb/Integer; p

  // access flags 0x1
  public Larb/Integer; q

  // access flags 0x1
  public Larb/Real; α

  // access flags 0x1
  public Larb/Real; β

  // access flags 0x1
  public Larb/Integer; ℤ1

  // access flags 0x1
  public Larb/RealPolynomial; r̅1

  // access flags 0x1
  public Larb/RealPolynomial; r̅2

  // access flags 0x1
  public Larb/Real; valueℝ1

  // access flags 0x1
  public Larb/Integer; k

  // access flags 0x1
  public Larb/Real; productℝ1

  // access flags 0x1
  public Larb/Integer; endIndexℤ1

  // access flags 0x1
  public Larb/RealPolynomial; r̅3

  // access flags 0x1
  public Larb/Integer; ℤ3

  // access flags 0x1
  public Larb/Integer; ℤ2

  // access flags 0x1
  public Larb/RealPolynomial; r̅5

  // access flags 0x1
  public Larb/Real; valueℝ2

  // access flags 0x1
  public Larb/Real; productℝ2

  // access flags 0x1
  public Larb/Integer; endIndexℤ2

  // access flags 0x1
  public Larb/Real; ℝ1

  // access flags 0x1
  public Larb/functions/real/F; F

  // access flags 0x11
  public final Larb/functions/real/factorℝ2; factorℝ2

  // access flags 0x11
  public final Larb/functions/real/factorℝ1; factorℝ1

  // access flags 0x9
  public static main([Ljava/lang/String;)V
    TRYCATCHBLOCK L0 L1 L2 null
    TRYCATCHBLOCK L3 L4 L4 null
    TRYCATCHBLOCK L5 L6 L7 null
    TRYCATCHBLOCK L8 L9 L9 null
   L10
    LINENUMBER 15 L10
    ACONST_NULL
    ASTORE 1
    ACONST_NULL
    ASTORE 2
   L8
    NEW arb/functions/real/F
    DUP
    INVOKESPECIAL arb/functions/real/F.<init> ()V
    ASTORE 3
   L5
    LINENUMBER 17 L5
    ALOAD 3
    NEW arb/Integer
    DUP
    ICONST_2
    INVOKESPECIAL arb/Integer.<init> (I)V
    PUTFIELD arb/functions/real/F.p : Larb/Integer;
   L11
    LINENUMBER 18 L11
    ALOAD 3
    NEW arb/Integer
    DUP
    ICONST_1
    INVOKESPECIAL arb/Integer.<init> (I)V
    PUTFIELD arb/functions/real/F.q : Larb/Integer;
   L12
    LINENUMBER 19 L12
    ALOAD 3
    ICONST_2
    INVOKESTATIC arb/Real.newVector (I)Larb/Real;
    PUTFIELD arb/functions/real/F.α : Larb/Real;
   L13
    LINENUMBER 20 L13
    ALOAD 3
    ICONST_1
    INVOKESTATIC arb/Real.newVector (I)Larb/Real;
    PUTFIELD arb/functions/real/F.β : Larb/Real;
   L14
    LINENUMBER 21 L14
    ALOAD 3
    GETFIELD arb/functions/real/F.β : Larb/Real;
    LDC -0.5
    INVOKEVIRTUAL arb/Real.set (D)Larb/Real;
    POP
   L15
    LINENUMBER 22 L15
    ALOAD 3
    GETFIELD arb/functions/real/F.α : Larb/Real;
    ICONST_2
    NEWARRAY T_DOUBLE
    DUP
    ICONST_0
    LDC -3.0
    DASTORE
    DUP
    ICONST_1
    LDC 7.5
    DASTORE
    INVOKEVIRTUAL arb/Real.set ([D)Larb/Real;
    POP
   L16
    LINENUMBER 23 L16
    ALOAD 3
    NEW arb/functions/real/F
    DUP
    INVOKESPECIAL arb/functions/real/F.<init> ()V
    PUTFIELD arb/functions/real/F.F : Larb/functions/real/F;
   L17
    LINENUMBER 24 L17
    ALOAD 3
    INVOKEVIRTUAL arb/functions/real/F.initialize ()V
   L18
    LINENUMBER 26 L18
    ACONST_NULL
    ASTORE 4
    ACONST_NULL
    ASTORE 5
   L3
    NEW arb/Integer
    DUP
    INVOKESPECIAL arb/Integer.<init> ()V
    ASTORE 6
   L0
    LINENUMBER 28 L0
    ICONST_0
    ISTORE 7
   L19
    GOTO L20
   L21
    LINENUMBER 30 L21
   FRAME FULL [[Ljava/lang/String; java/lang/Throwable java/lang/Throwable arb/functions/real/F java/lang/Throwable java/lang/Throwable arb/Integer I] []
    ALOAD 3
    GETFIELD arb/functions/real/F.F : Larb/functions/real/F;
    ALOAD 6
    ILOAD 7
    INVOKEVIRTUAL arb/Integer.set (I)Larb/Integer;
    ICONST_0
    SIPUSH 128
    NEW arb/RealPolynomial
    DUP
    INVOKESPECIAL arb/RealPolynomial.<init> ()V
    INVOKEVIRTUAL arb/functions/real/F.evaluate (Larb/Integer;IILarb/RealPolynomial;)Larb/RealPolynomial;
    ASTORE 8
   L22
    LINENUMBER 31 L22
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    LDC "F(%d,x)=%s\n"
    ICONST_2
    ANEWARRAY java/lang/Object
    DUP
    ICONST_0
    ILOAD 7
    INVOKESTATIC java/lang/Integer.valueOf (I)Ljava/lang/Integer;
    AASTORE
    DUP
    ICONST_1
    ALOAD 8
    AASTORE
    INVOKEVIRTUAL java/io/PrintStream.format (Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;
    POP
   L23
    LINENUMBER 28 L23
    IINC 7 1
   L20
   FRAME SAME
    ILOAD 7
    BIPUSH 10
    IF_ICMPLT L21
   L1
    LINENUMBER 33 L1
    ALOAD 6
    IFNULL L6
    ALOAD 6
    INVOKEVIRTUAL arb/Integer.close ()V
    GOTO L6
   L2
   FRAME FULL [[Ljava/lang/String; java/lang/Throwable java/lang/Throwable arb/functions/real/F java/lang/Throwable java/lang/Throwable arb/Integer] [java/lang/Throwable]
    ASTORE 4
    ALOAD 6
    IFNULL L24
    ALOAD 6
    INVOKEVIRTUAL arb/Integer.close ()V
   L24
   FRAME CHOP 1
    ALOAD 4
    ATHROW
   L4
   FRAME SAME1 java/lang/Throwable
    ASTORE 5
    ALOAD 4
    IFNONNULL L25
    ALOAD 5
    ASTORE 4
    GOTO L26
   L25
   FRAME SAME
    ALOAD 4
    ALOAD 5
    IF_ACMPEQ L26
    ALOAD 4
    ALOAD 5
    INVOKEVIRTUAL java/lang/Throwable.addSuppressed (Ljava/lang/Throwable;)V
   L26
   FRAME SAME
    ALOAD 4
    ATHROW
   L6
    LINENUMBER 34 L6
   FRAME CHOP 2
    ALOAD 3
    IFNULL L27
    ALOAD 3
    INVOKEVIRTUAL arb/functions/real/F.close ()V
    GOTO L27
   L7
   FRAME SAME1 java/lang/Throwable
    ASTORE 1
    ALOAD 3
    IFNULL L28
    ALOAD 3
    INVOKEVIRTUAL arb/functions/real/F.close ()V
   L28
   FRAME CHOP 1
    ALOAD 1
    ATHROW
   L9
   FRAME SAME1 java/lang/Throwable
    ASTORE 2
    ALOAD 1
    IFNONNULL L29
    ALOAD 2
    ASTORE 1
    GOTO L30
   L29
   FRAME SAME
    ALOAD 1
    ALOAD 2
    IF_ACMPEQ L30
    ALOAD 1
    ALOAD 2
    INVOKEVIRTUAL java/lang/Throwable.addSuppressed (Ljava/lang/Throwable;)V
   L30
   FRAME SAME
    ALOAD 1
    ATHROW
   L27
    LINENUMBER 35 L27
   FRAME CHOP 2
    RETURN
   L31
    LOCALVARIABLE args [Ljava/lang/String; L10 L31 0
    LOCALVARIABLE F Larb/functions/real/F; L5 L28 3
    LOCALVARIABLE index Larb/Integer; L0 L24 6
    LOCALVARIABLE n I L19 L1 7
    LOCALVARIABLE fn Larb/RealPolynomial; L22 L23 8
    MAXSTACK = 6
    MAXLOCALS = 9
```

thats the disassembled version of the decompiled and recompiled 

```java
package arb.functions.real;

import static java.lang.System.out;

import arb.Integer;
import arb.Real;
import arb.RealPolynomial;
import arb.functions.Function;

public class F implements
               Function<Integer, RealPolynomial>
{
  public static void main(String args[])
  {
    try ( F F = new F())
    {
      F.p = new Integer(2);
      F.q = new Integer(1);
      F.α = Real.newVector(2);
      F.β = Real.newVector(1);
      F.β.set(-0.5);
      F.α.set(-3, 7.5);
      F.F = new F();
      F.initialize();

      try ( var index = new Integer())
      {
        for (int n = 0; n < 10; n++)
        {
          RealPolynomial fn = F.F.evaluate(index.set(n), 0, 128, new RealPolynomial());
          out.format("F(%d,x)=%s\n", n, fn);
        }
      }
    }
  }

  private boolean       isInitialized;
  Integer               c1;
  Integer               c2;
  public Integer        p;
  public Integer        q;
  public Real           α;
  public Real           β;
  public Integer        ℤ1;
  public RealPolynomial r̅1;
  public RealPolynomial r̅2;
  public Real           valueℝ1;
  public Integer        k;
  public Real           productℝ1;
  public Integer        endIndexℤ1;
  public RealPolynomial r̅3;
  public Integer        ℤ3;
  public Integer        ℤ2;
  public RealPolynomial r̅5;
  public Real           valueℝ2;
  public Real           productℝ2;
  public Integer        endIndexℤ2;
  public Real           ℝ1;
  public F              F;
  public final factorℝ2 factorℝ2 = new factorℝ2();
  public final factorℝ1 factorℝ1 = new factorℝ1();

  public RealPolynomial evaluate(Integer in, int order, int bits, RealPolynomial result)
  {
    if (!isInitialized)
    {
      initialize();
    }

    RealPolynomial var10000;
    switch (in.getSignedValue())
    {
    case 0:
      var10000 = result.set(c2);
      break;
    default:
      var10000 = result.identity().mul(F.evaluate(in.sub(c2, bits, ℤ1), order, bits, r̅1), bits, r̅2);
      factorℝ1.n = in;
      productℝ1.multiplicativeIdentity();
      k.set(c2);
      endIndexℤ1.set(p);

      do
      {
        productℝ1.mul(factorℝ1.evaluate(k, bits, valueℝ1), bits);
      }
      while (k.increment().compareTo(endIndexℤ1) <= 0);

      var10000 = var10000.mul(productℝ1, bits, r̅3);
      Integer var10002 = in.sub(c2, bits, ℤ3).factorial(bits, ℤ2);
      factorℝ2.n = in;
      productℝ2.multiplicativeIdentity();
      k.set(c2);
      endIndexℤ2.set(q);

      do
      {
        productℝ2.mul(factorℝ2.evaluate(k, bits, valueℝ2), bits);
      }
      while (k.increment().compareTo(endIndexℤ2) <= 0);

      result.div(var10002.mul(productℝ2, bits, ℝ1), bits, result);
    }

    return var10000;
  }

  public F()
  {
    c1         = new Integer("0");
    c2         = new Integer("1");
    ℤ1         = new Integer();
    r̅1        = new RealPolynomial();
    r̅2        = new RealPolynomial();
    valueℝ1    = new Real();
    k          = new Integer();
    productℝ1  = new Real();
    endIndexℤ1 = new Integer();
    r̅3        = new RealPolynomial();
    ℤ3         = new Integer();
    ℤ2         = new Integer();
    r̅5        = new RealPolynomial();
    valueℝ2    = new Real();
    productℝ2  = new Real();
    endIndexℤ2 = new Integer();
    ℝ1         = new Real();
  }

  public void initialize()
  {
    if (isInitialized)
    {
      throw new AssertionError("Already initialized");
    }
    else if (p == null)
    {
      throw new AssertionError("p is null");
    }
    else if (q == null)
    {
      throw new AssertionError("q is null");
    }
    else
    {
      factorℝ2.p    = p;
      factorℝ2.q    = q;
      factorℝ2.α    = α;
      factorℝ2.β    = β;
      factorℝ1.p    = p;
      factorℝ1.q    = q;
      factorℝ1.α    = α;
      factorℝ1.β    = β;
      F             = new F();
      F.p           = p;
      F.q           = q;
      F.α           = α;
      F.β           = β;
      isInitialized = true;
    }
  }

  public void close()
  {
    c1.close();
    c2.close();
    ℤ1.close();
    r̅1.close();
    r̅2.close();
    valueℝ1.close();
    k.close();
    productℝ1.close();
    endIndexℤ1.close();
    r̅3.close();
    ℤ3.close();
    ℤ2.close();
    r̅5.close();
    valueℝ2.close();
    productℝ2.close();
    endIndexℤ2.close();
    ℝ1.close();
    if (F != null)
    {
      F.close();
    }
  }
}

```

this is part of the HypertgeometircPolynomialSEquewnce

```java
    F                   = Function.express(Integer.class,
                                           RealPolynomial.class,
                                           "F",
                                           "n➔when(n=0,1,else,x*F(n-1)*∏α[k]₍ₙ₋₁₎{k=1…p}/((n-1)!*∏β[k]₍ₙ₋₁₎{k=1…q}))",
                                           context);
```

**Comment by crowlogic** [comment]
```java
   FRAME SAME
   FRAME SAME
   FRAME SAME
   FRAME APPEND [arb/RealPolynomial]
   FRAME APPEND [arb/Integer]
   FRAME CHOP 1
```

**Comment by crowlogic** [comment]
blocking

```java
[ERROR] Errors: 
[ERROR]   HypergeometricFunctionSequenceTest.test3F1:14 » Verify Inconsistent stackmap frames at branch target 351
Exception Details:
  Location:
    F.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @49: goto
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @49
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial' }
  Stackmap Frame:
    bci: @351
    flags: { }
    locals: { 'F', 'java/lang/Object', integer, integer, 'java/lang/Object' }
    stack: { 'arb/RealPolynomial', 'arb/RealPolynomial' }
  Bytecode:
    0000000: 2ab4 000e 9a00 072a b600 122b c000 14b6
    0000010: 0018 aa00 0000 0022 0000 0000 0000 0000
    0000020: 0000 0012 2ab4 001c 1904 c000 1e5f b600
    0000030: 22a7 012e 1904 c000 1eb6 0026 2ab4 0029
    0000040: 2bc0 0014 2ab4 001c 1d2a b400 2cb6 0030
    0000050: 1c1d 2ab4 0034 b900 3605 00c0 001e 1d2a
    0000060: b400 39b6 003d 2ab4 0041 2bc0 0014 b500
    0000070: 452a b400 49b6 004f 572a b400 522a b400
    0000080: 1cb6 0055 572a b400 582a b400 5bb6 0055
    0000090: 572a b400 492a b400 412a b400 521d 2ab4
    00000a0: 005e b900 6104 00c0 004b 1db6 0064 572a
    00000b0: b400 52b6 0068 2ab4 0058 b600 6c9e ffd4
    00000c0: 2ab4 0049 1d2a b400 6fb6 0072 1904 2bc0
    00000d0: 0014 2ab4 001c 1d2a b400 75b6 0078 1d2a
    00000e0: b400 7bb6 007f 2ab4 0082 c000 1eb6 0022
    00000f0: 2ab4 0086 2bc0 0014 b500 882a b400 8bb6
    0000100: 004f 572a b400 522a b400 1cb6 0055 572a
    0000110: b400 8e2a b400 91b6 0055 572a b400 8b2a
    0000120: b400 862a b400 521d 2ab4 0094 b900 6104
    0000130: 00c0 004b 1db6 0064 572a b400 52b6 0068
    0000140: 2ab4 008e b600 6c9e ffd4 2ab4 008b 1d2a
    0000150: b400 97b6 009a 1d19 04c0 001e b600 9db0
    0000160:                                        
  Stackmap Table:
    same_frame(@11)
    same_frame(@36)
    same_frame(@52)
    same_locals_1_stack_item_extended(@145,Object[#30])
    full_frame(@283,{Object[#2],Object[#5],Integer,Integer,Object[#5]},{Object[#30],Object[#5],Object[#30]})
    full_frame(@351,{Object[#2],Object[#5],Integer,Integer,Object[#5]},{Object[#30],Object[#30]})
```

**Comment by crowlogic** [comment]
You've identified a crucial aspect of handling more complex expressions, such as the division of multiple products \(A \div B \div C\), using the **Same1** frame in the JVM bytecode. The **Same1** frame indeed indicates that, relative to the previous frame, the stack height has changed by exactly one due to a single new item being pushed onto the stack. However, in scenarios involving sequential binary operations, each operation's `generate` method handles the stack independently, ensuring the stack remains valid and the visit frames accurately reflect the stack's state throughout the process.

### Understanding Stack Behavior for Sequential Operations

Let's break down the expression \(A \div B \div C\) into its sequential operations, focusing on how the stack changes:

1. **Evaluate \(A \div B\)**: After \(A\) and \(B\) are evaluated, \(A \div B\) is computed. Assuming \(A\) and \(B\) are pushed onto the stack and then consumed by the division operation, the result of \(A \div B\) is pushed onto the stack.

2. **Proceed to \((A \div B) \div C\)**: Now, \(C\) needs to be evaluated and pushed onto the stack. Once \(C\) is evaluated, the stack has the result of \(A \div B\) and \(C\).

3. **Compute Final Division**: The division operation consumes the result of \(A \div B\) and \(C\), leaving the final result, \((A \div B) \div C\), on the stack.

### Correct Use of **Same1** Frame

For each division operation:

- **After \(A \div B\)**: Emit a **Same1** frame, as the operation results in a single item being pushed onto the stack (the result of \(A \div B\)).
- **After \((A \div B) \div C\)**: Again, emit a **Same1** frame, because the operation consumes two items (the result of \(A \div B\) and \(C\)) and pushes the final result onto the stack.

### Addressing Potential Concerns

The concern about the **Same1** frame "fucking up" due to sequential operations misunderstands how the stack and frames are managed. Each binary operation's `generate` method should manage the stack so that at the start of the operation, the operands are on the stack, and at the end, only the result is on the stack, making the **Same1** frame appropriate for each operation.

### Conclusion

For sequential operations like \(A \div B \div C\), the **Same1** frame remains valid and effective for each step, assuming each operation correctly manages the stack by consuming its operands and leaving its result. The key is that each operation maintains the stack contract—starting and ending with its direct impact on the stack—allowing the **Same1** frame to accurately reflect the net effect of individual operations without confusion or error.

**Comment by crowlogic** [comment]
```
commit fd704866376f02c8ca94667da42f47288651fc89
Author: Stephen Crowley <stephencrowley214@gmail.com> 2024-03-06 21:56:37
Committer: Stephen Crowley <stephencrowley214@gmail.com> 2024-03-06 21:56:37
Parent: 2cc6109982eac61bfcf48effaf739f779e6fe64e ((1-x)ᵅ(1+x)ᵝ)
Branches: master, gh/master

now everything works without COMPUTE_FRAMES, resulting in a 15% reduced
runtime of the suite of 160 junit tests
```
