### ISSUE TITLE
expr compiler: variable incorrectly declaring n to be the indeterminant of the polynomial result

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#369]
```java
resolveReference(reference=n)
Checking if n is the indeterminant variable in a polynomial expression
Declaring n to be the indeterminant of Expression[expression=k➔β[k]₍ₙ₎,
                      className=factorℝ2,
                      functionName=factorℝ2, recursive=false, functionClass=interface arb.functions.Function] + from 
BinaryOperat
```

```java
java.lang.ClassCastException: class arb.Real cannot be cast to class arb.RealPolynomial (arb.Real and arb.RealPolynomial are in module arb4j of loader 'app')
	at factorℝ1.evaluate(Unknown Source)
	at arb4j/arb.functions.Function.evaluate(Function.java:201)
	at factorP1.evaluate(Unknown Source)
	at arb4j/arb.functions.Function.evaluate(Function.java:201)
	at F.evaluate(Unknown Source)
	at arb4j/arb.functions.polynomials.HypergeometricPolynomial.evaluate(HypergeometricPolynomial.java:73)
	at arb4j/arb.functions.polynomials.HypergeometricPolynomial.evaluate(HypergeometricPolynomial.java:1)
	at arb4j/arb.functions.Function.evaluate(Function.java:201)
	at arb4j/arb.functions.polynomials.HypergeometricPolynomialTest.testSum(HypergeometricPolynomialTest.java:78)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
Woop. fixed in https://github.com/crowlogic/arb4j/commit/3c956ea33c91ea75ee6148752e5a7071c7caaf18

stackexchange sucks its overran by pedantic neckbeards from hell
