### ISSUE TITLE
support higher-order Bessel functions

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#374]
```java
[crow@c15 20240329-07:15:48PM]~$ arbshell
jshell> var f = express("tanh(log(1+J1(x)^2))");
jshell> plot(-10,40,2000,f);
jshell> Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: 'arb.Real arb.Real.J1(int, arb.Real)'
	at tanhlog1PlusJ1xTo2.evaluate(Unknown Source)
	at arb4j@0.90/arb.functions.real.RealFunction.lambda$quantize$0(RealFunction.java:243)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
	at arb4j@0.90/arb.functions.real.RealFunction.quantize(RealFunction.java:243)
	at arb4j@0.90/arb.functions.real.RealFunction.quantize(RealFunction.java:190)
	at arb4j@0.90/arb.functions.real.RealFunction.quantize(RealFunction.java:156)
	at arb4j@0.90/arb.utensils.ShellFunctions.lambda$plot$3(ShellFunctions.java:122)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@21.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@21.0.2/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
	at java.base/java.lang.Thread.run(Thread.java:1583)


```

**Comment by crowlogic** [comment]
will do it l8r its not necessary atm
