### ISSUE TITLE
half-integer order Bessel functions with rational Lommel/Bessel function result

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#429]
```java
java.lang.AssertionError: check that the order is a half-integer and evaluate the result in terms of lommel or bessel polynomials
	at arb4j/arb.expressions.nodes.unary.BesselFunctionOfTheFirstKind.generate(BesselFunctionOfTheFirstKind.java:92)
	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:267)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:927)
	at arb4j/arb.expressions.Expression.generate(Expression.java:750)
	at arb4j/arb.expressions.Expression.defineClass(Expression.java:528)
	at arb4j/arb.expressions.Expression.getInstance(Expression.java:1221)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1345)
	at arb4j/arb.RealQuasiPolynomialTest.testQuasiPolynomialSequence(RealQuasiPolynomialTest.java:66)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
[crow@c17 20240803-05:52:40AM]~/a$ cat scripts/rationalLommel.arb 
var context = new Context();
context.registerVariable("v",RealConstants.half);
var R = RationalFunctionSequence.express("v₍ₙ₎*(z/2)^(-n)*pFq([1/2-n/2,-n/2],[v,-n,1-v-n],-z^2)",context);
R
var x = R.evaluate(3,128);[crow@c17 20240803-05:52:43AM]~/a$ cat scripts/rationalLommel.arb 
var context = new Context();
context.registerVariable("v",RealConstants.half);
var R = RationalFunctionSequence.express("v₍ₙ₎*(z/2)^(-n)*pFq([1/2-n/2,-n/2],[v,-n,1-v-n],-z^2)",context);
R
var x = R.evaluate(3,128);[crow@c17 20240803-05:53:37AM]~/a$ arbshell
jshell> /open scripts/rationalLommel.arb
|  Exception java.lang.NoSuchMethodError: 'arb.RationalFunction arb.Real.mul(arb.RationalFunction, int, arb.RationalFunction)'
|        at vNTimes(zOver2)ToThePowerOf(Minusn)TimespFq({1Over2MinusnOver2,MinusnOver2},{v,Minusn,1MinusvMinusn},MinuszToThePowerOf2).evaluate (Unknown Source)
|        at Function.evaluate (Function.java:299)
|        at Function.evaluate (Function.java:289)
|        at Sequence.evaluate (Sequence.java:51)
|        at do_it$Aux (#5:1)
|        at (#5:1)
```

**Comment by crowlogic** [comment]
```java
arb.exceptions.ArbException: at least one of the upper parameters must be a non-negative integer but there is none among [1.5, 1.5]
	at arb4j/arb.functions.real.RationalHypergeometricFunction.initialize(RationalHypergeometricFunction.java:176)
	at arb4j/arb.functions.real.RationalHypergeometricFunction.evaluate(RationalHypergeometricFunction.java:164)
	at vNTimes(zOver2)ToThePowerOf(Minusn)TimespFq({1Over2MinusnOver2,MinusnOver2},{v,Minusn,1MinusvMinusn},Minusz²).evaluate(Unknown Source)
	at arb4j/arb.functions.Function.evaluate(Function.java:334)
	at arb4j/arb.functions.sequences.Sequence.evaluate(Sequence.java:63)
	at arb4j/arb.RationalFunctionTest.testLommelPolynomials(RationalFunctionTest.java:27)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```


```java
ackage arb.functions.real;

import arb.*;
import arb.Integer;
import arb.expressions.Expression;
import arb.functions.sequences.RationalFunctionSequence;

public class vNTimes implements RationalFunctionSequence, Typesettable, AutoCloseable, Initializable
{
  public static void main(String args[])
  {
    vNTimes vnTimes = new vNTimes();
    vnTimes.v = RealConstants.half;

    RationalFunction val = vnTimes.evaluate(3, 128);
    System.out.println("val=" + val);
  }

  public boolean          isInitialized;
  Integer                 cℤ2 = new Integer("1");
  Integer                 cℤ1 = new Integer("2");
  public Real             v;
  public Fraction         vf1 = new Fraction();
  public Fraction         vf2 = new Fraction();
  public Integer          ℤ1  = new Integer();
  public Fraction         f1  = new Fraction();
  public Fraction         f2  = new Fraction();
  public Fraction         f3  = new Fraction();
  public Fraction         f4  = new Fraction();
  public Fraction         f5  = new Fraction();
  public Real             ℝ1  = new Real();
  public Fraction         f6  = new Fraction();
  public Fraction         f7  = new Fraction();
  public Real             ℝ2  = new Real();
  public Fraction         f8  = new Fraction();
  public RationalFunction fℝ4 = new RationalFunction();
  public RationalFunction fℝ3 = new RationalFunction();
  public RationalFunction fℝ5 = new RationalFunction();
  public RationalFunction fℝ2 = new RationalFunction();
  public RationalFunction fℝ1 = new RationalFunction();

  @Override
  public Class<RationalFunction> coDomainType()
  {
    return RationalFunction.class;
  }

  @Override
  public RationalFunction evaluate(Integer n, int order, int bits, RationalFunction result)
  {
    if (!isInitialized)
    {
      initialize();
    }

    Fraction topLeft = cℤ2.div(cℤ1, bits, f1).sub(n.div(cℤ1, bits, f2), bits, f3);
    Fraction topRight = n.div(cℤ1, bits, f4).neg(f5);
    Fraction numerator   = vf1.set(topLeft,
                                   topRight);
    Fraction denominator = vf2.set(f6.set(v), n.neg(f7), cℤ2.sub(v, bits, ℝ2).sub(n, bits, f8));
    System.out.format("topLeft=%s\ntopRight=%s\nnumerator=%s\ndenominator=%s\n", numerator, denominator, topLeft, topRight );
    
    var      arg         = RationalNullaryFunction.parse("-z^2");
    var      f           = new RationalHypergeometricFunction(numerator,
                                                              denominator,
                                                              arg);
    return v.ascendingFactorial(n, bits, ℝ1)
            .mul(fℝ1.identity().div(cℤ1, bits, fℝ2).pow(n.neg(ℤ1), bits, fℝ3), bits, fℝ4)
            .mul(f.evaluate(null, 1, bits, fℝ5), bits, result);
  }

  @Override
  public void initialize()
  {
    if (isInitialized)
    {
      throw new AssertionError("Already initialized");
    }
    else if (v == null)
    {
      throw new AssertionError("v shan't be null");
    }
    else
    {
      isInitialized = true;
    }
  }

  @Override
  public void close()
  {
    cℤ2.close();
    cℤ1.close();
    vf1.close();
    vf2.close();
    ℤ1.close();
    f1.close();
    f2.close();
    f3.close();
    f4.close();
    f5.close();
    ℝ1.close();
    f6.close();
    f7.close();
    ℝ2.close();
    f8.close();
    fℝ4.close();
    fℝ3.close();
    fℝ5.close();
    fℝ2.close();
    fℝ1.close();
  }

  @Override
  public String toString()
  {
    return "n➔v₍ₙ₎*(z/2)^(-n)*pFq([1/2-n/2,-n/2],[v,-n,1-v-n],-z^2)";
  }

  @Override
  public String typeset()
  {
    return "\\left(\\left((v)_{n} \\cdot (\\frac{z}{2})^{(-n)}\\right) \\cdot ${_2F_3}\\left(\\left[\\left(\\frac{1}{2}-\\frac{n}{2}\\right),-\\frac{n}{2}\\right], \\left[v,-n,\\left(\\left(1-v\\right)-n\\right)\\right] ; -(z)^{(2)}\\right)\\right)";
  }
}
```

```java
topLeft=[[3/2, 0/0], 3/2]
topRight=[1/2, -3, -5/2]
numerator=[3/2, 0/0]
denominator=3/2
Exception in thread "main" arb.exceptions.ArbException: at least one of the upper parameters must be a non-negative integer but there is none among [1.5, 1.5]
	at arb4j/arb.functions.real.RationalHypergeometricFunction.initialize(RationalHypergeometricFunction.java:176)
	at arb4j/arb.functions.real.RationalHypergeometricFunction.evaluate(RationalHypergeometricFunction.java:164)
	at arb4j/arb.functions.real.vNTimes.evaluate(vNTimes.java:71)
	at arb4j/arb.functions.real.vNTimes.evaluate(vNTimes.java:1)
	at arb4j/arb.functions.Function.evaluate(Function.java:299)
	at arb4j/arb.functions.Function.evaluate(Function.java:289)
	at arb4j/arb.functions.sequences.Sequence.evaluate(Sequence.java:51)
	at arb4j/arb.functions.real.vNTimes.main(vNTimes.java:14)
```

**Comment by crowlogic** [comment]
I understand, and you're right. This situation highlights an important aspect of developing mathematical libraries, especially when dealing with multiple precision types. Let's break this down:

1. The existence of two versions (with and without bits) is a common pattern in arbitrary-precision arithmetic libraries to handle both exact and approximated computations.

2. Your point about the compiler emitting code to not specify bits when not needed is an excellent optimization goal. Until that's implemented, we need to be extra careful with method overloading and ensure both versions behave correctly.

To address this issue and prevent similar problems in the future, consider the following steps:

1. Audit all similar methods (like add, sub, mul, div) to ensure they're consistently implemented in both their "with bits" and "without bits" versions.

2. Implement a comprehensive test suite that covers both versions of each operation. This should include:
   - Basic operation tests
   - Edge cases (like negation of zero, extreme values)
   - Consistency checks between "with bits" and "without bits" versions

3. Consider implementing a static analysis tool or custom lint rules to catch inconsistencies between paired methods.

4. Document clearly which operations require bit precision and which don't, to help prevent misuse.

5. In the longer term, look into ways to unify the API or use a type system that can distinguish between exact and approximate types at compile time.

6. For critical operations like negation, consider adding runtime assertions in debug builds to verify correctness.

Thank you for bringing this to light. It's a valuable lesson in library design and the importance of thorough testing, especially in mathematical software where subtle bugs can have significant impacts.
