### ISSUE TITLE
fix expression of hypergeometric functions as RationalFunctions

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#452]
```java
import arb.Fraction;
import arb.Initializable;
import arb.Integer;
import arb.RationalFunction;
import arb.RationalNullaryFunction;
import arb.Real;
import arb.Typesettable;
import arb.functions.complex.ComplexPolynomialNullaryFunction;

public class pFq({Minus2,3_5,1},{2,4},1Over2MinusxOver2) implements RationalNullaryFunction, Typesettable, AutoCloseable, Initializable {
   public boolean isInitialized;
   Integer cℤ1 = new Integer("2");
   Integer cℤ4 = new Integer("4");
   Integer cℤ3 = new Integer("1");
   Real cℝ2 = new Real("3.5", 128);
   public Fraction vf1 = new Fraction();
   public Fraction vf2 = new Fraction();
   public Fraction f1 = new Fraction();
   public Fraction f2 = new Fraction();
   public Fraction f3 = new Fraction();
   public Fraction f4 = new Fraction();
   public Fraction f5 = new Fraction();

   @Override
   public Class<RationalFunction> coDomainType() {
      return RationalFunction.class;
   }

   @Override
   public RationalFunction evaluate(Object in, int order, int bits, RationalFunction result) {
      if (!this.isInitialized) {
         this.initialize();
      }

      return new Object(
            this.vf1.set(new Fraction[]{this.cℤ1.neg(this.f1), this.f2.set(this.cℝ2), this.f3.set(this.cℤ3)}),
            this.vf2.set(new Fraction[]{this.f4.set(this.cℤ1), this.f5.set(this.cℤ4)}),
            ComplexPolynomialNullaryFunction.parse("(1/2)-(x/2)")
         )
         .evaluate(null, 1, bits, result);
   }

   @Override
   public void initialize() {
      if (this.isInitialized) {
         throw new AssertionError("Already initialized");
      } else {
         this.isInitialized = true;
      }
   }

   @Override
   public void close() {
      this.cℤ1.close();
      this.cℤ4.close();
      this.cℤ3.close();
      this.cℝ2.close();
      this.vf1.close();
      this.vf2.close();
      this.f1.close();
      this.f2.close();
      this.f3.close();
      this.f4.close();
      this.f5.close();
   }

   @Override
   public String toString() {
      return "pFq([-2,3.5,1],[2,4],1/2-x/2)";
   }

   @Override
   public String typeset() {
      return "${_3F_2}\\left(\\left[-2,3.5,1\\right], \\left[2,4\\right] ; \\left(\\frac{1}{2}-\\frac{x}{2}\\right)\\right)";
   }
}
```

**Comment by crowlogic** [comment]
its getting there..

```java
import arb.Fraction;
import arb.Initializable;
import arb.Integer;
import arb.RationalFunction;
import arb.RationalNullaryFunction;
import arb.Real;
import arb.Typesettable;
import arb.functions.complex.ComplexPolynomialNullaryFunction;
import arb.functions.real.RationalHypergeometricFunction;

public class pFq({Minus2,3_5,1},{2,4},1Over2MinusxOver2) implements RationalNullaryFunction, Typesettable, AutoCloseable, Initializable {
   public boolean isInitialized;
   Integer cℤ1 = new Integer("2");
   Integer cℤ4 = new Integer("4");
   Integer cℤ3 = new Integer("1");
   Real cℝ2 = new Real("3.5", 128);
   public Fraction vf1 = new Fraction();
   public Fraction vf2 = new Fraction();
   public Fraction f1 = new Fraction();
   public Fraction f2 = new Fraction();
   public Fraction f3 = new Fraction();
   public Fraction f4 = new Fraction();
   public Fraction f5 = new Fraction();

   @Override
   public Class<RationalFunction> coDomainType() {
      return RationalFunction.class;
   }

   @Override
   public RationalFunction evaluate(Object in, int order, int bits, RationalFunction result) {
      if (!this.isInitialized) {
         this.initialize();
      }

      return new RationalHypergeometricFunction(
            this.vf1.set(new Fraction[]{this.cℤ1.neg(this.f1), this.f2.set(this.cℝ2), this.f3.set(this.cℤ3)}),
            this.vf2.set(new Fraction[]{this.f4.set(this.cℤ1), this.f5.set(this.cℤ4)}),
            ComplexPolynomialNullaryFunction.parse("(1/2)-(x/2)")
         )
         .evaluate(null, 1, bits, result);
   }

   @Override
   public void initialize() {
      if (this.isInitialized) {
         throw new AssertionError("Already initialized");
      } else {
         this.isInitialized = true;
      }
   }

   @Override
   public void close() {
      this.cℤ1.close();
      this.cℤ4.close();
      this.cℤ3.close();
      this.cℝ2.close();
      this.vf1.close();
      this.vf2.close();
      this.f1.close();
      this.f2.close();
      this.f3.close();
      this.f4.close();
      this.f5.close();
   }

   @Override
   public String toString() {
      return "pFq([-2,3.5,1],[2,4],1/2-x/2)";
   }

   @Override
   public String typeset() {
      return "${_3F_2}\\left(\\left[-2,3.5,1\\right], \\left[2,4\\right] ; \\left(\\frac{1}{2}-\\frac{x}{2}\\right)\\right)";
   }
}
```

**Comment by crowlogic** [comment]
fixed...

```java
import arb.Fraction;
import arb.Initializable;
import arb.Integer;
import arb.RationalFunction;
import arb.RationalNullaryFunction;
import arb.Real;
import arb.Typesettable;
import arb.functions.real.RationalHypergeometricFunction;

public class pFq({Minus2,3_5,1},{2,4},1Over2MinusxOver2) implements RationalNullaryFunction, Typesettable, AutoCloseable, Initializable {
   public boolean isInitialized;
   Integer cℤ1 = new Integer("2");
   Integer cℤ4 = new Integer("4");
   Integer cℤ3 = new Integer("1");
   Real cℝ2 = new Real("3.5", 128);
   public Fraction vf1 = new Fraction();
   public Fraction vf2 = new Fraction();
   public Fraction f1 = new Fraction();
   public Fraction f2 = new Fraction();
   public Fraction f3 = new Fraction();
   public Fraction f4 = new Fraction();
   public Fraction f5 = new Fraction();

   @Override
   public Class<RationalFunction> coDomainType() {
      return RationalFunction.class;
   }

   @Override
   public RationalFunction evaluate(Object in, int order, int bits, RationalFunction result) {
      if (!this.isInitialized) {
         this.initialize();
      }

      return new RationalHypergeometricFunction(
            this.vf1.set(new Fraction[]{this.cℤ1.neg(this.f1), this.f2.set(this.cℝ2), this.f3.set(this.cℤ3)}),
            this.vf2.set(new Fraction[]{this.f4.set(this.cℤ1), this.f5.set(this.cℤ4)}),
            arb.functions.real.RationalNullaryFunction.parse("(1/2)-(x/2)")
         )
         .evaluate(null, 1, bits, result);
   }

   @Override
   public void initialize() {
      if (this.isInitialized) {
         throw new AssertionError("Already initialized");
      } else {
         this.isInitialized = true;
      }
   }

   @Override
   public void close() {
      this.cℤ1.close();
      this.cℤ4.close();
      this.cℤ3.close();
      this.cℝ2.close();
      this.vf1.close();
      this.vf2.close();
      this.f1.close();
      this.f2.close();
      this.f3.close();
      this.f4.close();
      this.f5.close();
   }

   @Override
   public String toString() {
      return "pFq([-2,3.5,1],[2,4],1/2-x/2)";
   }

   @Override
   public String typeset() {
      return "${_3F_2}\\left(\\left[-2,3.5,1\\right], \\left[2,4\\right] ; \\left(\\frac{1}{2}-\\frac{x}{2}\\right)\\right)";
   }
}
```

**Comment by crowlogic** [comment]
now that that part is squared away

```java
java.lang.NoSuchMethodError: 'arb.RationalFunction arb.Fraction.ascendingFactorial(arb.Integer, int, arb.RationalFunction)'
	at factorfℝ2.evaluate(Unknown Source)
	at arb4j/arb.functions.Function.evaluate(Function.java:334)
	at factorfℝ1.evaluate(Unknown Source)
	at arb4j/arb.functions.Function.evaluate(Function.java:334)
	at F.evaluate(Unknown Source)
	at arb4j/arb.functions.real.RationalHypergeometricFunction.evaluate(RationalHypergeometricFunction.java:167)
	at pFq({Minus2,3_5,1},{2,4},1Over2MinusxOver2).evaluate(Unknown Source)
	at arb4j/arb.functions.NullaryFunction.evaluate(NullaryFunction.java:49)
	at arb4j/arb.expressions.nodes.unary.HypergeometricFunctionTest.testHypergeometricFunctionExpressionRational(HypergeometricFunctionTest.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
```java
java.lang.NoSuchMethodError: 'arb.RationalFunction arb.RationalFunction.mul(arb.RationalFunction, int)'
	at factorfℝ1.evaluate(Unknown Source)
	at arb4j/arb.functions.Function.evaluate(Function.java:334)
	at F.evaluate(Unknown Source)
	at arb4j/arb.functions.real.RationalHypergeometricFunction.evaluate(RationalHypergeometricFunction.java:167)
	at pFq({Minus2,3_5,1},{2,4},1Over2MinusxOver2).evaluate(Unknown Source)
	at arb4j/arb.functions.NullaryFunction.evaluate(NullaryFunction.java:49)
	at arb4j/arb.expressions.nodes.unary.HypergeometricFunctionTest.testHypergeometricFunctionExpressionRational(HypergeometricFunctionTest.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
Thank you for providing the `factorfℝ1` class. This is indeed the main implementation of the hypergeometric function term calculation. Let's analyze the `evaluate` method to identify the issue:

1. The argument calculation:
   ```java
   cℤ1.div(cℤ2, bits, f1)
      .sub(fℝ1.identity().div(cℤ2, bits, fℝ2), bits, fℝ3)
      .pow(n, bits, fℝ4);
   ```
   This is correctly calculating (1/2 - x/2)^n.

2. The numerator product:
   ```java
   prodfℝ1.multiplicativeIdentity();
   while (var10001.compareTo(endIndexℤ2) <= 0)
   {
     prodfℝ1.mul(factorfℝ2.evaluate(k, bits, valuefℝ2), bits);
     var10001 = k.increment();
   }
   ```
   This is correctly calculating the product of (α_k)_n for k from 1 to p.

3. The denominator calculation:
   ```java
   var10001 = n.factorial(bits, ℤ1);
   factorfℝ3.n = n;
   prodfℝ2.multiplicativeIdentity();
   while (var10002.compareTo(endIndexℤ3) <= 0)
   {
     prodfℝ2.mul(factorfℝ3.evaluate(k, bits, valuefℝ3), bits);
     var10002 = k.increment();
   }
   RationalFunction denom = var10001.mul(prodfℝ2, bits, fℝ6);
   ```
   This is correctly calculating n! * product of (β_k)_n for k from 1 to q.

4. The final division:
   ```java
   return var10000.div(denom, bits, result);
   ```
   This is correctly dividing the numerator by the denominator.

The implementation looks correct. The issue must be in how the rational functions are being represented or simplified. The problem is likely in the `RationalFunction` class itself, particularly in how it handles multiplication, division, and simplification.

To debug this:

1. Add more detailed logging in the `RationalFunction` class, especially in the `mul`, `div`, and any simplification methods.

2. In the `evaluate` method of `factorfℝ1`, print out the intermediate results:
   - Print `fℝ4` after calculating the argument term.
   - Print `prodfℝ1` after the numerator product loop.
   - Print `var10001` (n!) and `prodfℝ2` after the denominator calculation.

3. Check if there's any unintended simplification happening in the `RationalFunction` class that might be introducing the x in the denominator.

4. Verify that the `ascendingFactorial` method in both `factorfℝ2` and `factorfℝ3` is implemented correctly.

The core logic of the hypergeometric function calculation appears to be correct. The issue is likely in how the rational functions are being manipulated or represented. We need to ensure that no unintended simplifications or transformations are occurring that could introduce the x in the denominator or alter the coefficients.
