### ISSUE TITLE
HypergeometricFunctionTest.testHypergeometricFunctionExpressionRational: junit.framework.ComparisonFailure: expected:<[201/320+49/160*x+21/320*x^2]> but was:<[(-x^3+5*x^2-11*x+15)/8]>

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#454]
```java
junit.framework.ComparisonFailure: expected:<[201/320+49/160*x+21/320*x^2]> but was:<[(-x^3+5*x^2-11*x+15)/8]>
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:100)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:107)
	at junit@4.13.2/junit.framework.TestCase.assertEquals(TestCase.java:260)
	at arb4j/arb.expressions.nodes.unary.HypergeometricFunctionTest.testHypergeometricFunctionExpressionRational(HypergeometricFunctionTest.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
the problem mentioned in the last comment wasnt the problem, it was fixed yet the issue persists

**Comment by crowlogic** [comment]
segfault
```java
Stack: [0x0000778e7f700000,0x0000778e7f800000],  sp=0x0000778e7f7fdbe0,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libflint.so.20+0x2ab43d]  fmpz_poly_set_fmpz+0xd
j  arb.arblib.fmpz_poly_set_fmpz(Larb/IntegerPolynomial;J)V+6 arb4j
j  arb.IntegerPolynomial.set(Larb/Integer;)Larb/IntegerPolynomial;+5 arb4j
j  arb.RationalFunction.set(Larb/Fraction;)Larb/RationalFunction;+8 arb4j
j  arb.Fraction.pow(Larb/Integer;ILarb/RationalFunction;)Larb/RationalFunction;+2 arb4j
j  ((1Over2)Minus(zOver2))ToThePowerOfn.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object;+61
j  arb.functions.Function.evaluate(Ljava/lang/Object;ILjava/lang/Object;)Ljava/lang/Object;+5 arb4j
j  arb.RationalFunctionTest.testPowers()V+53 arb4j
```
