### ISSUE TITLE
integer expressions can have square roots as intermediate variables but not as the codomain (the ultimate value expressed by tbe function)

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#477]
java.lang.NoSuchMethodError: 'arb.Integer arb.Fraction.sqrt(int, arb.Integer)'
	at ⌊100Over√(1⁄2)⌋.evaluate(Unknown Source)
	at arb4j/arb.functions.NullaryFunction.evaluate(NullaryFunction.java:88)
	at arb4j/arb.functions.IntegerNullaryFunction.evaluate(IntegerNullaryFunction.java:33)
	at arb4j/arb.expressions.ExpressionTest.testSquareRootOfOneHalf(ExpressionTest.java:39)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by crowlogic** [comment]
```java
"main" #1 prio=5 tid=0x00007a202c02d800 nid=56080 runnable [0x00007a20351fe000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_in_native
 - arb.arblibJNI.arb_sqrt(long, arb.Real, long, arb.Real, int) @bci=0 (Interpreted frame)
 - arb.arblib.arb_sqrt(arb.Real, arb.Real, int) @bci=11, line=2342 (Interpreted frame)
 - arb.Real.sqrt(int, arb.Real) @bci=3, line=1448 (Interpreted frame)
 - arb.Fraction.sqrt(int, arb.Real) @bci=7, line=73 (Interpreted frame)
 - arb.functions.FloorOfOneHundedOverTheSquareRootOfOneHalf.evaluate(java.lang.Object, int, int, arb.Integer) @bci=36, line=43 (Interpreted frame)
 - arb.functions.FloorOfOneHundedOverTheSquareRootOfOneHalf.evaluate(java.lang.Object, int, int, java.lang.Object) @bci=12, line=1 (Interpreted frame)
 - arb.functions.NullaryFunction.evaluate(int) @bci=10, line=88 (Interpreted frame)
 - arb.functions.IntegerNullaryFunction.evaluate() @bci=2, line=33 (Interpreted frame)
 - arb.functions.FloorOfOneHundedOverTheSquareRootOfOneHalf.main(java.lang.String[]) @bci=9, line=18 (Interpreted frame)
```
