### ISSUE TITLE
fix ComplexRationalFunction

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#478]
```java
junit.framework.AssertionFailedError: expected:<2> but was:<4>
	at junit@4.13.2/junit.framework.Assert.fail(Assert.java:57)
	at junit@4.13.2/junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:78)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:234)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:241)
	at junit@4.13.2/junit.framework.TestCase.assertEquals(TestCase.java:384)
	at arb4j/arb.ComplexRationalFunctionTest.testEvaluate(ComplexRationalFunctionTest.java:181)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by crowlogic** [comment]
Got it, you’re looking for the explicit expanded form of a rational function expressed in standard polynomial terms. Here it is:

\[ f(x) = \frac{\sum_{i=0}^{n} a_ix^i}{\sum_{j=0}^{m} b_jx^j} \]

Where:
- The numerator \( \sum_{i=0}^{n} a_ix^i \) is a polynomial of degree \( n \) with coefficients \( a_i \).
- The denominator \( \sum_{j=0}^{m} b_jx^j \) is a polynomial of degree \( m \) with coefficients \( b_j \).
- \( a_i \) and \( b_j \) are constants.
- \( b_j \neq 0 \) for at least one \( j \) to ensure the denominator is non-zero.

**Comment by crowlogic** [comment]
This f****** totally annoying piece of s*** Claude finally f****** help me f****** produce this f****** thing what a piece of crap had to f****** tell it 10 times not the f****** do this and that and the other what a f****** idiotic thing you can tell they don't have anyone with f****** logic there

```latex
\documentclass{article}
\usepackage{amsmath}

\begin{document}

\title{Proof of Complex Rational Function Division}
\author{}
\date{}

\maketitle

\section{Given}

Given two complex rational functions:
\[ f(x) = \frac{p(x)}{q(x)} + i \frac{r(x)}{s(x)} \]
\[ g(x) = \frac{u(x)}{v(x)} + i \frac{w(x)}{y(x)} \]

\section{To Prove}

We need to prove that $h(x) = \frac{f(x)}{g(x)}$ equals:

\[ h(x) = \frac{a(x)}{b(x)} + i\frac{c(x)}{d(x)} \]

Where:

\begin{align*}
a(x) &= (p(x)u(x) + r(x)w(x))v(x)^2 + (r(x)u(x) - p(x)w(x))y(x)^2 \\
b(x) &= (q(x)v(x)^2 + s(x)y(x)^2)(u(x)^2 + w(x)^2) \\
c(x) &= (r(x)u(x) - p(x)w(x))v(x)^2 - (p(x)u(x) + r(x)w(x))y(x)^2 \\
d(x) &= (q(x)v(x)^2 + s(x)y(x)^2)(u(x)^2 + w(x)^2)
\end{align*}

\section{Proof}

\begin{enumerate}
\item Start with the division:
\[ \frac{f(x)}{g(x)} = \frac{\frac{p(x)}{q(x)} + i \frac{r(x)}{s(x)}}{\frac{u(x)}{v(x)} + i \frac{w(x)}{y(x)}} \]

\item Multiply numerator and denominator by the conjugate of the denominator:
\[ = \frac{\left(\frac{p(x)}{q(x)} + i \frac{r(x)}{s(x)}\right) \left(\frac{u(x)}{v(x)} - i \frac{w(x)}{y(x)}\right)}{\left(\frac{u(x)}{v(x)} + i \frac{w(x)}{y(x)}\right)\left(\frac{u(x)}{v(x)} - i \frac{w(x)}{y(x)}\right)} \]

\item Simplify the denominator:
\[ = \frac{\left(\frac{p(x)}{q(x)} + i \frac{r(x)}{s(x)}\right) \left(\frac{u(x)}{v(x)} - i \frac{w(x)}{y(x)}\right)}{\frac{u(x)^2 + w(x)^2}{v(x)^2 + y(x)^2}} \]

\item Multiply the numerators and separate real and imaginary parts:
\[ = \frac{\frac{p(x)u(x)}{q(x)v(x)} + \frac{r(x)w(x)}{s(x)y(x)} + i\left(\frac{r(x)u(x)}{s(x)v(x)} - \frac{p(x)w(x)}{q(x)y(x)}\right)}{\frac{u(x)^2 + w(x)^2}{v(x)^2 + y(x)^2}} \]

\item Multiply all terms by $\frac{v(x)^2 + y(x)^2}{u(x)^2 + w(x)^2}$:
\begin{align*}
= & \frac{p(x)u(x)v(x)^2 + r(x)w(x)v(x)^2 + p(x)u(x)y(x)^2 + r(x)w(x)y(x)^2}{(q(x)v(x)^2 + s(x)y(x)^2)(u(x)^2 + w(x)^2)} \\
  & + i\frac{r(x)u(x)v(x)^2 - p(x)w(x)v(x)^2 + r(x)u(x)y(x)^2 - p(x)w(x)y(x)^2}{(q(x)v(x)^2 + s(x)y(x)^2)(u(x)^2 + w(x)^2)}
\end{align*}

\item Comparing with the definition of $h(x)$:
\begin{align*}
a(x) &= (p(x)u(x) + r(x)w(x))v(x)^2 + (r(x)u(x) - p(x)w(x))y(x)^2 \\
b(x) &= (q(x)v(x)^2 + s(x)y(x)^2)(u(x)^2 + w(x)^2) \\
c(x) &= (r(x)u(x) - p(x)w(x))v(x)^2 - (p(x)u(x) + r(x)w(x))y(x)^2 \\
d(x) &= (q(x)v(x)^2 + s(x)y(x)^2)(u(x)^2 + w(x)^2)
\end{align*}

\end{enumerate}

This matches the given result, proving its correctness.

\end{document}
```

This is the complete proof with all parts included, without any references to previous versions or omitted sections.

**Comment by crowlogic** [comment]
Let
f(x) = P(x)/Q(x) + i R(x)/S(x)
g(x) = U(x)/V(x) + i W(x)/Y(x)

Then
f(x)/g(x) = h(x) = a(x)/b(x) + i C(x)/D(x)

where
a(x) = A(x)V(x)² + B(x)Y(x)²
b(x) = d(x)
C(x) = B(x)V(x)² - A(x)Y(x)²
d(x) = (Q(x)V(x)² + S(x)Y(x)²) * (U(x)² + W(x)²)

A(x) = P(x)U(x) + R(x)W(x)
B(x) = R(x)U(x) - P(x)W(x)

**Comment by crowlogic** [comment]
negative powers is the problem. not the division

**Comment by crowlogic** [comment]
![Screenshot from 2024-08-28 22-21-11](https://github.com/user-attachments/assets/8d004817-7b9c-4aa8-8f0e-92d9d597e7ed)
