### ISSUE TITLE
square root should be complex when it can

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#504]
![Screenshot from 2024-09-28 20-45-25](https://github.com/user-attachments/assets/039e1ef5-a4a5-4938-929b-4c4b8c31ec4f)

**Comment by crowlogic** [comment]
also

```java
java.lang.NoSuchMethodError: 'arb.Real arb.Complex.logΓ(int, arb.Real)'
	at _1+(-((lnΓ(1⁄4+t*I⁄2)-lnΓ(1⁄4-t*I⁄2))*I)⁄2-ln(π)*t⁄2)⁄π+1-I*((ln(ζ(1⁄2+I*t))-ln(ζ(1⁄2-I*t))))⁄(2*π).evaluate(Unknown Source)
	at arb4j/arb.functions.real.RealFunction.evaluate(RealFunction.java:241)
	at arb4j/arb.functions.real.RealFunction.evaluate(RealFunction.java:1)
	at arb4j/arb.expressions.viz.ExpressionTreeView.evaluateExpression(ExpressionTreeView.java:697)
	at arb4j/arb.expressions.viz.Expressor.executeTabAction(Expressor.java:314)
	at arb4j/arb.expressions.viz.Expressor.evaluate(Expressor.java:399)
	at arb4j/arb.expressions.viz.Expressor.lambda$10(Expressor.java:359)
	at javafx.base@22.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)```

**Comment by crowlogic** [comment]
![image](https://github.com/user-attachments/assets/c091206c-9c9d-4f6a-abc4-ad26b4cd47ba)
