### ISSUE TITLE
integer division should result in a fraction

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#547]
see https://github.com/crowlogic/arb4j/issues/545

```java
jshell> var Q = new RationalJacobiPolynomials(RealConstants.half,RealConstants.half);
jshell> seq(0,5,Q);;
|  Exception java.lang.NoSuchMethodError: 'arb.RationalFunction arb.RationalFunction.sub(arb.Real, int, arb.RationalFunction)'
|        at P.evaluate (Unknown Source)
|        at RationalJacobiPolynomials.evaluate (RationalJacobiPolynomials.java:115)
```

**Comment by crowlogic** [comment]
```java
jshell> var P = new RationalJacobiPolynomials(RealConstants.negHalf,RealConstants.negHalf);
jshell> P.evaluate(1,128);
$2 ==> (x)/2
jshell> P.evaluate(0,128);
$3 ==> 1
jshell> P.evaluate(2,128);
$4 ==> (6*x^2-3)/8
jshell> P.evaluate(3,128);
|  Exception arb.exceptions.ArbException: numeratorAddress=140167400341680
denominatorAddress=140167400341616
numerator=140167403622080
denominator=140167403622112

|        at RationalFunction.assertPointerConsistency (RationalFunction.java:581)
|        at RationalFunction.set (RationalFunction.java:649)
|        at RationalFunction.div (RationalFunction.java:74)
|        at P.evaluate (Unknown Source)
|        at P.evaluate (Unknown Source)
|        at RationalJacobiPolynomials.evaluate (RationalJacobiPolynomials.java:116)
|        at RationalJacobiPolynomials.evaluate (RationalJacobiPolynomials.java:1)
|        at Function.evaluate (Function.java:242)
|        at Function.evaluate (Function.java:222)
|        at Sequence.evaluate (Sequence.java:50)
|        at (#5:1)
jshell> 
```

**Comment by crowlogic** [comment]
```java
arb.exceptions.ArbException: numeratorAddress=133078831246784
denominatorAddress=133078831246720
numerator=133078831103888
denominator=133078831103920

	at arb4j/arb.RationalFunction.assertPointerConsistency(RationalFunction.java:581)
	at arb4j/arb.RationalFunction.set(RationalFunction.java:649)
	at arb4j/arb.RationalFunction.div(RationalFunction.java:74)
	at P.evaluate(Unknown Source)
	at P.evaluate(Unknown Source)
	at arb4j/arb.functions.polynomials.RationalJacobiPolynomials.evaluate(RationalJacobiPolynomials.java:116)
	at arb4j/arb.functions.polynomials.RationalJacobiPolynomials.evaluate(RationalJacobiPolynomials.java:1)
	at arb4j/arb.functions.Function.evaluate(Function.java:242)
	at arb4j/arb.functions.Function.evaluate(Function.java:222)
	at arb4j/arb.functions.integer.Sequence.evaluate(Sequence.java:50)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequenceTest.testPRational(JacobiPolynomialSequenceTest.java:53)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:530)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:758)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:453)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:211)

```

**Comment by crowlogic** [comment]
propose to add another generated method to functions generated by the expr compiler, something like this, but with latex versions of the formulas that determine the value presented, as well as text versions, for cross checking :

```java
  public Typesettable intermediateStates()
  {
    return () -> String.format("P[cℤ0001=%s, cℤ0002=%s, cℤ0003=%s, vf0010=%s, vf0011=%s, vf0012=%s, vℚ0006=%s, vℚ0007=%s, vℚ0008=%s, vℚ0009=%s, vℚ0010=%s, vℚ0011=%s, vℚ0012=%s, vℚ0013=%s, vℚ0014=%s, vℚ0015=%s, vℚ0016=%s, vℤ0005=%s, vℤ0006=%s]",
                               cℤ0001,
                               cℤ0002,
                               cℤ0003,
                               vf0010,
                               vf0011,
                               vf0012,
                               vℚ0006,
                               vℚ0007,
                               vℚ0008,
                               vℚ0009,
                               vℚ0010,
                               vℚ0011,
                               vℚ0012,
                               vℚ0013,
                               vℚ0014,
                               vℚ0015,
                               vℚ0016,
                               vℤ0005,
                               vℤ0006);

  }
```

**Comment by crowlogic** [comment]
much cleaner to do it this way

```java
  public String intermediateStates()
  {
    return String.format("P[cℤ0001=%s, cℤ0002=%s, cℤ0003=%s, vf0010=%s, vf0011=%s, vf0012=%s, vℚ0006=%s, vℚ0007=%s, vℚ0008=%s, vℚ0009=%s, vℚ0010=%s, vℚ0011=%s, vℚ0012=%s, vℚ0013=%s, vℚ0014=%s, vℚ0015=%s, vℚ0016=%s, vℤ0005=%s, vℤ0006=%s]",
                         cℤ0001,
                         cℤ0002,
                         cℤ0003,
                         vf0010,
                         vf0011,
                         vf0012,
                         vℚ0006,
                         vℚ0007,
                         vℚ0008,
                         vℚ0009,
                         vℚ0010,
                         vℚ0011,
                         vℚ0012,
                         vℚ0013,
                         vℚ0014,
                         vℚ0015,
                         vℚ0016,
                         vℤ0005,
                         vℤ0006);
  }
```

**Comment by crowlogic** [comment]
cool


```java
jshell> /list

   1 : var F = RealFunction.parse("tanh(log(1+x^2))");
   2 : var f = F.instantiate();
   3 : f
   4 : f.eval(2.3)
   5 : F.inspect(f);
   6 : F.inspect(f);
jshell> F.inspect(f);
$7 ==> 
━━ result=tanh(log(1+x^2))
   f━━ vℝ0003=log(1+x^2)=1.8389610707123490 +/- 3.54e-17
      f━━ vℝ0002=1+x^2=6.2899999999999992 +/- 5.27e-17
         ┃━━ cℤ0001=1=1
         +━━ vℝ0001=x^2=5.2899999999999992 +/- 5.27e-17
            ┃━━ x=x
            ^━━ cℤ0002=2=2

```

**Comment by crowlogic** [comment]
```java
[crow@c15 20241214-10:41:42AM]~$ arb
jshell> var f = RealFunction.parse("tanh(log(1+sin(x)^2))");
jshell> var F = RealFunction.parse("tanh(log(1+sin(x)^2))");
jshell> var f = F.instantiate()
jshell> f.eval(2.3);
$4 ==> 0.4154394149430445
jshell> F.inspect(f);
$5 ==> 
━━ result=tanh(log(1+sin(x)^2))
   f━━ vℝ0004=log(1+sin(x)^2)=0.4421674370663904 +/- 2.62e-17
      f━━ vℝ0003=1+sin(x)^2=1.5560762634675274 +/- 4.33e-17
         ┃━━ cℤ0001=1=1
         +━━ vℝ0002=sin(x)^2=0.5560762634675274 +/- 3.99e-17
            ┃━━ vℝ0001=sin(x)=0.74570521217672029 +/- 7.36e-18
            ┃   f━━ x=x
            ^━━ cℤ0002=2=2

jshell> F.inspect(f);
$6 ==> 
━━ result=tanh(log(1+sin(x)^2))
   f━━ vℝ0004=log(1+sin(x)^2)=0.4421674370663904 +/- 2.62e-17
      f━━ vℝ0003=1+sin(x)^2=1.5560762634675274 +/- 4.33e-17
         ┃━━ cℤ0001=1=1
         +━━ vℝ0002=sin(x)^2=0.5560762634675274 +/- 3.99e-17
            ┃━━ vℝ0001=sin(x)=0.74570521217672029 +/- 7.36e-18
            ┃   f━━ x=x
            ^━━ cℤ0002=2=2

jshell> f.eval(2.5);
$7 ==> 0.29691908059299477
jshell> F.inspect(f);
$8 ==> 
━━ result=tanh(log(1+sin(x)^2))
   f━━ vℝ0004=log(1+sin(x)^2)=0.3061374008338260 +/- 1.54e-17
      f━━ vℝ0003=1+sin(x)^2=1.3581689072683869 +/- 4.99e-17
         ┃━━ cℤ0001=1=1
         +━━ vℝ0002=sin(x)^2=0.35816890726838687 +/- 9.45e-18
            ┃━━ vℝ0001=sin(x)=0.59847214410395649 +/- 7.24e-18
            ┃   f━━ x=x
            ^━━ cℤ0002=2=2

```

**Comment by crowlogic** [comment]
```java
newP java.lang.Throwable
	at arb4j/arb.functions.real.P.<init>(P.java:70)
	at arb4j/arb.functions.real.P.main(P.java:25)

Exception in thread "main" arb.exceptions.CompilerException: Expecting  ']' at position 12 but got char '=' instead, remaining==[0=1, 1=((C(1)*x)-β+α)/2],default=((A(n)*P(n-1))-(B(n)*P(n-2)))/E(n)]

	at arb4j/arb.expressions.Expression.throwUnexpectedCharacterException(Expression.java:2171)
	at arb4j/arb.expressions.Expression.require(Expression.java:1881)
	at arb4j/arb.expressions.Expression.require(Expression.java:1874)
	at arb4j/arb.expressions.Expression.evaluateSquareBracketedIndex(Expression.java:761)
	at arb4j/arb.expressions.Expression.evaluateIndex(Expression.java:670)
	at arb4j/arb.expressions.Expression.evaluateName(Expression.java:683)
	at arb4j/arb.expressions.Expression.resolveIdentifier(Expression.java:1983)
	at arb4j/arb.expressions.Expression.evaluate(Expression.java:657)
	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:784)
	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:812)
	at arb4j/arb.expressions.Expression.resolve(Expression.java:1897)
	at arb4j/arb.expressions.Expression.parseRoot(Expression.java:1737)
	at arb4j/arb.functions.Function.parse(Function.java:199)
	at arb4j/arb.functions.integer.Sequence.parse(Sequence.java:118)
	at arb4j/arb.functions.real.P.expression(P.java:20)
	at arb4j/arb.functions.real.P.main(P.java:26)
```

**Comment by crowlogic** [comment]
make this latexified


```java

jshell> P.in
initialize()           intermediateStates()   inverse(               
jshell> P.intermediateStates()
$6 ==> "P[cℤ0001=0, cℤ0002=1, cℤ0003=2, vf0010=0⁄0, vf0011=45⁄4, vf0012=9, vℚ0006=0, vℚ0007=0, vℚ0008=0, vℚ0009=0, vℚ0010=0, vℚ0011=30*x, vℚ0012=(6*x^2-3)/8, vℚ0013=(90*x^3-45*x)/4, vℚ0014=(x)/2, vℚ0015=(45*x)/8, vℚ0016=(180*x^3-135*x)/8, vℤ0005=2, vℤ0006=1]"
jshell> 
```

**Comment by crowlogic** [comment]
heres the cause

```java
                          operation=mul,
                          right=C(n/2)(FunctionNode),
                          right.type=class arb.Fraction,
                          resultType=class arb.Fraction )


Variable(#112302969).generate( this=n, resultType=class arb.Integer)

FunctionCall.generate: this=C(n/2) resultType=class arb.Fraction

BinaryOperation.generate( this=n/2,
                          left=n(VariableNode),
                          left.type=class arb.Integer,
                          operation=div,
                          right=2(LiteralConstantNode),
                          right.type=class arb.Integer,
                          resultType=class arb.Integer )


Variable(#707976812).generate( this=n, resultType=class arb.Integer)

FunctionCall.generate: this=C(n-1) resultType=class arb.Fraction
```
