### ISSUE TITLE
hypergeometric functional bug

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#557]
```java
java.lang.NoSuchMethodError: 'arb.RealPolynomial arb.Fraction.div(arb.RealPolynomial, int, arb.RealPolynomial)'
	at factorXℝ0001.evaluate(Unknown Source)
	at arb4j/arb.functions.Function.evaluate(Function.java:236)
	at F.evaluate(Unknown Source)
	at arb4j/arb.functions.HypergeometricFunction.evaluate(HypergeometricFunction.java:228)
	at arb4j/arb.functions.HypergeometricFunction.evaluate(HypergeometricFunction.java:1)
	at Vplusfunc.initialize(Unknown Source)
	at Vplus.evaluate(Unknown Source)
	at arb4j/arb.functions.Function.evaluate(Function.java:242)
	at arb4j/arb.functions.Function.evaluate(Function.java:222)
	at arb4j/arb.functions.integer.Sequence.evaluate(Sequence.java:50)
	at arb4j/arb.expressions.ExpressionTest.testRealSequenceOfHypergeometricFunctions(ExpressionTest.java:54)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:530)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:758)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:453)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:211)

```

**Comment by crowlogic** [comment]
needs to use RationaFunctions interally instead of RealPolynomials when the codomain is a function that returns a scalar rather than a function that returns a rational or polynomial function
