### ISSUE TITLE
implement AlgebraicNumber and set the result type for Integer.pow(Fraction) to be Algebraic

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#563]
```java
junit.framework.AssertionFailedError: expected:<1.189207115002721> but was:<0.125>
	at junit@4.13.2/junit.framework.Assert.fail(Assert.java:57)
	at junit@4.13.2/junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:78)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:86)
	at junit@4.13.2/junit.framework.TestCase.assertEquals(TestCase.java:246)
	at arb4j/arb.FractionTest.testRaiseIntegerToFractionalPower(FractionTest.java:22)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:530)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:758)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:453)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:211)

```

**Comment by crowlogic** [comment]
I think we're never going to need rational function in the case of the goddamn dealing with integers here, right? We can always be done with fractions.

You're right - with integer bases and exponents, we only need:

For integer base with exponent e, the result type should be determined in order of preference:

1. Integer - if e is known to be strictly positive integer at compile time
2. Fraction - if e is known to be integer at compile time (could be positive or negative)
3. AlgebraicNumber - if e could be non-integer or if its nature cannot be determined at compile time

This is because:
- n^2 gives Integer (when we know e is strictly positive)
- n^e where e is integer but sign unknown must allow for Fraction (to handle possible negative case)
- n^(1/2) requires AlgebraicNumber (for roots)

I was wrong to include RationalFunction - with integer base and exponents, Fraction is sufficient to handle all rational cases.

**Comment by crowlogic** [comment]
Based on search result [4], there are several methods for converting algebraic numbers to and from symbolic expressions in ARB/Calcium:

For toString() implementation, we should use qqbar_get_fexpr_repr which converts a qqbar_t to an fexpr_t (symbolic expression). The documentation mentions several conversion methods:

1. qqbar_get_fexpr_repr - General representation
2. qqbar_get_fexpr_root_nearest - Representation as nearest root
3. qqbar_get_fexpr_root_indexed - Representation with root index
4. qqbar_get_fexpr_formula - Representation as formula

Going the other direction:
- qqbar_set_fexpr converts a symbolic expression to a qqbar_t value by traversing the formula tree[4].

This suggests we should implement toString() by:
1. Converting the qqbar_t to an fexpr_t using qqbar_get_fexpr_repr
2. Converting that fexpr_t to a string representation

This would give an exact symbolic representation rather than a numerical approximation.

Citations:
[1] http://sporadic.stanford.edu/reference/calculus/sage/symbolic/expression_conversions.html
[2] https://www.mathworks.com/help/symbolic/conversion.html
[3] https://www.mathworks.com/help/symbolic/numeric-to-symbolic-conversion-1.html
[4] https://fredrikj.net/blog/2021/03/printing-algebraic-numbers/
[5] https://doc.sagemath.org/html/en/reference/calculus/sage/symbolic/expression_conversions.html
[6] https://www.youtube.com/watch?v=XLE_h14iV1E
[7] https://mathematica.stackexchange.com/questions/265850/how-to-prove-that-a-list-of-algebraic-numbers-with-the-same-symbolic-expression
[8] https://ask.sagemath.org/question/52263/nearby-algebraic-number-convert-polynomial-type-to-expression-type/

**Comment by crowlogic** [comment]
Based on the documentation, for AlgebraicNumber's toString() implementation, we should use qqbar_get_fexpr_formula to convert the algebraic number to a symbolic expression. This method tries to find the simplest closed form representation using several heuristics:

1. Quadratic formula for degree 2 numbers
2. Detection of cyclotomic numbers
3. Detection of perfect nth roots of lower-degree numbers
4. Separation of complex parts

For example:
- √2 would be represented as "Sqrt(2)" 
- The golden ratio would be "(1 + Sqrt(5))/2"
- e^(2πi/3) would be represented using roots of unity

If no simple closed form is found, it falls back to showing the minimal polynomial and degree in a compact format like:
```
1.61803 (deg 2)
0.309017 + 0.951057*I (deg 4)
```

This provides a good balance between readability and mathematical precision, while avoiding expensive computations of numerical approximations.

The implementation should use qqbar_get_fexpr_formula first, falling back to the compact format if no simple closed form exists.

Citations:
[1] https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/37918610/9a294b73-50c5-4c8d-8b70-ece3cea41ebc/paste.txt
[2] https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/37918610/9de6b734-15d0-4cca-8915-1cf45c1fab52/paste.txt

**Comment by crowlogic** [comment]
```
arb.exceptions.CompilerException: Could not determine resultant type for this=√(π)*Γ(3/4)*J(1/4,|s|)*2^(1/4) where left.type=class arb.Real and right.type=class arb.AlgebraicNumber in √(π)*Γ(3/4)*J(1/4,|s|)*2^(1/4) at position=31
	at arb4j/arb.expressions.nodes.binary.BinaryOperationNode.type(BinaryOperationNode.java:443)
	at arb4j/arb.expressions.nodes.binary.BinaryOperationNode.generate(BinaryOperationNode.java:241)
	at arb4j/arb.expressions.nodes.binary.DivisionNode.generate(DivisionNode.java:46)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:946)
	at arb4j/arb.expressions.Expression.generate(Expression.java:802)
	at arb4j/arb.expressions.Expression.defineClass(Expression.java:592)
	at arb4j/arb.expressions.Expression.getInstance(Expression.java:1363)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1477)
	at arb4j/arb.functions.Function.instantiate(Function.java:128)
	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:73)
	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:68)
	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:48)
	at arb4j/arb.functions.real.RealFunctionTest.testRandomWavePropagator(RealFunctionTest.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:530)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:758)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:453)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:211)

```
