### ISSUE TITLE
 AlgebraicNumber support

### ISSUE THREAD

**Issue by crowlogic** [crowlogic/arb4j#566]

**Comment by crowlogic** [comment]
Need toString methodf


```java
junit.framework.AssertionFailedError: expected:<1.189207115002721> but was:<arb.AlgebraicNumber@446a1e84>
	at junit@4.13.2/junit.framework.Assert.fail(Assert.java:57)
	at junit@4.13.2/junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:78)
	at junit@4.13.2/junit.framework.Assert.assertEquals(Assert.java:86)
	at junit@4.13.2/junit.framework.TestCase.assertEquals(TestCase.java:246)
	at arb4j/arb.FractionTest.testRaiseIntegerToFractionalPower(FractionTest.java:22)
	
```

**Comment by crowlogic** [comment]
```java
java.lang.NoSuchMethodError: 'arb.Real arb.Integer.pow(arb.Fraction, int, arb.Real)'
	at _2^(1⁄4).evaluate(Unknown Source)
	at arb4j/arb.functions.NullaryFunction.evaluate(NullaryFunction.java:92)
	at arb4j/arb.functions.NullaryFunction.evaluate(NullaryFunction.java:97)
	at arb4j/arb.FractionTest.testRaiseIntegerToFractionalPower(FractionTest.java:21)

```
